import type { HelpCatalog } from "../types";

export const helpDe: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Erste Schritte",
      blurb: "Von der ersten Idee bis zum vollständigen Validierungslauf.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Abrechnung & Kampagnen",
      blurb: "Wofür Sie zahlen, was einen Report verbraucht und was zu tun ist, wenn nichts mehr übrig ist.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Scores & Urteile",
      blurb: "Was der Stempel bedeutet und wie Sie den Report lesen.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Arbeiten im Studio",
      blurb: "Fragen, neu bewerten, Angles und Kill-Tests – ohne Läufe zu verschwenden.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Konto & Sprache",
      blurb: "Locale, Datenschutz und Kontakt zum Team.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Verbraucht Chat einen vollständigen Report?", slug: "iterate" },
    { q: "Was hat meine Kampagne freigeschaltet?", slug: "campaigns-and-pricing" },
    { q: "Was bedeuten GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Ich kann keine weitere Analyse starten", slug: "cant-run-analysis" },
    { q: "Warum hat sich mein Score nach einem Re-Run geändert?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Ihre erste Idee validieren",
      summary:
        "Konto anlegen, Idee beschreiben, Kampagne freischalten und einen fundierten Score erhalten.",
      eyebrow: "Hier starten",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "erste",
        "anmelden",
        "starten",
        "freischalten",
        "einstieg",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian ist ein Studio zur Geschäftsvalidierung. Sie beschreiben eine Idee im Kontext Ihres Ziels und erhalten ein evidenzbasiertes GO / MAYBE / NO-GO mit Markt, Geld, Risiken und dem nächsten Test. Keine Motivationsrede.",
        },
        { type: "h2", text: "Der Weg" },
        {
          type: "ol",
          items: [
            "Kostenloses Konto anlegen und das Studio öffnen.",
            "Beschreiben Sie, was Sie anbieten, für wen und warum jetzt. Legen Sie Ihr Ziel fest (Nebeneinkommen, Lifestyle, Venture oder unsicher), damit die GO-Hürde zu Ihnen passt.",
            "Wenn Sie bereit zum Scoren sind, schalten Sie eine vollständige Kampagne für diese Idee frei (ein Preis pro Idee; aktueller Betrag unter Pricing).",
            "Lesen Sie zuerst den Stempel und die Entscheidungsfläche, dann bei Bedarf Markt, Geld und Evidenz.",
            "Iterieren: Pitch umschreiben, anderen Angle versuchen, Fragen zur Review stellen oder einen realen Kill-Test fahren.",
          ],
        },
        {
          type: "callout",
          text: "Chat zur Review verbraucht nie einen gescoreten Report. Vollständige Re-Scores und Deep-Analysen nutzen das Kampagnen-Kontingent.",
        },
        { type: "h2", text: "Was Sie in einem vollständigen Lauf bekommen" },
        {
          type: "ul",
          items: [
            "Urteil und Score (GO / MAYBE / NO-GO) mit Konfidenz und zielbezogenen Bändern",
            "Nachfrage, Zahlungsbereitschaft, Wettbewerb und erzielbarer Umsatz",
            "Risikokarte und Pre-Mortem",
            "Käuferprofil und Kanäle",
            "Realer Testplan (Kill-Test) mit Pass/Fail-Schwellen",
            "Evidenz aus öffentlichen Quellen (Posts, Reviews, Issues) mit Links",
            "Raum zum Iterieren: neue Versionen, Angles und unbegrenzte Fragen zur Review dieser Idee",
          ],
        },
        {
          type: "p",
          text: "Ein vollständiger Lauf kann einige Minuten dauern — echte Web-Suche und Scoring, keine Sofort-Vermutung.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Kampagnen und Preise",
      summary: "Ein Preis pro Idee; was freigeschaltet wird und was als vollständiger Report zählt.",
      eyebrow: "Abrechnung",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "bezahlen",
        "preis",
        "freischalten",
        "abo",
        "kosten",
        "geld",
      ],
      blocks: [
        {
          type: "p",
          text: "Das Konto ist kostenlos. Ein Kampagnen-Pass schaltet den vollständigen Validierungspfad für eine Idee frei: gescorete Reports (bis zur enthaltenen Obergrenze, standardmäßig 10 vollständige Analysen), Wedges, Kill-Test-Kit, Wettbewerber-Intel und unbegrenzter Chat zu dieser Idee. Kein Abo.",
        },
        { type: "h2", text: "Was einen Report-Slot verbraucht" },
        {
          type: "table",
          headers: ["Aktion", "Verbraucht einen vollständigen gescoreten Report?"],
          rows: [
            ["Fragen / Chat zur Review", "Nein"],
            ["Report lesen oder aufklappen", "Nein"],
            ["Neue Version + Re-Score", "Ja"],
            ["Deep Validation", "Ja (schwererer Lauf)"],
            ["Angle- / Wedge-Turnier (jeder gescorete Teilnehmer)", "Ja, pro Analyse"],
            ["Interview-Kit oder Intel-Pack", "Nein (braucht Freischaltung, keinen Report-Slot)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Nur vollständige gescorete Analysen verbrauchen einen Report-Slot",
            "Sind die enthaltenen Reports aufgebraucht, bleiben Chat und bestehende Reports offen",
            "Eine andere Idee braucht einen eigenen Kampagnen-Pass",
          ],
        },
        {
          type: "callout",
          text: "Aktueller Preis und FAQ unter Pricing. Abrechnungsfragen: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Ich kann keine weitere Analyse starten",
      summary:
        "Kampagne gesperrt, Reports aufgebraucht oder der Button ist aus einem anderen Grund deaktiviert.",
      eyebrow: "Fehlerbehebung",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "aufgebraucht",
        "gesperrt",
        "blockiert",
        "scoren",
        "deaktiviert",
        "limit",
      ],
      blocks: [
        {
          type: "p",
          text: "Wenn Validate, Re-Score oder Deep Validation blockiert sind, prüfen Sie der Reihe nach Folgendes.",
        },
        {
          type: "ol",
          items: [
            "Kampagne gesperrt: Diese Idee wurde nie freigeschaltet. Öffnen Sie Freischaltung / Pricing für diese Idee.",
            "Reports aufgebraucht: Sie haben die im Pass enthaltenen vollständigen gescoreten Analysen genutzt. Chat und Lesen bleiben offen. Starten Sie eine neue Idee, um etwas anderes zu validieren.",
            "Lauf noch aktiv: Warten Sie, bis die aktuelle Analyse fertig ist.",
            "Keine substanzielle Änderung: Wenn Sie den aktuellen Report nur verstehen wollen, nutzen Sie Ask (ohne Re-Score), statt einen weiteren Lauf zu verbrauchen.",
          ],
        },
        {
          type: "callout",
          text: "Immer noch fest? Schreiben Sie an help@validorian.com mit Ihrer Konto-E-Mail und dem Ideentitel.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE und NO-GO",
      summary: "Was jeder Stempel bedeutet und was als Nächstes zu tun ist.",
      eyebrow: "Urteile",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "stempel",
        "urteil",
        "vorgehen",
        "stoppen",
      ],
      blocks: [
        {
          type: "p",
          text: "Der Stempel ist die Entscheidung. Die Zahl stützt ihn, aber der Stempel beantwortet, ob Sie unter dem gesetzten Ziel fortfahren sollten.",
        },
        {
          type: "ul",
          items: [
            "GO: Die Evidenz spricht dafür, dieses Framing für Ihr Ziel zu verfolgen. Bauen und testen Sie mit Absicht. Öffnen Sie den Plan, wenn Sie bereit sind.",
            "MAYBE: Gemischt oder grenzwertig. Idee verbessern, einen Kill-Test beweisen oder den Angle ändern, bevor Sie all-in gehen.",
            "NO-GO: So formuliert für Ihr Ziel zu schwach. Hart pivoten oder stoppen. Polieren Sie keinen fatalen Mismatch.",
            "INSUFFICIENT: Die Konfidenz ist zu niedrig für eine ehrliche Bewertung. Aussage klären, Kontext ergänzen oder nach besserer Evidenz neu laufen lassen.",
          ],
        },
        {
          type: "callout",
          text: "Nebeneinkommen und Venture-Raise werden nicht gleich bewertet. Ein Score, der für ein Ziel GO erreicht, kann für ein anderes in MAYBE liegen.",
        },
        {
          type: "p",
          text: "UI-Labels können in Ihrer Sprache erscheinen (zum Beispiel koreanische Stempel). Das Scoring nutzt darunter weiterhin dieselben GO- / MAYBE- / NO-GO-Regeln.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Ihren Report lesen",
      summary:
        "Wie Sie Entscheidungsfläche, Brief, Markt, Geld, Risiken, Plan und Evidenz scannen.",
      eyebrow: "Der Report",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "abschnitte",
        "markt",
        "geld",
        "risiken",
        "evidenz",
      ],
      blocks: [
        {
          type: "p",
          text: "Wenn Sie nur einmal überfliegen: Stempel, warum dieser Score, offene Fragen, dann der Kill-Test. Kapitel nur aufklappen, wenn Sie Tiefe brauchen.",
        },
        {
          type: "ol",
          items: [
            "Stempel und Score: Ziel-Fit und warum dieser Score (Bremsen und Hebel).",
            "Brief: Schmerzmittel vs. Vitamin, Stärken, offene Fragen.",
            "Markt: Größenordnung, Wettbewerber, Kanäle, Verteidigbarkeit.",
            "Geld: Unit Economics und Projektionen (Schätzungen, keine Versprechen).",
            "Risiken: Matrix und Pre-Mortem, bevor Sie die roten Zellen ignorieren.",
            "Plan: Gesperrt, bis GO oder ein bestandener Kill-Test einen Build-Pfad rechtfertigt.",
            "Evidenz: Das Corpus hinter dem Demand-Read (Belege, nicht Dekoration).",
          ],
        },
        {
          type: "callout",
          text: "Im Studio bleiben Kapitel zugeklappt, damit die Entscheidung führt. Öffnen Sie nur, was Sie brauchen.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Wie das Scoring funktioniert",
      summary:
        "Kriterien, Gewichte und Gates. Optionale Lektüre, wenn ein Badge oder eine Anpassung verwirrt.",
      eyebrow: "Unter der Haube",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "kriterien",
        "gewichte",
        "bänder",
        "anpassungen",
        "vertrauen",
      ],
      blocks: [
        {
          type: "p",
          text: "Sie brauchen diese Seite nicht, um Validorian zu nutzen. Öffnen Sie sie, wenn eine Scoring-Notiz, ein Borderline-Badge oder ein Clamp rätselhaft wirkt.",
        },
        {
          type: "p",
          text: "Kurz gesagt: Das Modell schreibt pro Faktor eine kurze Begründung und eine Buchstabennote. Software macht daraus Zahlen, gewichtet sie für Ihr Ziel und wendet harte Regeln an, damit ein fataler Schwachpunkt nicht durch Stärken anderswo weggemittelt werden kann.",
        },
        { type: "h2", text: "Die zehn Kriterien" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Wem Sie vertrauen sollten" },
        {
          type: "ul",
          items: [
            "Abgerufene Evidenz (Posts, Reviews) mit echten Links und Vote-Counts",
            "Gates und Clamps in den Scoring-Notizen, wenn sie greifen",
            "Borderline-Badges, wenn der Score nahe an einer GO- oder MAYBE-Linie liegt (Re-Runs können umkippen)",
          ],
        },
        {
          type: "p",
          text: "Marktzahlen und manche Wettbewerber-Notizen sind Modellschätzungen aus der Suche. Prüfen Sie Quellen, bevor Sie die Firma wetten.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Warum hat sich mein Score geändert?",
      summary: "Re-Runs, Zielwechsel, neues Framing und normales Scoring-Rauschen.",
      eyebrow: "Fehlerbehebung",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "abweichung",
        "anders",
        "kippen",
        "rauschen",
        "erneut",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Sie haben Ideenaussage, Ziel oder Founder-Kontext geändert: Der Score sollte sich ändern.",
            "Borderline-Scores: Das Produkt markiert, wenn Sie innerhalb des Lauf-zu-Lauf-Rauschens einer Schwelle liegen. Ein Re-Run kann auf der anderen Seite landen, ohne dass das System kaputt ist.",
            "Neue Evidenz oder ein Kill-Test-Ergebnis: Felddaten können Nachfrage und Urteil ehrlich verschieben.",
            "Deep Validation: Ein schwererer Lauf kann Konfidenz und Notizen anpassen; behandeln Sie ihn als zweiten Blick, nicht als anderes Produkt.",
          ],
        },
        {
          type: "callout",
          text: "Wenn das Framing unverändert ist und der Sprung wild wirkt, schreiben Sie an help@validorian.com mit Ideentitel und Versionen.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Iterieren, ohne Läufe zu verschwenden",
      summary: "Fragen, neue Versionen, Angles und wann neu scoren.",
      eyebrow: "Studio-Schleife",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "fragen",
        "version",
        "winkel",
        "keil",
        "neu bewerten",
        "lauf",
      ],
      blocks: [
        {
          type: "p",
          text: "Ein Lauf (oder vollständiger gescoreter Report) ist eine tiefe Analyse, die Kampagnen-Kontingent verbraucht. Nutzen Sie Ask, wenn Sie nur die aktuelle Review verstehen wollen.",
        },
        { type: "h2", text: "Was verbraucht einen Report?" },
        {
          type: "table",
          headers: ["Aktion", "Verbraucht einen vollständigen gescoreten Report?"],
          rows: [
            ["Ask (Chat zu dieser Analyse)", "Nein"],
            ["Neue Version + Re-Score", "Ja"],
            ["Angles vergleichen / Wedge-Turnier", "Ja, pro gescoretem Angle"],
            ["Deep Validation", "Ja"],
            ["Kill-Test-Kit, Intel, Report lesen", "Nein"],
          ],
        },
        { type: "h2", text: "Ask (ohne Re-Score)" },
        {
          type: "p",
          text: "Sprechen Sie den aktuellen Report durch: Scores, Wettbewerber, Risiken. Erzeugt keine Version und nutzt keine vollständige Analyse.",
        },
        { type: "h2", text: "Neue Version" },
        {
          type: "p",
          text: "Ändern Sie Aussage, Ziel oder Kontext und scoren Sie neu. Nutzen Sie das nach einer echten Änderung am Framing oder an der Evidenz — nicht nach jeder Neugier.",
        },
        { type: "h2", text: "Angles vergleichen" },
        {
          type: "p",
          text: "Ein Angle (manchmal Alpha oder Wedge genannt) ist eine andere Kante oder Positionierung derselben Kernidee. Turniere scoren einige dieser Kanten im direkten Vergleich auf derselben Evidenz. Jeder gescorete Teilnehmer nutzt einen Report-Slot — wählen Sie bewusst.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-Tests und Interviews",
      summary: "Der günstigste Realitätscheck, bevor Sie bauen.",
      eyebrow: "Feldarbeit",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "gespräch",
        "käufer",
        "bestehen",
        "scheitern",
        "feld",
      ],
      blocks: [
        {
          type: "p",
          text: 'Ein MAYBE oder NO-GO heißt oft nicht „im Deck härter versuchen“. Es heißt: „Mit Käufern sprechen – mit vorab festgelegter Pass/Fail-Schwelle.“',
        },
        {
          type: "ul",
          items: [
            "Riskanteste Annahme: was das Corpus nicht geklärt hat",
            "Günstigster Test (etwa eine Woche oder weniger) mit einem Kanal",
            "Pass- und Kill-Schwellen, bevor Sie Ergebnisse sehen",
            "Interview-Kit: mit wem sprechen und Mom-Test-Fragen (Vergangenes Verhalten und Fakten, keine Komplimente zu Ihrer Idee)",
          ],
        },
        {
          type: "p",
          text: "Ergebnis festhalten und neu scoren, damit das Urteil aus Felddaten kommt – nicht aus Hoffnung.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Deep Validation",
      summary: "Wann der schwerere Lauf einen Report-Slot wert ist.",
      eyebrow: "Erweitert",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "tief",
        "teuer",
        "schwer",
        "zweite meinung",
      ],
      blocks: [
        {
          type: "p",
          text: "Deep Validation ist eine optionale, schwerere Analyse (unabhängige Cases, zusätzliche Checks). Sie verbraucht einen vollständigen gescoreten Report und kostet mehr Compute als ein Standardlauf.",
        },
        {
          type: "ul",
          items: [
            "Nutzen Sie sie, wenn die Idee ernst ist und Sie einen zweiten, härteren Blick wollen",
            "Überspringen Sie sie bei frühen Entwürfen und günstigen Experimenten",
            "Sie ersetzt keinen Kill-Test mit echten Käufern",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Sprache und KI-Ausgabe",
      summary: "UI-Sprache vs. Sprache der Report-Prosa.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "sprache",
        "übersetzen",
        "globus",
        "deutsch",
        "koreanisch",
      ],
      blocks: [
        {
          type: "p",
          text: "Der Globus-Umschalter setzt das UI-Chrome: Navigation, Buttons, Abschnittsüberschriften, Urteilsstempel und Labels. Sie können Sprachen nach Name oder Code suchen (zum Beispiel Koreanisch, 한국어 oder ko).",
        },
        {
          type: "p",
          text: "KI-geschriebener Fließtext (Zusammenfassungen, Wettbewerber-Notizen, offene Fragen) folgt der Sprache, die beim Generieren oder Re-Scoren aktiv war. Alte englische Reports bleiben Englisch, bis Sie unter der neuen Locale neu laufen lassen.",
        },
        {
          type: "ul",
          items: [
            "Sprache jederzeit über den Header wechseln",
            "Maschinen-Codes in gespeicherten Daten (Urteile, Kriteriums-Namen) bleiben Englisch für Scoring-Konsistenz",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Datenschutz und Ihre Ideen",
      summary: "Wer sieht, was Sie im Studio eingeben.",
      eyebrow: "Vertrauen",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privat",
        "daten",
        "sicherheit",
        "teilen",
        "geheim",
        "datenschutz",
      ],
      blocks: [
        {
          type: "p",
          text: "Ideen und Reports in Ihrem Konto sind standardmäßig privat. Sie werden nicht in einem öffentlichen Feed veröffentlicht.",
        },
        {
          type: "ul",
          items: [
            "Sie steuern das Konto, dem jede Idee gehört",
            "API-Keys greifen, falls Sie welche anlegen, nur auf Ideen dieses Keys bzw. Kontomodells zu",
            "Wir nutzen Modell-Anbieter zum Scoren und Schreiben von Reports: Fügen Sie keine Geheimnisse ein, die Sie nicht an Verarbeitungssysteme senden können",
            "Konto-Löschfunktionen entfernen Ihre Daten gemäß dem Konto-Flow des Produkts",
          ],
        },
        {
          type: "callout",
          text: "Fragen zum Umgang mit Daten: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Hilfe vom Team holen",
      summary: "Wie Sie uns erreichen und was Sie mitschicken sollten.",
      eyebrow: "Menschen",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "e-mail",
        "hilfe",
        "kontakt",
        "fehler",
        "mensch",
      ],
      blocks: [
        {
          type: "p",
          text: "Bei Produktproblemen, Abrechnung oder einer stecken gebliebenen Kampagne: help@validorian.com. Support und Contact gehen derzeit in dasselbe Postfach.",
        },
        {
          type: "ul",
          items: [
            "Konto-E-Mail und Ideentitel angeben, falls relevant",
            "Screenshots helfen bei UI-Bugs",
            "Niemals Passwörter senden",
          ],
        },
      ],
    },
  ],
};
