import type { HelpCatalog } from "../types";

export const helpEs: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Primeros pasos",
      blurb: "De la primera idea a un pase completo de validación.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Facturación y campañas",
      blurb: "Qué pagas, qué consume un informe y qué hacer cuando se te acaban.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Puntuaciones y veredictos",
      blurb: "Qué significa el sello y cómo leer el informe.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Trabajar en el estudio",
      blurb: "Pregunta, re-puntúa, ángulos y kill-tests sin desperdiciar ejecuciones.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Cuenta e idioma",
      blurb: "Idioma, privacidad y cómo contactar al equipo.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "¿El chat consume un informe completo?", slug: "iterate" },
    { q: "¿Qué desbloqueó mi campaña?", slug: "campaigns-and-pricing" },
    { q: "¿Qué significa GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "No puedo lanzar otro análisis", slug: "cant-run-analysis" },
    { q: "¿Por qué cambió mi puntuación tras un re-run?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Valida tu primera idea",
      summary:
        "Crea una cuenta, describe la idea, desbloquea una campaña y obtén una puntuación fundamentada.",
      eyebrow: "Empieza aquí",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "primero",
        "registro",
        "empezar",
        "desbloquear",
        "inicio",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian es un estudio de validación de negocios. Describes una idea frente a tu objetivo y recibes un GO / MAYBE / NO-GO respaldado por evidencia, con mercado, dinero, riesgos y una próxima prueba. No es un discurso motivacional.",
        },
        { type: "h2", text: "El camino" },
        {
          type: "ol",
          items: [
            "Crea una cuenta gratis y abre el estudio.",
            "Describe qué ofreces, para quién y por qué ahora. Define tu objetivo (side hustle, lifestyle, venture o no estoy seguro) para que el listón de GO coincida contigo.",
            "Cuando quieras puntuar, desbloquea una campaña completa en esa idea (un precio por idea; consulta Pricing para el importe actual).",
            "Lee primero el sello y la superficie de decisión; luego profundiza en mercado, dinero y evidencia según necesites.",
            "Itera: reescribe el pitch, prueba otro ángulo, haz preguntas sobre la revisión o lanza un kill-test en el mundo real.",
          ],
        },
        {
          type: "callout",
          text: "Chatear con la revisión nunca consume un informe puntuado. Las re-puntuaciones completas y los análisis profundos usan la asignación de la campaña.",
        },
        { type: "h2", text: "Qué obtienes en un pase completo" },
        {
          type: "ul",
          items: [
            "Veredicto y puntuación (GO / MAYBE / NO-GO) con confianza y bandas relativas a tu objetivo",
            "Demanda, disposición a pagar, competencia e ingresos alcanzables",
            "Mapa de riesgos y pre-mortem",
            "Perfil de comprador y canales",
            "Plan de prueba en el mundo real (kill-test) con umbrales de pase/fallo",
            "Evidencia de fuentes públicas (posts, reseñas, issues) con enlaces",
            "Espacio para iterar: nuevas versiones, ángulos y preguntas ilimitadas sobre la revisión de esa idea",
          ],
        },
        {
          type: "p",
          text: "Un pase completo puede tardar unos minutos: búsqueda web real y puntuación, no una conjetura al instante.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campañas y precios",
      summary: "Un precio por idea; qué se desbloquea y qué cuenta como informe completo.",
      eyebrow: "Facturación",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "pagar",
        "precio",
        "desbloquear",
        "suscripción",
        "coste",
        "dinero",
        "campaña",
      ],
      blocks: [
        {
          type: "p",
          text: "La cuenta es gratis. Un pase de campaña desbloquea una ruta completa de validación en una idea: informes puntuados (hasta el tope incluido, por defecto 10 análisis completos), wedges, kit de kill-test, intel de competidores y chat ilimitado en esa idea. Sin suscripción.",
        },
        { type: "h2", text: "Qué consume un slot de informe" },
        {
          type: "table",
          headers: ["Acción", "¿Usa un informe puntuado completo?"],
          rows: [
            ["Preguntar / chatear sobre la revisión", "No"],
            ["Leer o expandir el informe", "No"],
            ["Nueva versión + re-puntuación", "Sí"],
            ["Validación profunda", "Sí (ejecución más pesada)"],
            ["Torneo de ángulos / wedges (cada entrante puntuado)", "Sí, por análisis"],
            ["Kit de entrevistas o paquete de intel", "No (necesita desbloqueo, no un slot de informe)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Solo los análisis puntuados completos consumen un slot de informe",
            "Cuando se agotan los informes incluidos, el chat y los informes existentes siguen abiertos",
            "Otra idea necesita su propio pase de campaña",
          ],
        },
        {
          type: "callout",
          text: "Consulta Pricing para el precio en vivo y el FAQ. Problemas de facturación: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "No puedo lanzar otro análisis",
      summary:
        "Campaña bloqueada, informes agotados o el botón desactivado por otro motivo.",
      eyebrow: "Solución de problemas",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "agotado",
        "bloqueado",
        "no puedo puntuar",
        "desactivado",
        "límite",
      ],
      blocks: [
        {
          type: "p",
          text: "Si Validate, re-puntuación o validación profunda está bloqueado, revisa esto en orden.",
        },
        {
          type: "ol",
          items: [
            "Campaña bloqueada: esta idea nunca se desbloqueó. Abre desbloqueo / Pricing para esa idea.",
            "Informes completados: usaste todos los análisis puntuados incluidos en el pase. Chat y lectura siguen abiertos. Empieza una idea nueva para validar algo distinto.",
            "Trabajo en curso: espera a que termine el análisis actual.",
            "Sin cambio material: si solo quieres entender el informe actual, usa Ask (sin re-puntuación) en lugar de gastar otra ejecución.",
          ],
        },
        {
          type: "callout",
          text: "¿Sigues atascado? Escribe a help@validorian.com con el email de tu cuenta y el título de la idea.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE y NO-GO",
      summary: "Qué significa cada sello y qué hacer después.",
      eyebrow: "Veredictos",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "sello",
        "veredicto",
        "aprobado",
        "fallo",
        "insuficiente",
      ],
      blocks: [
        {
          type: "p",
          text: "El sello es la decisión. El número lo respalda, pero el sello responde si conviene seguir con el objetivo que definiste.",
        },
        {
          type: "ul",
          items: [
            "GO: la evidencia apoya perseguir este encuadre para tu objetivo. Construye y prueba con intención. Abre el plan cuando estés listo.",
            "MAYBE: mixto o en el límite. Mejora la idea, demuestra un kill-test o cambia el ángulo antes de ir a fondo.",
            "NO-GO: tal como está escrita, débil para tu objetivo. Pivota con fuerza o para. No pulas un desajuste fatal.",
            "INSUFFICIENT: la confianza es demasiado baja para calificar con honestidad. Aclara el planteamiento, añade contexto o vuelve a ejecutar cuando haya mejor evidencia.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle y round de venture no se califican igual. Una puntuación que es GO para un objetivo puede quedar en MAYBE para otro.",
        },
        {
          type: "p",
          text: "Las etiquetas de la UI pueden aparecer en tu idioma (por ejemplo sellos en coreano). La puntuación sigue las mismas reglas GO / MAYBE / NO-GO por debajo.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Cómo leer tu informe",
      summary:
        "Cómo escanear la superficie de decisión, el brief, mercado, dinero, riesgos, plan y evidencia.",
      eyebrow: "El informe",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "secciones",
        "mercado",
        "dinero",
        "riesgos",
        "evidencia",
        "informe",
      ],
      blocks: [
        {
          type: "p",
          text: "Si solo miras una vez: sello, por qué esta puntuación, preguntas abiertas y luego el kill-test. Expande capítulos solo cuando necesites profundidad.",
        },
        {
          type: "ol",
          items: [
            "Sello y puntuación: encaje con el objetivo y por qué esta puntuación (frenos y palancas).",
            "Brief: analgésico vs vitamina, fortalezas, preguntas abiertas.",
            "Mercado: tamaño, competidores, canales, defensibilidad.",
            "Dinero: unit economics y proyecciones (estimaciones, no promesas).",
            "Riesgos: matriz y pre-mortem antes de ignorar las celdas rojas.",
            "Plan: bloqueado hasta que un GO o un kill-test aprobado justifique un camino de construcción.",
            "Evidencia: el corpus detrás de la lectura de demanda (recibos, no decoración).",
          ],
        },
        {
          type: "callout",
          text: "En el estudio, los capítulos se quedan colapsados para que mande la decisión. Expande solo lo que necesites.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Cómo funciona la puntuación",
      summary:
        "Criterios, pesos y gates. Lectura opcional si un badge o ajuste te confunde.",
      eyebrow: "Por debajo del capó",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "criterios",
        "pesos",
        "bandas",
        "ajustes del sistema",
        "confianza",
      ],
      blocks: [
        {
          type: "p",
          text: "No necesitas esta página para usar Validorian. Ábrela cuando una nota de puntuación, un badge borderline o un clamp parezcan misteriosos.",
        },
        {
          type: "p",
          text: "En pocas palabras: el modelo escribe una justificación breve y una nota por letra en cada factor. El software convierte esas notas en números, las pondera según tu objetivo y aplica reglas duras para que un fallo fatal no se diluya promediando fortalezas en otras partes.",
        },
        { type: "h2", text: "Los diez criterios" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "En qué confiar" },
        {
          type: "ul",
          items: [
            "Evidencia obtenida (posts, reseñas) con enlaces reales y recuentos de votos",
            "Gates y clamps listados en las notas de puntuación cuando se activan",
            "Badges borderline cuando la puntuación está cerca de una línea GO o MAYBE (un re-run puede voltear)",
          ],
        },
        {
          type: "p",
          text: "Las cifras de tamaño de mercado y algunas notas de competidores son estimaciones del modelo a partir de búsquedas. Revisa las fuentes antes de apostar la empresa.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "¿Por qué cambió mi puntuación?",
      summary: "Re-runs, cambios de objetivo, nuevo encuadre y ruido normal de puntuación.",
      eyebrow: "Solución de problemas",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "varianza",
        "diferente",
        "voltear",
        "ruido",
        "re-ejecutar",
        "cambió",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Cambiaste el planteamiento de la idea, el objetivo o el contexto del founder: la puntuación debería cambiar.",
            "Puntuaciones borderline: el producto marca cuando estás dentro del ruido de ejecución a ejecución de un umbral. Un re-run puede caer al otro lado sin que el sistema esté roto.",
            "Nueva evidencia o un resultado de kill-test: los datos de campo pueden mover la demanda y el veredicto con honestidad.",
            "Validación profunda: un pase más pesado puede ajustar confianza y notas; trátalo como una segunda mirada, no como otro producto.",
          ],
        },
        {
          type: "callout",
          text: "Si el encuadre no cambió y el salto parece salvaje, escribe a help@validorian.com con el título de la idea y las versiones.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Itera sin desperdiciar ejecuciones",
      summary: "Ask, nuevas versiones, ángulos y cuándo re-puntuar.",
      eyebrow: "Bucle del estudio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "preguntar",
        "versión",
        "ángulo",
        "re-puntuar",
        "ejecución",
        "iterar",
      ],
      blocks: [
        {
          type: "p",
          text: "Una ejecución (o informe puntuado completo) es un análisis profundo que consume la asignación de la campaña. Usa Ask cuando solo quieras entender la revisión actual.",
        },
        { type: "h2", text: "¿Qué consume un informe?" },
        {
          type: "table",
          headers: ["Acción", "¿Usa un informe puntuado completo?"],
          rows: [
            ["Ask (chatear sobre este análisis)", "No"],
            ["Nueva versión + re-puntuación", "Sí"],
            ["Comparar ángulos / torneo de wedges", "Sí, por ángulo puntuado"],
            ["Validación profunda", "Sí"],
            ["Kit de kill-test, intel, leer el informe", "No"],
          ],
        },
        { type: "h2", text: "Ask (sin re-puntuación)" },
        {
          type: "p",
          text: "Habla del informe actual: puntuaciones, competidores, riesgos. No crea una versión y no usa un análisis completo.",
        },
        { type: "h2", text: "Nueva versión" },
        {
          type: "p",
          text: "Cambia el planteamiento, el objetivo o el contexto y luego re-puntúa. Úsalo tras un cambio real del encuadre o la evidencia, no tras cada curiosidad.",
        },
        { type: "h2", text: "Comparar ángulos" },
        {
          type: "p",
          text: "Un ángulo (a veces llamado alpha o wedge) es un borde o posicionamiento distinto de la misma idea central. Los torneos puntúan varios de esos bordes cara a cara sobre la misma evidencia. Cada entrante puntuado usa un slot de informe, así que elige con criterio.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-tests y entrevistas",
      summary: "La prueba real más barata antes de construir.",
      eyebrow: "Trabajo de campo",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "entrevista",
        "comprador",
        "pase",
        "fallo",
        "campo",
        "kill-test",
      ],
      blocks: [
        {
          type: "p",
          text: 'Un MAYBE o NO-GO a menudo no es "inténtalo más duro en la deck." Es "habla con compradores con un umbral de pase/fallo pre-registrado."',
        },
        {
          type: "ul",
          items: [
            "Supuesto más arriesgado: lo que el corpus no resolvió",
            "Prueba más barata (alrededor de una semana o menos) con un canal",
            "Umbrales de pase y kill escritos antes de ver resultados",
            "Kit de entrevistas: con quién hablar y preguntas al estilo Mom-Test (comportamiento pasado y hechos, no cumplidos sobre tu idea)",
          ],
        },
        {
          type: "p",
          text: "Registra el resultado y re-puntúa para que el veredicto se actualice con datos de campo, no con esperanza.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Validación profunda",
      summary: "Cuándo el pase más pesado vale un slot de informe.",
      eyebrow: "Avanzado",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "profunda",
        "costoso",
        "validación",
      ],
      blocks: [
        {
          type: "p",
          text: "La validación profunda es un análisis opcional más pesado (casos independientes, comprobaciones extra). Usa un informe puntuado completo y cuesta más cómputo que un pase estándar.",
        },
        {
          type: "ul",
          items: [
            "Úsala cuando la idea es seria y quieres una segunda mirada más dura",
            "Sáltala en borradores tempranos y experimentos baratos",
            "No sustituye un kill-test con compradores reales",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Idioma y salida de la IA",
      summary: "Idioma de la UI vs idioma de la prosa del informe.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "idioma",
        "coreano",
        "traducir",
        "globo",
        "localización",
      ],
      blocks: [
        {
          type: "p",
          text: "El selector del globo define el chrome de la UI: nav, botones, títulos de sección, sellos de veredicto y etiquetas. Puedes buscar idiomas por nombre o código (por ejemplo Korean, 한국어 o ko).",
        },
        {
          type: "p",
          text: "El texto de cuerpo escrito por la IA (resúmenes, notas de competidores, preguntas abiertas) sigue el idioma activo cuando generas o re-puntúas. Los informes antiguos en inglés siguen en inglés hasta que vuelvas a ejecutar bajo el nuevo locale.",
        },
        {
          type: "ul",
          items: [
            "Cambia de idioma en cualquier momento desde el header",
            "Los códigos máquina en datos guardados (veredictos, nombres de criterios) se quedan en inglés para consistencia de puntuación",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privacidad y tus ideas",
      summary: "Quién ve lo que pones en el estudio.",
      eyebrow: "Confianza",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privado",
        "datos",
        "seguridad",
        "compartir",
        "secreto",
        "privacidad",
      ],
      blocks: [
        {
          type: "p",
          text: "Las ideas e informes de tu cuenta son privados por defecto. No se publican en un feed público.",
        },
        {
          type: "ul",
          items: [
            "Tú controlas la cuenta que posee cada idea",
            "Las API keys, si las creas, solo acceden a ideas de esa key o modelo de cuenta",
            "Usamos proveedores de modelos para puntuar y redactar informes: no pegues secretos que no puedas permitirte enviar a sistemas de procesamiento",
            "Las herramientas de borrar cuenta eliminan tus datos según el flujo de cuenta del producto",
          ],
        },
        {
          type: "callout",
          text: "Preguntas sobre el manejo de datos: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Pide ayuda al equipo",
      summary: "Cómo contactarnos y qué incluir.",
      eyebrow: "Humanos",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "correo",
        "soporte",
        "contacto",
        "error",
        "humano",
        "ayuda",
      ],
      blocks: [
        {
          type: "p",
          text: "Para problemas de producto, facturación o una campaña atascada, escribe a help@validorian.com. Support y Contact van al mismo buzón por ahora.",
        },
        {
          type: "ul",
          items: [
            "Incluye el email de tu cuenta y el título de la idea si aplica",
            "Las capturas de pantalla ayudan con bugs de UI",
            "Nunca envíes contraseñas",
          ],
        },
      ],
    },
  ],
};
