import type { HelpCatalog } from "../types";

export const helpFr: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Premiers pas",
      blurb: "De la première idée à un passage de validation complet.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Facturation et campagnes",
      blurb: "Ce que vous payez, ce qui consomme un rapport, et quoi faire quand vous n’en avez plus.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Scores et verdicts",
      blurb: "Ce que signifie le tampon et comment lire le rapport.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Travailler dans le studio",
      blurb: "Poser des questions, rescorer, angles et kill-tests sans gaspiller de runs.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Compte et langue",
      blurb: "Locale, confidentialité et contacter l’équipe.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Le chat consomme-t-il un rapport complet ?", slug: "iterate" },
    { q: "Qu’est-ce que ma campagne a débloqué ?", slug: "campaigns-and-pricing" },
    { q: "Que signifient GO / MAYBE / NO-GO ?", slug: "verdicts" },
    { q: "Je ne peux plus lancer d’analyse", slug: "cant-run-analysis" },
    { q: "Pourquoi mon score a changé après un re-run ?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Validez votre première idée",
      summary:
        "Créez un compte, décrivez l’idée, débloquez une campagne et obtenez un score fondé sur des preuves.",
      eyebrow: "Commencez ici",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "premier",
        "inscription",
        "début",
        "débloquer",
        "démarrage",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian est un studio de validation d’idées business. Vous décrivez une idée par rapport à votre objectif, puis vous obtenez un GO / MAYBE / NO-GO étayé par des preuves, avec marché, argent, risques et un prochain test. Pas un discours de motivation.",
        },
        { type: "h2", text: "Le parcours" },
        {
          type: "ol",
          items: [
            "Créez un compte gratuit et ouvrez le studio.",
            "Décrivez ce que vous proposez, pour qui, et pourquoi maintenant. Définissez votre objectif (side hustle, lifestyle, venture, ou incertain) pour que le seuil de GO corresponde à votre situation.",
            "Quand vous êtes prêt à scorer, débloquez une campagne complète sur cette idée (un prix par idée ; voir Tarifs pour le montant actuel).",
            "Lisez d’abord le tampon et la surface de décision, puis explorez marché, argent et preuves selon vos besoins.",
            "Itérez : reformulez le pitch, essayez un autre angle, posez des questions sur la revue, ou lancez un kill-test en conditions réelles.",
          ],
        },
        {
          type: "callout",
          text: "Discuter avec la revue ne consomme jamais un rapport scoré. Les re-scores complets et analyses approfondies utilisent l’allocation de campagne.",
        },
        { type: "h2", text: "Ce que vous obtenez en un passage complet" },
        {
          type: "ul",
          items: [
            "Verdict et score (GO / MAYBE / NO-GO) avec confiance et bandes relatives à l’objectif",
            "Demande, disposition à payer, concurrence et revenu accessible",
            "Carte des risques et pre-mortem",
            "Profil acheteur et canaux",
            "Plan de test en conditions réelles (kill-test) avec barres de pass/fail",
            "Preuves issues de sources publiques (posts, avis, issues) avec liens",
            "Espace pour itérer : nouvelles versions, angles, et questions illimitées sur la revue de cette idée",
          ],
        },
        {
          type: "p",
          text: "Un passage complet peut prendre quelques minutes — vraie recherche web et scoring, pas une estimation instantanée.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campagnes et tarifs",
      summary: "Un prix par idée ; ce qui se débloque et ce qui compte comme rapport complet.",
      eyebrow: "Facturation",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "payer",
        "prix",
        "débloquer",
        "abonnement",
        "coût",
        "argent",
      ],
      blocks: [
        {
          type: "p",
          text: "Le compte est gratuit. Un pass campagne débloque un parcours de validation complet sur une idée : rapports scorés (jusqu’au plafond inclus, 10 analyses complètes par défaut), wedges, kit kill-test, intel concurrentiel, et chat illimité sur cette idée. Pas d’abonnement.",
        },
        { type: "h2", text: "Ce qui consomme un créneau de rapport" },
        {
          type: "table",
          headers: ["Action", "Utilise un rapport scoré complet ?"],
          rows: [
            ["Demander / chatter sur la revue", "Non"],
            ["Lire ou développer le rapport", "Non"],
            ["Nouvelle version + re-score", "Oui"],
            ["Validation approfondie", "Oui (run plus lourd)"],
            ["Tournoi d’angles / wedges (chaque entrant scoré)", "Oui, par analyse"],
            ["Kit d’interview ou pack intel", "Non (nécessite le déblocage, pas un créneau de rapport)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Seules les analyses scorées complètes consomment un créneau de rapport",
            "Quand les rapports inclus sont épuisés, le chat et les rapports existants restent ouverts",
            "Une autre idée nécessite son propre pass campagne",
          ],
        },
        {
          type: "callout",
          text: "Voir Tarifs pour le prix en vigueur et la FAQ. Problèmes de facturation : help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Je ne peux plus lancer d’analyse",
      summary:
        "Campagne verrouillée, rapports épuisés, ou bouton désactivé pour une autre raison.",
      eyebrow: "Dépannage",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "épuisé",
        "verrouillé",
        "bloqué",
        "désactivé",
        "plafond",
      ],
      blocks: [
        {
          type: "p",
          text: "Si Valider, re-scorer ou la validation approfondie est bloqué, vérifiez ces points dans l’ordre.",
        },
        {
          type: "ol",
          items: [
            "Campagne verrouillée : cette idée n’a jamais été débloquée. Ouvrez le déblocage / Tarifs pour cette idée.",
            "Rapports épuisés : vous avez utilisé toutes les analyses scorées incluses dans le pass. Le chat et la lecture restent ouverts. Lancez une nouvelle idée pour en valider une autre.",
            "Travail encore en cours : attendez la fin de l’analyse en cours.",
            "Pas de changement matériel : si vous voulez seulement comprendre le rapport actuel, utilisez Demander (sans rescore) plutôt que de consommer un autre run.",
          ],
        },
        {
          type: "callout",
          text: "Toujours bloqué ? Écrivez à help@validorian.com avec l’e-mail de votre compte et le titre de l’idée.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE et NO-GO",
      summary: "Ce que signifie chaque tampon et que faire ensuite.",
      eyebrow: "Verdicts",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "tampon",
        "insuffisant",
        "verdict",
      ],
      blocks: [
        {
          type: "p",
          text: "Le tampon est la décision. Le chiffre la soutient, mais le tampon répond à la question : faut-il avancer selon l’objectif que vous avez fixé.",
        },
        {
          type: "ul",
          items: [
            "GO : les preuves soutiennent de poursuivre ce cadrage pour votre objectif. Construisez et testez avec intention. Ouvrez le plan quand vous êtes prêt.",
            "MAYBE : mitigé ou limite. Améliorez l’idée, prouvez un kill-test, ou changez d’angle avant de vous engager à fond.",
            "NO-GO : tel qu’écrit, faible pour votre objectif. Pivotez franchement ou arrêtez. Ne polissez pas un décalage fatal.",
            "INSUFFICIENT : la confiance est trop faible pour noter honnêtement. Clarifiez l’énoncé, ajoutez du contexte, ou relancez après de meilleures preuves.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle et levée venture ne sont pas notés de la même façon. Un score qui passe en GO pour un objectif peut rester en MAYBE pour un autre.",
        },
        {
          type: "p",
          text: "Les libellés de l’interface peuvent s’afficher dans votre langue (par exemple des tampons en coréen). Le scoring utilise toujours les mêmes règles GO / MAYBE / NO-GO en dessous.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Lire votre rapport",
      summary:
        "Comment parcourir la surface de décision, le brief, le marché, l’argent, les risques, le plan et les preuves.",
      eyebrow: "Le rapport",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "interface",
        "marché",
        "argent",
        "risques",
        "preuves",
      ],
      blocks: [
        {
          type: "p",
          text: "Si vous ne parcourez qu’une fois : tampon, pourquoi ce score, questions ouvertes, puis le kill-test. Développez les chapitres seulement quand vous avez besoin de profondeur.",
        },
        {
          type: "ol",
          items: [
            "Tampon et score : adéquation à l’objectif et pourquoi ce score (freins et leviers).",
            "Brief : antidouleur vs vitamine, forces, questions ouvertes.",
            "Marché : sizing, concurrents, canaux, défensabilité.",
            "Argent : unit economics et projections (estimations, pas des promesses).",
            "Risques : matrice et pre-mortem avant d’ignorer les cellules rouges.",
            "Plan : verrouillé jusqu’à un GO ou un kill-test réussi qui justifie un chemin de construction.",
            "Preuves : le corpus derrière la lecture de la demande (des reçus, pas de la décoration).",
          ],
        },
        {
          type: "callout",
          text: "Dans le studio, les chapitres restent repliés pour que la décision mène. Développez seulement ce dont vous avez besoin.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Comment fonctionne le scoring",
      summary:
        "Critères, poids et gates. Lecture optionnelle si un badge ou un ajustement vous déroute.",
      eyebrow: "Sous le capot",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "critères",
        "poids",
        "bandes",
        "ajustements",
        "confiance",
      ],
      blocks: [
        {
          type: "p",
          text: "Vous n’avez pas besoin de cette page pour utiliser Validorian. Ouvrez-la quand une note de scoring, un badge limite ou un clamp semble mystérieux.",
        },
        {
          type: "p",
          text: "En clair : le modèle rédige une courte justification et une note lettre par facteur. Le logiciel convertit ces notes en chiffres, les pondère selon votre objectif, et applique des règles dures pour qu’un défaut fatal ne soit pas dilué par des forces ailleurs.",
        },
        { type: "h2", text: "Les dix critères" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Ce à quoi vous pouvez vous fier" },
        {
          type: "ul",
          items: [
            "Preuves récupérées (posts, avis) avec de vrais liens et des comptes de votes",
            "Gates et clamps listés sous les notes de scoring lorsqu’ils se déclenchent",
            "Badges limite lorsque le score est proche d’une ligne GO ou MAYBE (un re-run peut basculer)",
          ],
        },
        {
          type: "p",
          text: "Les chiffres de sizing marché et certaines notes concurrentielles sont des estimations du modèle à partir de la recherche. Vérifiez les sources avant de parier l’entreprise.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Pourquoi mon score a changé ?",
      summary: "Re-runs, changements d’objectif, nouveau cadrage, et bruit normal de scoring.",
      eyebrow: "Dépannage",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "variance",
        "différent",
        "bascule",
        "limite",
        "bruit",
        "relancer",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Vous avez modifié l’énoncé de l’idée, l’objectif ou le contexte fondateur : le score doit changer.",
            "Scores limites : le produit signale quand vous êtes dans le bruit d’un run à l’autre par rapport à un seuil. Un re-run peut basculer de l’autre côté sans que le système soit cassé.",
            "Nouvelles preuves ou résultat de kill-test : les données terrain peuvent déplacer honnêtement la demande et le verdict.",
            "Validation approfondie : un passage plus lourd peut ajuster la confiance et les notes ; traitez-le comme un second regard, pas comme un produit différent.",
          ],
        },
        {
          type: "callout",
          text: "Si le cadrage est inchangé et le saut semble extravagant, écrivez à help@validorian.com avec le titre de l’idée et les versions.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Itérer sans gaspiller de runs",
      summary: "Demander, nouvelles versions, angles, et quand re-scorer.",
      eyebrow: "Boucle studio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "demander",
        "discuter",
        "relancer",
        "itérer",
      ],
      blocks: [
        {
          type: "p",
          text: "Un run (ou rapport scoré complet) est une analyse profonde qui consomme l’allocation de campagne. Utilisez Demander quand vous voulez seulement comprendre la revue actuelle.",
        },
        { type: "h2", text: "Qu’est-ce qui consomme un rapport ?" },
        {
          type: "table",
          headers: ["Action", "Utilise un rapport scoré complet ?"],
          rows: [
            ["Demander (chat sur cette analyse)", "Non"],
            ["Nouvelle version + re-score", "Oui"],
            ["Comparer des angles / tournoi de wedges", "Oui, par angle scoré"],
            ["Validation approfondie", "Oui"],
            ["Kit kill-test, intel, lecture du rapport", "Non"],
          ],
        },
        { type: "h2", text: "Demander (sans rescore)" },
        {
          type: "p",
          text: "Parcourez le rapport actuel : scores, concurrents, risques. Ne crée pas de version et n’utilise pas une analyse complète.",
        },
        { type: "h2", text: "Nouvelle version" },
        {
          type: "p",
          text: "Modifiez l’énoncé, l’objectif ou le contexte, puis re-scorez. À utiliser après un vrai changement de cadrage ou de preuves, pas après chaque curiosité.",
        },
        { type: "h2", text: "Comparer des angles" },
        {
          type: "p",
          text: "Un angle (parfois appelé alpha ou wedge) est un bord ou un positionnement différent de la même idée de fond. Les tournois scorent quelques-uns de ces bords face à face sur les mêmes preuves. Chaque entrant scoré utilise un créneau de rapport : choisissez délibérément.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-tests et interviews",
      summary: "La preuve terrain la moins chère avant de construire.",
      eyebrow: "Terrain",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "entretien",
        "acheteur",
        "terrain",
        "Mom-Test",
      ],
      blocks: [
        {
          type: "p",
          text: "Un MAYBE ou un NO-GO, ce n’est souvent pas « travailler plus le pitch deck ». C’est « parler aux acheteurs avec une barre pass/fail préenregistrée ».",
        },
        {
          type: "ul",
          items: [
            "Hypothèse la plus risquée : ce que le corpus n’a pas tranché",
            "Test le moins cher (environ une semaine ou moins) avec un canal",
            "Seuils de pass et de kill écrits avant de voir les résultats",
            "Kit d’interview : à qui parler et questions de style Mom-Test (comportement passé et faits, pas des compliments sur votre idée)",
          ],
        },
        {
          type: "p",
          text: "Enregistrez le résultat et re-scorez pour que le verdict se mette à jour à partir des données terrain, pas de l’espoir.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Validation approfondie",
      summary: "Quand le passage plus lourd vaut un créneau de rapport.",
      eyebrow: "Avancé",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "approfondi",
        "lourd",
        "coûteux",
      ],
      blocks: [
        {
          type: "p",
          text: "La validation approfondie est une analyse optionnelle plus lourde (cas indépendants, contrôles supplémentaires). Elle utilise un rapport scoré complet et coûte plus de compute qu’un passage standard.",
        },
        {
          type: "ul",
          items: [
            "Utilisez-la quand l’idée est sérieuse et que vous voulez un second regard plus exigeant",
            "Passez-la pour les brouillons précoces et les expériences peu chères",
            "Elle ne remplace pas un kill-test avec de vrais acheteurs",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Langue et sortie IA",
      summary: "Langue de l’interface vs langue de la prose du rapport.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "langue",
        "traduire",
        "coréen",
        "interface",
      ],
      blocks: [
        {
          type: "p",
          text: "Le sélecteur globe définit le chrome de l’interface : navigation, boutons, titres de sections, tampons de verdict et libellés. Vous pouvez chercher des langues par nom ou code (par exemple Korean, 한국어, ou ko).",
        },
        {
          type: "p",
          text: "Le corps de texte rédigé par l’IA (résumés, notes concurrentielles, questions ouvertes) suit la langue active au moment où vous générez ou re-scorez. Les anciens rapports en anglais restent en anglais jusqu’à un re-run sous la nouvelle locale.",
        },
        {
          type: "ul",
          items: [
            "Changez de langue à tout moment depuis l’en-tête",
            "Les codes machine dans les données stockées (verdicts, noms de critères) restent en anglais pour la cohérence du scoring",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Confidentialité et vos idées",
      summary: "Qui voit ce que vous mettez dans le studio.",
      eyebrow: "Confiance",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privé",
        "données",
        "sécurité",
        "partager",
        "secret",
      ],
      blocks: [
        {
          type: "p",
          text: "Les idées et rapports de votre compte sont privés par défaut. Ils ne sont pas publiés sur un fil public.",
        },
        {
          type: "ul",
          items: [
            "Vous contrôlez le compte qui possède chaque idée",
            "Les clés API, si vous en créez, n’accèdent qu’aux idées de ce modèle de clé ou de compte",
            "Nous utilisons des fournisseurs de modèles pour scorer et rédiger les rapports : ne collez pas de secrets que vous ne pouvez pas vous permettre d’envoyer aux systèmes de traitement",
            "Les outils de suppression de compte retirent vos données selon le flux compte du produit",
          ],
        },
        {
          type: "callout",
          text: "Questions sur le traitement des données : help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Obtenir de l’aide de l’équipe",
      summary: "Comment nous joindre et quoi inclure.",
      eyebrow: "Humains",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "e-mail",
        "assistance",
        "humain",
      ],
      blocks: [
        {
          type: "p",
          text: "Pour des problèmes produit, de facturation, ou une campagne bloquée, écrivez à help@validorian.com. Support et Contact vont pour l’instant à la même boîte.",
        },
        {
          type: "ul",
          items: [
            "Incluez l’e-mail de votre compte et le titre de l’idée si c’est pertinent",
            "Les captures d’écran aident pour les bugs d’interface",
            "N’envoyez jamais de mots de passe",
          ],
        },
      ],
    },
  ],
};
