import type { HelpCatalog } from "../types";

export const helpHi: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "शुरुआत करें",
      blurb: "पहले idea से लेकर पूरे validation pass तक।",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Billing और campaigns",
      blurb: "आप किसके लिए भुगतान करते हैं, कब report खर्च होता है, और quota खत्म होने पर क्या करें।",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Scores और verdicts",
      blurb: "Stamp का मतलब क्या है और report कैसे पढ़ें।",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Studio में काम करना",
      blurb: "पूछें, re-score करें, angles और kill-tests — बिना runs बर्बाद किए।",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Account और भाषा",
      blurb: "Locale, privacy, और टीम से संपर्क।",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "क्या chat पूरा report खर्च करता है?", slug: "iterate" },
    { q: "मेरे campaign ने क्या unlock किया?", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO का मतलब क्या है?", slug: "verdicts" },
    { q: "मैं और analysis नहीं चला पा रहा/रही", slug: "cant-run-analysis" },
    { q: "Re-run के बाद score क्यों बदला?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "अपना पहला idea validate करें",
      summary:
        "Account बनाएँ, idea लिखें, campaign unlock करें, और grounded score पाएँ।",
      eyebrow: "यहीं से शुरू करें",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "पहला",
        "शुरुआत",
        "खाता",
        "अनलॉक",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian एक business validation studio है। आप अपने goal के हिसाब से idea बताते हैं, फिर evidence-backed GO / MAYBE / NO-GO मिलता है — market, money, risks, और अगला test के साथ। यह pep talk नहीं है।",
        },
        { type: "h2", text: "रास्ता" },
        {
          type: "ol",
          items: [
            "मुफ़्त account बनाएँ और studio खोलें।",
            "क्या दे रहे हैं, किसके लिए, और क्यों अभी — यह लिखें। अपना goal सेट करें (side hustle, lifestyle, venture, या unsure) ताकि GO का bar आपके हिसाब से हो।",
            "Score के लिए तैयार हों तो उस idea पर full campaign unlock करें (एक idea पर एक price; मौजूदा राशि Pricing पर देखें)।",
            "पहले stamp और decision surface पढ़ें, फिर ज़रूरत पड़ने पर market, money, और evidence में जाएँ।",
            "Iterate करें: pitch दोबारा लिखें, दूसरा angle आज़माएँ, review पर सवाल पूछें, या real-world kill-test चलाएँ।",
          ],
        },
        {
          type: "callout",
          text: "Review के साथ chat कभी scored report नहीं खर्च करता। Full re-scores और deep analyses campaign allotment इस्तेमाल करते हैं।",
        },
        { type: "h2", text: "Full pass में क्या मिलता है" },
        {
          type: "ul",
          items: [
            "Verdict और score (GO / MAYBE / NO-GO) — confidence और goal-relative bands के साथ",
            "Demand, willingness to pay, competition, और obtainable revenue",
            "Risk map और pre-mortem",
            "Buyer profile और channels",
            "Real-world test plan (kill-test) pass/fail bars के साथ",
            "Public sources से evidence (posts, reviews, issues) links सहित",
            "Iterate की जगह: नए versions, angles, और उस idea की review पर unlimited सवाल",
          ],
        },
        {
          type: "p",
          text: "Full pass में कुछ मिनट लग सकते हैं — असली web search और scoring, कोई instant guess नहीं।",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campaigns और pricing",
      summary: "एक idea पर एक price; क्या unlock होता है और full report कब गिना जाता है।",
      eyebrow: "Billing",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "कीमत",
        "भुगतान",
        "अनलॉक",
        "सदस्यता",
      ],
      blocks: [
        {
          type: "p",
          text: "Account मुफ़्त है। Campaign pass एक idea पर पूरा validation path unlock करता है: scored reports (शामिल cap तक, default 10 full analyses), wedges, kill-test kit, competitor intel, और उस idea पर unlimited chat। कोई subscription नहीं।",
        },
        { type: "h2", text: "Report slot कब खर्च होता है" },
        {
          type: "table",
          headers: ["Action", "क्या full scored report इस्तेमाल होता है?"],
          rows: [
            ["Review के बारे में Ask / chat", "नहीं"],
            ["Report पढ़ना या expand करना", "नहीं"],
            ["New version + re-score", "हाँ"],
            ["Deep validation", "हाँ (भारी run)"],
            ["Angle / wedge tournament (हर scored entrant)", "हाँ, हर analysis पर"],
            ["Interview kit या intel pack", "नहीं (unlock चाहिए, report slot नहीं)"],
          ],
        },
        {
          type: "ul",
          items: [
            "सिर्फ full scored analyses report slot खर्च करते हैं",
            "शामिल reports खत्म होने पर भी chat और मौजूदा reports खुले रहते हैं",
            "अलग idea के लिए अलग campaign pass चाहिए",
          ],
        },
        {
          type: "callout",
          text: "लाइव price और FAQ के लिए Pricing देखें। Billing समस्याएँ: help@validorian.com।",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "मैं और analysis नहीं चला पा रहा/रही",
      summary:
        "Campaign locked, reports खत्म, या बटन किसी और वजह से disabled।",
      eyebrow: "Troubleshooting",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "बंद",
        "लॉक",
        "खत्म",
        "अटका",
      ],
      blocks: [
        {
          type: "p",
          text: "अगर Validate, re-score, या deep validation ब्लॉक है, तो इस क्रम में जाँचें।",
        },
        {
          type: "ol",
          items: [
            "Campaign locked: इस idea को कभी unlock नहीं किया। उस idea के लिए unlock / Pricing खोलें।",
            "Reports complete: pass में शामिल full scored analyses खत्म हो गए। Chat और पढ़ना खुला रहता है। कुछ और validate करने के लिए नया idea शुरू करें।",
            "Work still running: मौजूदा analysis खत्म होने का इंतज़ार करें।",
            "कोई material change नहीं: अगर सिर्फ मौजूदा report समझना है, तो दूसरा run खर्च करने के बजाय Ask (no rescore) इस्तेमाल करें।",
          ],
        },
        {
          type: "callout",
          text: "फिर भी अटके? help@validorian.com पर अपना account email और idea title भेजें।",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE, और NO-GO",
      summary: "हर stamp का मतलब और आगे क्या करें।",
      eyebrow: "Verdicts",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "स्टैंप",
        "निर्णय",
        "फैसला",
      ],
      blocks: [
        {
          type: "p",
          text: "Stamp ही call है। नंबर उसे support करता है, लेकिन stamp बताता है कि आपके सेट goal के तहत आगे बढ़ें या नहीं।",
        },
        {
          type: "ul",
          items: [
            "GO: evidence आपके goal के लिए इस framing को pursue करने का समर्थन करता है। इरादे से build और test करें। तैयार हों तो plan खोलें।",
            "MAYBE: मिश्रित या borderline। All-in जाने से पहले idea सुधारें, kill-test साबित करें, या angle बदलें।",
            "NO-GO: जैसे लिखा है, आपके goal के लिए कमज़ोर। सख्त pivot करें या रुकें। Fatal mismatch को polish न करें।",
            "INSUFFICIENT: ईमानदारी से grade करने के लिए confidence बहुत कम है। Statement साफ़ करें, context जोड़ें, या बेहतर evidence के बाद re-run करें।",
          ],
        },
        {
          type: "callout",
          text: "Side hustle और venture raise एक जैसे grade नहीं होते। जो score एक goal के लिए GO clear करे, दूसरे के लिए MAYBE में बैठ सकता है।",
        },
        {
          type: "p",
          text: "UI labels आपकी भाषा में दिख सकते हैं (उदाहरण: Korean stamps)। Scoring नीचे उन्हीं GO / MAYBE / NO-GO नियमों पर चलता है।",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "अपनी report पढ़ें",
      summary:
        "Decision surface, brief, market, money, risks, plan, और evidence कैसे स्कैन करें।",
      eyebrow: "The report",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "रिपोर्ट",
        "बाजार",
        "जोखिम",
        "योजना",
      ],
      blocks: [
        {
          type: "p",
          text: "अगर एक बार ही skim करें: stamp, score क्यों, open questions, फिर kill-test। Chapters तभी expand करें जब depth चाहिए।",
        },
        {
          type: "ol",
          items: [
            "Stamp और score: goal fit और score क्यों (drags और levers)।",
            "Brief: painkiller बनाम vitamin, strengths, open questions।",
            "Market: sizing, competitors, channels, defensibility।",
            "Money: unit economics और projections (अनुमान, वादे नहीं)।",
            "Risks: matrix और pre-mortem — red cells नज़रअंदाज़ करने से पहले।",
            "Plan: GO या kill-test pass build path justify करे तब तक gated।",
            "Evidence: demand read के पीछे corpus (receipts, सजावट नहीं)।",
          ],
        },
        {
          type: "callout",
          text: "Studio में chapters collapsed रहते हैं ताकि decision आगे रहे। सिर्फ ज़रूरी चीज़ expand करें।",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Scoring कैसे काम करता है",
      summary:
        "Criteria, weights, और gates। Badge या adjustment उलझाए तो वैकल्पिक पढ़ाई।",
      eyebrow: "Under the hood",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "मानदंड",
        "वजन",
        "स्कोरिंग",
        "भरोसा",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian इस्तेमाल करने के लिए यह पेज ज़रूरी नहीं। Scoring note, borderline badge, या clamp रहस्यमय लगे तो खोलें।",
        },
        {
          type: "p",
          text: "सादे शब्दों में: model हर factor के लिए छोटा rationale और letter grade लिखता है। Software उन grades को numbers में बदलता है, आपके goal के हिसाब से weight देता है, और hard rules लगाता है ताकि एक fatal flaw बाकी strengths में average होकर गायब न हो जाए।",
        },
        { type: "h2", text: "दस criteria" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "किस पर भरोसा करें" },
        {
          type: "ul",
          items: [
            "Fetched evidence (posts, reviews) असली links और vote counts के साथ",
            "Gates और clamps — scoring notes में जब वे fire हों",
            "Borderline badges जब score GO या MAYBE line के पास हो (re-runs flip कर सकते हैं)",
          ],
        },
        {
          type: "p",
          text: "Market sizing के आंकड़े और कुछ competitor notes search से model estimates हैं। कंपनी पर दांव लगाने से पहले sources जाँचें।",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "मेरा score क्यों बदला?",
      summary: "Re-runs, goal बदलाव, नया framing, और सामान्य scoring noise।",
      eyebrow: "Troubleshooting",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "बदलाव",
        "अलग",
        "शोर",
        "फिर से",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "आपने idea statement, goal, या founder context बदला: score बदलना चाहिए।",
            "Borderline scores: product बताता है जब आप threshold के run-to-run noise के अंदर हों। Re-run दूसरी तरफ land कर सकता है — इसका मतलब सिस्टम टूटा नहीं।",
            "नया evidence या kill-test result: field data demand और verdict को ईमानदारी से हिला सकता है।",
            "Deep validation: भारी pass confidence और notes adjust कर सकता है; इसे second look समझें, अलग product नहीं।",
          ],
        },
        {
          type: "callout",
          text: "अगर framing वही है और jump बहुत अजीब लगे, help@validorian.com पर idea title और versions भेजें।",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Runs बर्बाद किए बिना iterate करें",
      summary: "Ask, नए versions, angles, और कब re-score करें।",
      eyebrow: "Studio loop",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "पूछें",
        "चैट",
        "संस्करण",
        "कोण",
      ],
      blocks: [
        {
          type: "p",
          text: "Run (या full scored report) गहरी analysis है जो campaign allotment खर्च करती है। जब सिर्फ मौजूदा review समझनी हो तो Ask इस्तेमाल करें।",
        },
        { type: "h2", text: "Report कब खर्च होता है?" },
        {
          type: "table",
          headers: ["Action", "क्या full scored report इस्तेमाल होता है?"],
          rows: [
            ["Ask (इस analysis के बारे में chat)", "नहीं"],
            ["New version + re-score", "हाँ"],
            ["Compare angles / wedge tournament", "हाँ, हर scored angle पर"],
            ["Deep validation", "हाँ"],
            ["Kill-test kit, intel, report पढ़ना", "नहीं"],
          ],
        },
        { type: "h2", text: "Ask (no rescore)" },
        {
          type: "p",
          text: "मौजूदा report पर बात करें: scores, competitors, risks। Version नहीं बनता और full analysis नहीं खर्च होता।",
        },
        { type: "h2", text: "New version" },
        {
          type: "p",
          text: "Statement, goal, या context बदलें, फिर re-score करें। Framing या evidence में असली बदलाव के बाद इस्तेमाल करें — हर curiosity पर नहीं।",
        },
        { type: "h2", text: "Compare angles" },
        {
          type: "p",
          text: "Angle (कभी alpha या wedge कहा जाता है) उसी core idea का अलग edge या positioning है। Tournaments उन्हीं edges में से कुछ को same evidence पर head-to-head score करते हैं। हर scored entrant report slot लेता है, इसलिए सोच-समझकर चुनें।",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-tests और interviews",
      summary: "Build से पहले सबसे सस्ता real-world proof।",
      eyebrow: "Field work",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "साक्षात्कार",
        "खरीदार",
        "फ़ील्ड",
        "पास",
        "फ़ेल",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE या NO-GO अक्सर "deck में और मेहनत" नहीं होता। यह "buyers से pre-registered pass/fail bar के साथ बात करें" होता है।',
        },
        {
          type: "ul",
          items: [
            "Riskiest assumption: corpus ने जो settle नहीं किया",
            "सबसे सस्ता test (लगभग एक हफ़्ते या कम) channel के साथ",
            "Pass और kill thresholds — results देखने से पहले लिखे हुए",
            "Interview kit: किससे बात करें और Mom-Test style सवाल (पिछला व्यवहार और facts, idea पर तारीफ़ नहीं)",
          ],
        },
        {
          type: "p",
          text: "Result रिकॉर्ड करें और re-score करें ताकि verdict hope से नहीं, field data से अपडेट हो।",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Deep validation",
      summary: "भारी pass कब report slot के लायक है।",
      eyebrow: "Advanced",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "गहरा",
        "महंगा",
        "उन्नत",
      ],
      blocks: [
        {
          type: "p",
          text: "Deep validation वैकल्पिक भारी analysis है (independent cases, extra checks)। यह full scored report इस्तेमाल करता है और standard pass से ज़्यादा compute लेता है।",
        },
        {
          type: "ul",
          items: [
            "जब idea गंभीर हो और दूसरी, सख्त नज़र चाहिए तो इस्तेमाल करें",
            "Early drafts और सस्ते experiments के लिए skip करें",
            "यह real buyers वाले kill-test की जगह नहीं लेता",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "भाषा और AI output",
      summary: "UI भाषा बनाम report prose भाषा।",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "भाषा",
        "अनुवाद",
        "हिंदी",
        "लोकेल",
      ],
      blocks: [
        {
          type: "p",
          text: "Globe switcher UI chrome सेट करता है: nav, buttons, section titles, verdict stamps, और labels। भाषा नाम या code से खोज सकते हैं (उदाहरण: Korean, 한국어, या ko)।",
        },
        {
          type: "p",
          text: "AI-written body text (summaries, competitor notes, open questions) उसी भाषा का अनुसरण करता है जो generate या re-score के समय सक्रिय थी। पुरानी English reports English रहती हैं जब तक नई locale में re-run न करें।",
        },
        {
          type: "ul",
          items: [
            "Header से कभी भी भाषा बदलें",
            "Stored data में machine codes (verdicts, criterion names) scoring consistency के लिए English रहते हैं",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privacy और आपके ideas",
      summary: "Studio में जो डालते हैं उसे कौन देखता है।",
      eyebrow: "Trust",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "गोपनीयता",
        "डेटा",
        "सुरक्षा",
        "निजी",
      ],
      blocks: [
        {
          type: "p",
          text: "आपके account में ideas और reports default में private हैं। वे public feed पर publish नहीं होते।",
        },
        {
          type: "ul",
          items: [
            "हर idea का मालिक account आप नियंत्रित करते हैं",
            "API keys, अगर बनाएँ, तो सिर्फ उस key या account model के ideas तक पहुँचती हैं",
            "हम score और reports लिखने के लिए model providers इस्तेमाल करते हैं: ऐसे secrets paste न करें जिन्हें processing systems तक भेजना महँगा पड़े",
            "Delete account tools product के account flow के अनुसार आपका data हटाते हैं",
          ],
        },
        {
          type: "callout",
          text: "Data handling के सवाल: help@validorian.com।",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "टीम से मदद लें",
      summary: "हमसे कैसे संपर्क करें और क्या शामिल करें।",
      eyebrow: "Humans",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "ईमेल",
        "सहायता",
        "संपर्क",
        "बग",
      ],
      blocks: [
        {
          type: "p",
          text: "Product issues, billing, या अटके campaign के लिए help@validorian.com पर email करें। Support और Contact फिलहाल एक ही inbox पर जाते हैं।",
        },
        {
          type: "ul",
          items: [
            "अपना account email और ज़रूरत हो तो idea title शामिल करें",
            "UI bugs के लिए screenshots मददगार हैं",
            "कभी passwords न भेजें",
          ],
        },
      ],
    },
  ],
};
