import type { HelpCatalog } from "../types";

export const helpId: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Mulai di sini",
      blurb: "Dari ide pertama sampai full validation pass.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Penagihan & kampanye",
      blurb: "Apa yang kamu bayar, apa yang menghabiskan laporan, dan apa yang dilakukan saat habis.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Skor & verdict",
      blurb: "Arti stempel dan cara membaca laporan.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Bekerja di studio",
      blurb: "Tanya, re-score, sudut, dan kill-test tanpa membuang run.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Akun & bahasa",
      blurb: "Locale, privasi, dan cara menghubungi tim.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Apakah chat memakai laporan penuh?", slug: "iterate" },
    { q: "Apa yang dibuka kampanye saya?", slug: "campaigns-and-pricing" },
    { q: "Apa arti GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Saya tidak bisa menjalankan analisis lagi", slug: "cant-run-analysis" },
    { q: "Kenapa skor saya berubah setelah re-run?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Validasi ide pertamamu",
      summary:
        "Buat akun, deskripsikan ide, buka kampanye, dan dapatkan skor berdasar bukti.",
      eyebrow: "Mulai di sini",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "pertama",
        "daftar",
        "mulai",
        "buka",
        "awal",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian adalah studio validasi bisnis. Kamu mendeskripsikan ide terhadap tujuanmu, lalu mendapat GO / MAYBE / NO-GO berdasar bukti—dengan pasar, uang, risiko, dan tes berikutnya. Bukan ceramah motivasi.",
        },
        { type: "h2", text: "Jalurnya" },
        {
          type: "ol",
          items: [
            "Buat akun gratis dan buka studio.",
            "Deskripsikan apa yang ditawarkan, untuk siapa, dan kenapa sekarang. Tetapkan tujuan (side hustle, lifestyle, venture, atau belum yakin) supaya bar GO cocok denganmu.",
            "Saat siap menilai, buka kampanye penuh pada ide itu (satu harga per ide; lihat Harga untuk jumlah saat ini).",
            "Baca stempel dan permukaan keputusan dulu, lalu gali pasar, uang, dan bukti sesuai kebutuhan.",
            "Iterasi: tulis ulang pitch, coba sudut lain, tanya tentang review, atau jalankan kill-test di dunia nyata.",
          ],
        },
        {
          type: "callout",
          text: "Chat dengan review tidak pernah menghabiskan laporan skor. Re-score penuh dan analisis mendalam memakai alokasi kampanye.",
        },
        { type: "h2", text: "Yang kamu dapat dalam full pass" },
        {
          type: "ul",
          items: [
            "Verdict dan skor (GO / MAYBE / NO-GO) dengan keyakinan dan pita relatif terhadap tujuan",
            "Permintaan, willingness to pay, kompetisi, dan pendapatan yang bisa dicapai",
            "Peta risiko dan pre-mortem",
            "Profil pembeli dan channel",
            "Rencana tes dunia nyata (kill-test) dengan bar lulus/gagal",
            "Bukti dari sumber publik (post, review, issue) dengan tautan",
            "Ruang untuk iterasi: versi baru, sudut, dan pertanyaan tak terbatas pada review ide itu",
          ],
        },
        {
          type: "p",
          text: "Full pass bisa memakan beberapa menit — pencarian web nyata dan penilaian, bukan tebakan instan.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Kampanye dan harga",
      summary: "Satu harga per ide; apa yang terbuka dan apa yang dihitung sebagai laporan penuh.",
      eyebrow: "Penagihan",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "bayar",
        "harga",
        "buka",
        "langganan",
        "biaya",
        "uang",
      ],
      blocks: [
        {
          type: "p",
          text: "Akun gratis. Pass kampanye membuka jalur validasi penuh pada satu ide: laporan skor (sampai batas termasuk, default 10 analisis penuh), wedge, kit kill-test, intel kompetitor, dan chat tak terbatas pada ide itu. Tanpa langganan.",
        },
        { type: "h2", text: "Apa yang menghabiskan slot laporan" },
        {
          type: "table",
          headers: ["Aksi", "Memakai laporan skor penuh?"],
          rows: [
            ["Tanya / chat tentang review", "Tidak"],
            ["Baca atau perluas laporan", "Tidak"],
            ["Versi baru + re-score", "Ya"],
            ["Validasi mendalam", "Ya (run lebih berat)"],
            ["Turnamen sudut / wedge (tiap entrant yang dinilai)", "Ya, per analisis"],
            ["Kit wawancara atau paket intel", "Tidak (butuh unlock, bukan slot laporan)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Hanya analisis skor penuh yang menghabiskan slot laporan",
            "Saat laporan termasuk habis, chat dan laporan yang ada tetap terbuka",
            "Ide berbeda butuh pass kampanye sendiri",
          ],
        },
        {
          type: "callout",
          text: "Lihat Harga untuk harga live dan FAQ. Masalah penagihan: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Saya tidak bisa menjalankan analisis lagi",
      summary:
        "Kampanye terkunci, laporan habis, atau tombol dinonaktifkan karena alasan lain.",
      eyebrow: "Pemecahan masalah",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "habis",
        "terkunci",
        "diblokir",
        "tidak bisa skor",
        "nonaktif",
        "batas",
      ],
      blocks: [
        {
          type: "p",
          text: "Jika Validasi, re-score, atau validasi mendalam diblokir, periksa ini berurutan.",
        },
        {
          type: "ol",
          items: [
            "Kampanye terkunci: ide ini belum pernah dibuka. Buka unlock / Harga untuk ide itu.",
            "Laporan selesai: kamu memakai semua analisis skor penuh yang termasuk di pass. Chat dan membaca tetap terbuka. Mulai ide baru untuk memvalidasi yang berbeda.",
            "Pekerjaan masih berjalan: tunggu analisis saat ini selesai.",
            "Tidak ada perubahan material: jika hanya ingin memahami laporan saat ini, pakai Tanya (tanpa rescore) alih-alih menghabiskan run lain.",
          ],
        },
        {
          type: "callout",
          text: "Masih buntu? Email help@validorian.com dengan email akun dan judul ide.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE, dan NO-GO",
      summary: "Arti tiap stempel dan apa yang dilakukan berikutnya.",
      eyebrow: "Verdict",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "stempel",
        "lulus",
        "gagal",
        "tidak cukup",
      ],
      blocks: [
        {
          type: "p",
          text: "Stempel adalah putusan. Angka mendukungnya, tapi stempel menjawab apakah maju di bawah tujuan yang kamu tetapkan.",
        },
        {
          type: "ul",
          items: [
            "GO: bukti mendukung mengejar framing ini untuk tujuanmu. Bangun dan uji dengan niat. Buka rencana saat siap.",
            "MAYBE: campur atau borderline. Perbaiki ide, buktikan kill-test, atau ubah sudut sebelum all-in.",
            "NO-GO: seperti tertulis, lemah untuk tujuanmu. Pivot keras atau berhenti. Jangan poles mismatch yang fatal.",
            "INSUFFICIENT: keyakinan terlalu rendah untuk menilai jujur. Perjelas pernyataan, tambah konteks, atau jalankan ulang setelah bukti lebih baik.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle dan venture raise tidak dinilai sama. Skor yang lolos GO untuk satu tujuan bisa duduk di MAYBE untuk tujuan lain.",
        },
        {
          type: "p",
          text: "Label UI bisa muncul dalam bahasamu (misalnya stempel Korea). Penilaian di bawahnya tetap memakai aturan GO / MAYBE / NO-GO yang sama.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Membaca laporanmu",
      summary:
        "Cara memindai permukaan keputusan, ringkas, pasar, uang, risiko, rencana, dan bukti.",
      eyebrow: "Laporan",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "bagian",
        "ringkas",
        "pasar",
        "uang",
        "risiko",
        "rencana",
        "bukti",
      ],
      blocks: [
        {
          type: "p",
          text: "Jika hanya skim sekali: stempel, kenapa skor ini, pertanyaan terbuka, lalu kill-test. Perluas bab hanya saat butuh kedalaman.",
        },
        {
          type: "ol",
          items: [
            "Stempel dan skor: kesesuaian tujuan dan kenapa skor ini (drag dan lever).",
            "Ringkas: painkiller vs vitamin, kekuatan, pertanyaan terbuka.",
            "Pasar: sizing, kompetitor, channel, defensibility.",
            "Uang: unit economics dan proyeksi (estimasi, bukan janji).",
            "Risiko: matriks dan pre-mortem sebelum kamu abaikan sel merah.",
            "Rencana: terkunci sampai GO atau lulus kill-test membenarkan jalur build.",
            "Bukti: korpus di balik bacaan permintaan (kwitansi, bukan dekorasi).",
          ],
        },
        {
          type: "callout",
          text: "Di studio, bab tetap tertutup supaya keputusan memimpin. Perluas hanya yang kamu butuhkan.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Cara kerja penilaian",
      summary:
        "Kriteria, bobot, dan gate. Bacaan opsional jika badge atau penyesuaian membingungkan.",
      eyebrow: "Di balik layar",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "kriteria",
        "bobot",
        "gerbang",
        "pita",
        "penyesuaian sistem",
        "kepercayaan",
      ],
      blocks: [
        {
          type: "p",
          text: "Kamu tidak perlu halaman ini untuk memakai Validorian. Buka saat catatan penilaian, badge borderline, atau clamp tampak misterius.",
        },
        {
          type: "p",
          text: "Sederhananya: model menulis rasional singkat dan nilai huruf per faktor. Software mengubah nilai itu menjadi angka, memberi bobot untuk tujuanmu, dan menerapkan aturan keras supaya satu cacat fatal tidak rata-rata hilang oleh kekuatan di tempat lain.",
        },
        { type: "h2", text: "Sepuluh kriteria" },
        {
          type: "ul",
          items: [
            "Kekuatan Permintaan, Kesediaan Membayar, Kesesuaian Masalah–Solusi",
            "Retensi & Kekambuhan, Timing Pasar, Posisi Kompetitif",
            "Diferensiasi / Moat, Kemudahan Akuisisi, Kesesuaian Founder, Kesesuaian Tujuan",
          ],
        },
        { type: "h2", text: "Yang harus dipercaya" },
        {
          type: "ul",
          items: [
            "Bukti yang diambil (post, review) dengan tautan nyata dan hitungan vote",
            "Gate dan clamp yang tercantum di catatan penilaian saat terpicu",
            "Badge borderline saat skor dekat garis GO atau MAYBE (re-run bisa membalik)",
          ],
        },
        {
          type: "p",
          text: "Angka ukuran pasar dan beberapa catatan kompetitor adalah estimasi model dari pencarian. Cek sumber sebelum bertaruh perusahaan.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Kenapa skor saya berubah?",
      summary: "Re-run, perubahan tujuan, framing baru, dan noise penilaian normal.",
      eyebrow: "Pemecahan masalah",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "variansi",
        "berbeda",
        "balik",
        "noise",
        "ulang",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Kamu mengubah pernyataan ide, tujuan, atau konteks founder: skor seharusnya berubah.",
            "Skor borderline: produk menandai saat kamu berada dalam noise run-to-run dari ambang. Re-run bisa mendarat di sisi lain tanpa berarti sistem rusak.",
            "Bukti baru atau hasil kill-test: data lapangan bisa menggeser permintaan dan verdict secara jujur.",
            "Validasi mendalam: pass lebih berat bisa menyesuaikan keyakinan dan catatan; anggap sebagai tinjauan kedua, bukan produk berbeda.",
          ],
        },
        {
          type: "callout",
          text: "Jika framing tidak berubah dan lompatannya tampak liar, email help@validorian.com dengan judul ide dan versinya.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Iterasi tanpa membuang run",
      summary: "Tanya, versi baru, sudut, dan kapan re-score.",
      eyebrow: "Loop studio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "tanya",
        "versi",
        "sudut",
        "ulang skor",
      ],
      blocks: [
        {
          type: "p",
          text: "Run (atau laporan skor penuh) adalah analisis mendalam yang menghabiskan alokasi kampanye. Pakai Tanya saat hanya ingin memahami review saat ini.",
        },
        { type: "h2", text: "Apa yang menghabiskan laporan?" },
        {
          type: "table",
          headers: ["Aksi", "Memakai laporan skor penuh?"],
          rows: [
            ["Tanya (chat tentang analisis ini)", "Tidak"],
            ["Versi baru + re-score", "Ya"],
            ["Bandingkan sudut / turnamen wedge", "Ya, per sudut yang dinilai"],
            ["Validasi mendalam", "Ya"],
            ["Kit kill-test, intel, membaca laporan", "Tidak"],
          ],
        },
        { type: "h2", text: "Tanya (tanpa rescore)" },
        {
          type: "p",
          text: "Bicarakan laporan saat ini: skor, kompetitor, risiko. Tidak membuat versi dan tidak memakai analisis penuh.",
        },
        { type: "h2", text: "Versi baru" },
        {
          type: "p",
          text: "Ubah pernyataan, tujuan, atau konteks, lalu re-score. Pakai setelah perubahan nyata pada framing atau bukti, bukan setelah setiap rasa penasaran.",
        },
        { type: "h2", text: "Bandingkan sudut" },
        {
          type: "p",
          text: "Sudut (kadang disebut alpha atau wedge) adalah edge atau positioning berbeda dari ide inti yang sama. Turnamen menilai beberapa edge itu head-to-head pada bukti yang sama. Tiap entrant yang dinilai memakai slot laporan, jadi pilih dengan sengaja.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-test dan wawancara",
      summary: "Bukti dunia nyata termurah sebelum kamu bangun.",
      eyebrow: "Kerja lapangan",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "wawancara",
        "pembeli",
        "lulus",
        "gagal",
        "lapangan",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE atau NO-GO sering bukan "coba lebih keras di deck." Melainkan "bicara ke pembeli dengan bar lulus/gagal yang sudah pra-terdaftar."',
        },
        {
          type: "ul",
          items: [
            "Asumsi paling berisiko: yang belum diselesaikan korpus",
            "Tes termurah (sekitar seminggu atau kurang) dengan channel",
            "Ambang lulus dan kill ditulis sebelum kamu melihat hasil",
            "Kit wawancara: siapa diajak bicara dan pertanyaan gaya Mom-Test (perilaku dan fakta masa lalu, bukan pujian tentang ide)",
          ],
        },
        {
          type: "p",
          text: "Catat hasilnya dan re-score supaya verdict diperbarui dari data lapangan, bukan harapan.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Validasi mendalam",
      summary: "Kapan pass lebih berat sepadan dengan slot laporan.",
      eyebrow: "Lanjutan",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "mendalam",
        "mahal",
      ],
      blocks: [
        {
          type: "p",
          text: "Validasi mendalam adalah analisis opsional yang lebih berat (kasus independen, cek ekstra). Memakai laporan skor penuh dan lebih mahal komputasinya daripada pass standar.",
        },
        {
          type: "ul",
          items: [
            "Pakai saat ide serius dan kamu ingin tinjauan kedua yang lebih keras",
            "Lewati untuk draf awal dan eksperimen murah",
            "Tidak menggantikan kill-test dengan pembeli nyata",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Bahasa dan output AI",
      summary: "Bahasa UI vs bahasa prosa laporan.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "bahasa",
        "terjemah",
        "korea",
      ],
      blocks: [
        {
          type: "p",
          text: "Switcher globe mengatur chrome UI: nav, tombol, judul bagian, stempel verdict, dan label. Kamu bisa mencari bahasa berdasarkan nama atau kode (misalnya Korean, 한국어, atau ko).",
        },
        {
          type: "p",
          text: "Teks body yang ditulis AI (ringkasan, catatan kompetitor, pertanyaan terbuka) mengikuti bahasa yang aktif saat kamu generate atau re-score. Laporan Inggris lama tetap Inggris sampai kamu jalankan ulang di locale baru.",
        },
        {
          type: "ul",
          items: [
            "Ganti bahasa kapan saja dari header",
            "Kode mesin di data tersimpan (verdict, nama kriteria) tetap English demi konsistensi penilaian",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privasi dan ide kamu",
      summary: "Siapa melihat apa yang kamu masukkan di studio.",
      eyebrow: "Kepercayaan",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privat",
        "keamanan",
        "rahasia",
        "bagikan",
      ],
      blocks: [
        {
          type: "p",
          text: "Ide dan laporan di akunmu privat secara default. Tidak dipublikasikan di feed publik.",
        },
        {
          type: "ul",
          items: [
            "Kamu mengontrol akun yang memiliki tiap ide",
            "Kunci API, jika dibuat, hanya mengakses ide untuk model kunci atau akun itu",
            "Kami memakai penyedia model untuk menilai dan menulis laporan: jangan tempel rahasia yang tidak bisa kamu kirim ke sistem pemrosesan",
            "Tool hapus akun menghapus datamu sesuai alur akun produk",
          ],
        },
        {
          type: "callout",
          text: "Pertanyaan tentang penanganan data: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Minta bantuan dari tim",
      summary: "Cara menghubungi kami dan apa yang perlu disertakan.",
      eyebrow: "Manusia",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "dukungan",
        "kontak",
        "manusia",
      ],
      blocks: [
        {
          type: "p",
          text: "Untuk masalah produk, penagihan, atau kampanye macet, email help@validorian.com. Dukungan dan Kontak sementara ke inbox yang sama.",
        },
        {
          type: "ul",
          items: [
            "Sertakan email akun dan judul ide jika relevan",
            "Screenshot membantu untuk bug UI",
            "Jangan kirim kata sandi",
          ],
        },
      ],
    },
  ],
};
