import type { HelpCatalog } from "../types";

export const helpIt: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Per iniziare",
      blurb: "Dalla prima idea a un passaggio completo di validazione.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Fatturazione e campagne",
      blurb: "Cosa paghi, cosa consuma un report e cosa fare quando finiscono.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Punteggi e verdetti",
      blurb: "Cosa significa il timbro e come leggere il report.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Lavorare nello studio",
      blurb: "Chiedi, rivaluta, angoli e kill-test senza sprecare esecuzioni.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Account e lingua",
      blurb: "Locale, privacy e come contattare il team.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "La chat consuma un report completo?", slug: "iterate" },
    { q: "Cosa ha sbloccato la mia campagna?", slug: "campaigns-and-pricing" },
    { q: "Cosa significa GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Non posso lanciare un'altra analisi", slug: "cant-run-analysis" },
    { q: "Perché è cambiato il punteggio dopo un re-run?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Valida la tua prima idea",
      summary:
        "Crea un account, descrivi l'idea, sblocca una campagna e ottieni un punteggio fondato.",
      eyebrow: "Inizia qui",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "prima",
        "registrazione",
        "iniziare",
        "sbloccare",
        "onboarding",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian è uno studio di validazione business. Descrivi un'idea rispetto al tuo obiettivo e ricevi un GO / MAYBE / NO-GO basato sull'evidenza, con mercato, soldi, rischi e un prossimo test. Non un discorso motivazionale.",
        },
        { type: "h2", text: "Il percorso" },
        {
          type: "ol",
          items: [
            "Crea un account gratis e apri lo studio.",
            "Descrivi cosa offri, a chi e perché adesso. Imposta il tuo obiettivo (side hustle, lifestyle, venture o non sicuro) così l'asticella del GO combacia con te.",
            "Quando sei pronto a valutare, sblocca una campagna completa su quell'idea (un prezzo per idea; vedi Prezzi per l'importo attuale).",
            "Leggi prima il timbro e la superficie decisionale, poi approfondisci mercato, soldi ed evidenza secondo necessità.",
            "Itera: riscrivi il pitch, prova un altro angolo, fai domande sul report o lancia un kill-test nel mondo reale.",
          ],
        },
        {
          type: "callout",
          text: "Chattare con il report non consuma mai un report valutato. Le rivalutazioni complete e le analisi profonde usano l'assegnazione della campagna.",
        },
        { type: "h2", text: "Cosa ottieni in un passaggio completo" },
        {
          type: "ul",
          items: [
            "Verdetto e punteggio (GO / MAYBE / NO-GO) con confidenza e bande relative all'obiettivo",
            "Domanda, propensione a pagare, concorrenza e ricavi ottenibili",
            "Mappa dei rischi e pre-mortem",
            "Profilo buyer e canali",
            "Piano di test nel mondo reale (kill-test) con soglie pass/fail",
            "Evidenza da fonti pubbliche (post, recensioni, issue) con link",
            "Spazio per iterare: nuove versioni, angoli e domande illimitate sul report di quell'idea",
          ],
        },
        {
          type: "p",
          text: "Un passaggio completo può richiedere qualche minuto — ricerca web reale e scoring, non un'indovinata istantanea.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campagne e prezzi",
      summary:
        "Un prezzo per idea; cosa si sblocca e cosa conta come report completo.",
      eyebrow: "Fatturazione",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "pagare",
        "prezzo",
        "sbloccare",
        "abbonamento",
        "costo",
        "soldi",
        "campagna",
      ],
      blocks: [
        {
          type: "p",
          text: "L'account è gratis. Un passaggio di campagna sblocca un percorso di validazione completo su un'idea: report valutati (fino al tetto incluso, di default 10 analisi complete), wedge, kit di kill-test, intel sui competitor e chat illimitata su quell'idea. Niente abbonamento.",
        },
        { type: "h2", text: "Cosa consuma uno slot di report" },
        {
          type: "table",
          headers: ["Azione", "Usa un report valutato completo?"],
          rows: [
            ["Chiedi / chatta sul report", "No"],
            ["Leggi o espandi il report", "No"],
            ["Nuova versione + re-score", "Sì"],
            ["Validazione profonda", "Sì (esecuzione più pesante)"],
            ["Torneo di angoli / wedge (ogni entrante valutato)", "Sì, per analisi"],
            [
              "Kit interviste o pacchetto intel",
              "No (serve lo sblocco, non uno slot di report)",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "Solo le analisi complete valutate consumano uno slot di report",
            "Quando i report inclusi sono finiti, chat e report esistenti restano aperti",
            "Un'idea diversa richiede il proprio passaggio di campagna",
          ],
        },
        {
          type: "callout",
          text: "Vedi Prezzi per il prezzo live e le FAQ. Problemi di fatturazione: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Non posso lanciare un'altra analisi",
      summary:
        "Campagna bloccata, report esauriti, o il pulsante disabilitato per un altro motivo.",
      eyebrow: "Risoluzione problemi",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "esaurito",
        "bloccato",
        "non posso valutare",
        "disabilitato",
        "limite",
      ],
      blocks: [
        {
          type: "p",
          text: "Se Valida, re-score o validazione profonda è bloccato, controlla questi punti in ordine.",
        },
        {
          type: "ol",
          items: [
            "Campagna bloccata: questa idea non è mai stata sbloccata. Apri sblocco / Prezzi per quell'idea.",
            "Report completati: hai usato le analisi complete incluse nel passaggio. Chat e lettura restano aperte. Avvia una nuova idea per validare qualcosa di diverso.",
            "Lavoro ancora in corso: aspetta che finisca l'analisi attuale.",
            "Nessun cambio materiale: se vuoi solo capire il report attuale, usa Chiedi (senza re-score) invece di consumare un'altra esecuzione.",
          ],
        },
        {
          type: "callout",
          text: "Ancora bloccato? Scrivi a help@validorian.com con l'email dell'account e il titolo dell'idea.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE e NO-GO",
      summary: "Cosa significa ogni timbro e cosa fare dopo.",
      eyebrow: "Verdetti",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "timbro",
        "verdetto",
        "approvato",
        "fallimento",
        "insufficiente",
      ],
      blocks: [
        {
          type: "p",
          text: "Il timbro è la decisione. Il numero la supporta, ma il timbro risponde se conviene proseguire sotto l'obiettivo che hai impostato.",
        },
        {
          type: "ul",
          items: [
            "GO: l'evidenza supporta perseguire questo framing per il tuo obiettivo. Costruisci e testa con intento. Apri il piano quando sei pronto.",
            "MAYBE: misto o al limite. Migliora l'idea, dimostra un kill-test o cambia angolo prima di andare all-in.",
            "NO-GO: così com'è scritto, debole per il tuo obiettivo. Pivota con forza o fermati. Non lucidare un mismatch fatale.",
            "INSUFFICIENT: la confidenza è troppo bassa per valutare onestamente. Chiarisci l'enunciato, aggiungi contesto o rilancia dopo evidenza migliore.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle e round venture non si valutano allo stesso modo. Un punteggio che supera GO per un obiettivo può restare in MAYBE per un altro.",
        },
        {
          type: "p",
          text: "Le etichette UI possono apparire nella tua lingua (ad esempio timbri in coreano). Lo scoring usa comunque le stesse regole GO / MAYBE / NO-GO sotto il cofano.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Come leggere il report",
      summary:
        "Come scansionare superficie decisionale, brief, mercato, soldi, rischi, piano ed evidenza.",
      eyebrow: "Il report",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "sezioni",
        "mercato",
        "soldi",
        "rischi",
        "piano",
        "evidenza",
        "report",
      ],
      blocks: [
        {
          type: "p",
          text: "Se dai un'occhiata una sola volta: timbro, perché questo punteggio, domande aperte, poi il kill-test. Espandi i capitoli solo quando serve profondità.",
        },
        {
          type: "ol",
          items: [
            "Timbro e punteggio: fit con l'obiettivo e perché questo punteggio (freni e leve).",
            "Brief: analgesico vs vitamina, punti di forza, domande aperte.",
            "Mercato: dimensionamento, competitor, canali, difendibilità.",
            "Soldi: unit economics e proiezioni (stime, non promesse).",
            "Rischi: matrice e pre-mortem prima di ignorare le celle rosse.",
            "Piano: bloccato finché un GO o un kill-test superato non giustifica un percorso di build.",
            "Evidenza: il corpus dietro la lettura della domanda (ricevute, non decorazione).",
          ],
        },
        {
          type: "callout",
          text: "Nello studio i capitoli restano compressi così manda la decisione. Espandi solo ciò che ti serve.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Come funziona lo scoring",
      summary:
        "Criteri, pesi e gate. Lettura opzionale se un badge o un aggiustamento ti confonde.",
      eyebrow: "Sotto il cofano",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "criteri",
        "pesi",
        "bande",
        "aggiustamenti di sistema",
        "fiducia",
      ],
      blocks: [
        {
          type: "p",
          text: "Non ti serve questa pagina per usare Validorian. Aprila quando una nota di scoring, un badge borderline o un clamp sembrano misteriosi.",
        },
        {
          type: "p",
          text: "In parole semplici: il modello scrive una breve rationale e un voto per lettera su ogni fattore. Il software trasforma quei voti in numeri, li pesa per il tuo obiettivo e applica regole dure così un difetto fatale non si annulla mediando i punti di forza altrove.",
        },
        { type: "h2", text: "I dieci criteri" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Di cosa fidarti" },
        {
          type: "ul",
          items: [
            "Evidenza recuperata (post, recensioni) con link reali e conteggi voti",
            "Gate e clamp elencati nelle note di scoring quando scattano",
            "Badge borderline quando il punteggio è vicino a una linea GO o MAYBE (un re-run può invertire)",
          ],
        },
        {
          type: "p",
          text: "Le cifre di dimensionamento di mercato e alcune note sui competitor sono stime del modello da ricerca. Controlla le fonti prima di scommettere l'azienda.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Perché è cambiato il mio punteggio?",
      summary:
        "Re-run, cambi di obiettivo, nuovo framing e rumore normale di scoring.",
      eyebrow: "Risoluzione problemi",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "varianza",
        "diverso",
        "invertire",
        "rumore",
        "ri-eseguire",
        "cambiato",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Hai cambiato l'enunciato dell'idea, l'obiettivo o il contesto founder: il punteggio deve cambiare.",
            "Punteggi borderline: il prodotto segnala quando sei entro il rumore da un'esecuzione all'altra rispetto a una soglia. Un re-run può cadere dall'altra parte senza che il sistema sia rotto.",
            "Nuova evidenza o un risultato di kill-test: i dati di campo possono spostare domanda e verdetto onestamente.",
            "Validazione profonda: un passaggio più pesante può aggiustare confidenza e note; trattalo come una seconda occhiata, non come un prodotto diverso.",
          ],
        },
        {
          type: "callout",
          text: "Se il framing non è cambiato e il salto sembra selvaggio, scrivi a help@validorian.com con il titolo dell'idea e le versioni.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Itera senza sprecare esecuzioni",
      summary: "Chiedi, nuove versioni, angoli e quando rivalutare.",
      eyebrow: "Loop dello studio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "chiedi",
        "versione",
        "angolo",
        "rivaluta",
        "esecuzione",
        "iterare",
      ],
      blocks: [
        {
          type: "p",
          text: "Un'esecuzione (o report valutato completo) è un'analisi profonda che consuma l'assegnazione della campagna. Usa Chiedi quando vuoi solo capire il report attuale.",
        },
        { type: "h2", text: "Cosa consuma un report?" },
        {
          type: "table",
          headers: ["Azione", "Usa un report valutato completo?"],
          rows: [
            ["Chiedi (chat su questa analisi)", "No"],
            ["Nuova versione + re-score", "Sì"],
            ["Confronta angoli / torneo wedge", "Sì, per angolo valutato"],
            ["Validazione profonda", "Sì"],
            ["Kit di kill-test, intel, lettura del report", "No"],
          ],
        },
        { type: "h2", text: "Chiedi (senza re-score)" },
        {
          type: "p",
          text: "Parla del report attuale: punteggi, competitor, rischi. Non crea una versione e non usa un'analisi completa.",
        },
        { type: "h2", text: "Nuova versione" },
        {
          type: "p",
          text: "Cambia enunciato, obiettivo o contesto, poi rivaluta. Usalo dopo un cambio reale di framing o evidenza, non dopo ogni curiosità.",
        },
        { type: "h2", text: "Confronta angoli" },
        {
          type: "p",
          text: "Un angolo (a volte chiamato alpha o wedge) è un edge o posizionamento diverso della stessa idea core. I tornei valutano alcuni di quegli edge testa a testa sulla stessa evidenza. Ogni entrante valutato usa uno slot di report, quindi scegli con criterio.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-test e interviste",
      summary: "La prova reale più economica prima di costruire.",
      eyebrow: "Lavoro di campo",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "intervista",
        "compratore",
        "buyer",
        "pass",
        "fallimento",
        "campo",
        "kill-test",
      ],
      blocks: [
        {
          type: "p",
          text: 'Un MAYBE o NO-GO spesso non è "impegnati di più sul deck." È "parla con i buyer con una soglia pass/fail pre-registrata."',
        },
        {
          type: "ul",
          items: [
            "Assunzione più rischiosa: ciò che il corpus non ha risolto",
            "Test più economico (circa una settimana o meno) con un canale",
            "Soglie di pass e kill scritte prima di vedere i risultati",
            "Kit interviste: con chi parlare e domande in stile Mom-Test (comportamento passato e fatti, non complimenti sulla tua idea)",
          ],
        },
        {
          type: "p",
          text: "Registra il risultato e rivaluta così il verdetto si aggiorna con dati di campo, non con la speranza.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Validazione profonda",
      summary: "Quando il passaggio più pesante vale uno slot di report.",
      eyebrow: "Avanzato",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "profonda",
        "costoso",
        "validazione",
      ],
      blocks: [
        {
          type: "p",
          text: "La validazione profonda è un'analisi opzionale più pesante (casi indipendenti, controlli extra). Usa un report valutato completo e costa più compute di un passaggio standard.",
        },
        {
          type: "ul",
          items: [
            "Usala quando l'idea è seria e vuoi una seconda occhiata più dura",
            "Saltala per bozze precoci ed esperimenti economici",
            "Non sostituisce un kill-test con buyer reali",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Lingua e output dell'AI",
      summary: "Lingua UI vs lingua della prosa del report.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "lingua",
        "coreano",
        "tradurre",
        "globo",
        "localizzazione",
      ],
      blocks: [
        {
          type: "p",
          text: "Il selettore del globo imposta il chrome UI: nav, pulsanti, titoli di sezione, timbri di verdetto ed etichette. Puoi cercare lingue per nome o codice (ad esempio Korean, 한국어 o ko).",
        },
        {
          type: "p",
          text: "Il testo body scritto dall'AI (sintesi, note sui competitor, domande aperte) segue la lingua attiva quando generi o rivaluti. I vecchi report in inglese restano in inglese finché non rilanci sotto il nuovo locale.",
        },
        {
          type: "ul",
          items: [
            "Cambia lingua in qualsiasi momento dall'header",
            "I codici macchina nei dati salvati (verdetti, nomi dei criteri) restano in inglese per coerenza di scoring",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privacy e le tue idee",
      summary: "Chi vede cosa metti nello studio.",
      eyebrow: "Fiducia",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privato",
        "dati",
        "sicurezza",
        "condividere",
        "segreto",
        "privacy",
      ],
      blocks: [
        {
          type: "p",
          text: "Le idee e i report del tuo account sono privati di default. Non vengono pubblicati su un feed pubblico.",
        },
        {
          type: "ul",
          items: [
            "Controlli tu l'account che possiede ogni idea",
            "Le API key, se le crei, accedono solo alle idee di quella key o modello di account",
            "Usiamo provider di modelli per valutare e scrivere i report: non incollare segreti che non puoi permetterti di inviare a sistemi di elaborazione",
            "Gli strumenti di eliminazione account rimuovono i tuoi dati secondo il flusso account del prodotto",
          ],
        },
        {
          type: "callout",
          text: "Domande sulla gestione dei dati: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Chiedi aiuto al team",
      summary: "Come contattarci e cosa includere.",
      eyebrow: "Umani",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "posta",
        "supporto",
        "contatto",
        "errore",
        "umano",
        "aiuto",
      ],
      blocks: [
        {
          type: "p",
          text: "Per problemi di prodotto, fatturazione o una campagna bloccata, scrivi a help@validorian.com. Supporto e Contatti vanno allo stesso inbox per ora.",
        },
        {
          type: "ul",
          items: [
            "Includi l'email dell'account e il titolo dell'idea se rilevante",
            "Gli screenshot aiutano per i bug UI",
            "Non inviare mai le password",
          ],
        },
      ],
    },
  ],
};
