import type { HelpCatalog } from "../types";

export const helpKo: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "시작하기",
      blurb: "첫 아이디어부터 전체 검증 패스까지.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "결제 & 캠페인",
      blurb: "무엇을 내고, 어떤 작업이 리포트를 소모하는지, 다 썼을 때 할 일.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "점수 & 판정",
      blurb: "스탬프의 의미와 리포트 읽는 법.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "스튜디오에서 작업하기",
      blurb: "질문, 재채점, 앵글, 킬테스트를 런 낭비 없이.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "계정 & 언어",
      blurb: "로케일, 개인정보, 팀에 연락하기.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "채팅이 전체 리포트를 쓰나요?", slug: "iterate" },
    { q: "캠페인으로 무엇이 열리나요?", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO는 무슨 뜻인가요?", slug: "verdicts" },
    { q: "분석을 더 실행할 수 없어요", slug: "cant-run-analysis" },
    { q: "재실행 후 점수가 왜 바뀌었나요?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "첫 아이디어 검증하기",
      summary:
        "계정을 만들고, 아이디어를 설명하고, 캠페인을 해제한 뒤 근거 있는 점수를 받으세요.",
      eyebrow: "여기서 시작",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "시작",
        "가입",
        "온보딩",
        "해제",
        "첫검증",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian은 비즈니스 검증 스튜디오입니다. 목표에 맞춰 아이디어를 설명하면, 시장·수익·리스크·다음 테스트까지 근거가 있는 GO / MAYBE / NO-GO를 받습니다. 응원 멘트가 아닙니다.",
        },
        { type: "h2", text: "진행 경로" },
        {
          type: "ol",
          items: [
            "무료 계정을 만들고 스튜디오를 엽니다.",
            "무엇을 제공하는지, 누구를 위한 것인지, 왜 지금인지 적습니다. 목표(사이드 허슬, 라이프스타일, 벤처, 또는 미정)를 설정하면 GO의 기준이 그에 맞춰집니다.",
            "채점할 준비가 되면 그 아이디어에 전체 캠페인을 해제합니다(아이디어당 한 번 가격; 현재 금액은 요금 페이지 참고).",
            "먼저 스탬프와 결정 표면을 읽고, 필요하면 시장·수익·근거를 더 파고듭니다.",
            "반복합니다: 피치를 다시 쓰고, 다른 앵글을 시도하고, 리뷰에 질문하거나, 실제 킬테스트를 실행합니다.",
          ],
        },
        {
          type: "callout",
          text: "리뷰와의 채팅은 채점된 리포트를 소모하지 않습니다. 전체 재채점과 딥 분석만 캠페인 할당량을 사용합니다.",
        },
        { type: "h2", text: "전체 패스에서 얻는 것" },
        {
          type: "ul",
          items: [
            "판정과 점수(GO / MAYBE / NO-GO), 신뢰도와 목표 대비 밴드",
            "수요, 지불 의향, 경쟁, 확보 가능한 매출",
            "리스크 맵과 프리모템",
            "구매자 프로필과 채널",
            "합격/실패 기준이 있는 실세계 테스트 계획(킬테스트)",
            "공개 출처(게시물, 리뷰, 이슈) 근거와 링크",
            "반복 공간: 새 버전, 앵글, 해당 아이디어 리뷰에 대한 무제한 질문",
          ],
        },
        {
          type: "p",
          text: "전체 패스는 몇 분이 걸릴 수 있습니다 — 실제 웹 검색과 채점이며, 즉석 추측이 아닙니다.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "캠페인과 요금",
      summary: "아이디어당 한 번 가격; 무엇이 열리고 전체 리포트로 무엇을 세는지.",
      eyebrow: "결제",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "요금",
        "결제",
        "캠페인",
        "해제",
        "구독",
        "가격",
      ],
      blocks: [
        {
          type: "p",
          text: "계정은 무료입니다. 캠페인 패스는 한 아이디어에 대한 전체 검증 경로를 엽니다: 채점 리포트(포함 상한까지, 기본 10회 전체 분석), 웨지, 킬테스트 키트, 경쟁사 인텔, 해당 아이디어에 대한 무제한 채팅. 구독 없습니다.",
        },
        { type: "h2", text: "리포트 슬롯을 소모하는 것" },
        {
          type: "table",
          headers: ["작업", "전체 채점 리포트를 사용하나요?"],
          rows: [
            ["리뷰에 대해 질문 / 채팅", "아니요"],
            ["리포트 읽기 또는 펼치기", "아니요"],
            ["새 버전 + 재채점", "예"],
            ["딥 검증", "예 (더 무거운 실행)"],
            ["앵글 / 웨지 토너먼트(채점된 후보마다)", "예, 분석당"],
            ["인터뷰 키트 또는 인텔 팩", "아니요 (해제는 필요, 리포트 슬롯은 아님)"],
          ],
        },
        {
          type: "ul",
          items: [
            "전체 채점 분석만 리포트 슬롯을 소모합니다",
            "포함된 리포트를 모두 써도 채팅과 기존 리포트는 계속 열립니다",
            "다른 아이디어에는 별도의 캠페인 패스가 필요합니다",
          ],
        },
        {
          type: "callout",
          text: "실시간 가격과 FAQ는 요금 페이지를 보세요. 결제 문제: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "분석을 더 실행할 수 없어요",
      summary:
        "캠페인 잠김, 리포트 소진, 또는 다른 이유로 버튼이 비활성인 경우.",
      eyebrow: "문제 해결",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "소진",
        "잠김",
        "막힘",
        "채점불가",
        "비활성",
        "상한",
      ],
      blocks: [
        {
          type: "p",
          text: "Validate, 재채점, 딥 검증이 막혀 있으면 아래 순서로 확인하세요.",
        },
        {
          type: "ol",
          items: [
            "캠페인 잠김: 이 아이디어를 아직 해제하지 않았습니다. 해당 아이디어의 해제 / 요금 페이지를 여세요.",
            "리포트 완료: 패스에 포함된 전체 채점 분석을 모두 썼습니다. 채팅과 읽기는 계속 됩니다. 다른 것을 검증하려면 새 아이디어를 시작하세요.",
            "작업이 진행 중: 현재 분석이 끝날 때까지 기다리세요.",
            "실질적 변경 없음: 현재 리포트만 이해하려면 런을 소모하지 않는 Ask(재채점 없음)를 쓰세요.",
          ],
        },
        {
          type: "callout",
          text: "여전히 막혀 있나요? 계정 이메일과 아이디어 제목을 포함해 help@validorian.com으로 메일 주세요.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE, NO-GO",
      summary: "각 스탬프의 의미와 다음에 할 일.",
      eyebrow: "판정",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "스탬프",
        "판정",
        "진행",
        "보류",
        "중단",
        "불충분",
      ],
      blocks: [
        {
          type: "p",
          text: "스탬프가 결론입니다. 숫자는 그것을 뒷받침하지만, 스탬프는 설정한 목표 아래에서 진행할지 여부를 답합니다.",
        },
        {
          type: "ul",
          items: [
            "GO: 근거가 이 프레이밍을 목표에 맞게 추구할 만하다고 지지합니다. 의도를 가지고 만들고 테스트하세요. 준비되면 플랜을 여세요.",
            "MAYBE: 혼재되거나 경계선. 올인하기 전에 아이디어를 다듬거나, 킬테스트를 통과시키거나, 앵글을 바꾸세요.",
            "NO-GO: 지금 서술 그대로는 목표에 약합니다. 강하게 피벗하거나 멈추세요. 치명적 불일치를 다듬지 마세요.",
            "INSUFFICIENT: 정직하게 채점하기에 신뢰도가 너무 낮습니다. 서술을 명확히 하고, 맥락을 추가하거나, 더 나은 근거 후에 다시 실행하세요.",
          ],
        },
        {
          type: "callout",
          text: "사이드 허슬과 벤처 펀딩은 같은 기준으로 채점되지 않습니다. 한 목표에서 GO인 점수가 다른 목표에서는 MAYBE일 수 있습니다.",
        },
        {
          type: "p",
          text: "UI 라벨은 언어에 맞게 표시될 수 있습니다(예: 한국어 스탬프). 채점 규칙은 아래에서 동일한 GO / MAYBE / NO-GO를 사용합니다.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "리포트 읽기",
      summary:
        "결정 표면, 브리프, 시장, 수익, 리스크, 플랜, 근거를 어떻게 훑을지.",
      eyebrow: "리포트",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "섹션",
        "브리프",
        "시장",
        "수익",
        "리스크",
        "플랜",
        "근거",
      ],
      blocks: [
        {
          type: "p",
          text: "한 번만 훑는다면: 스탬프, 이 점수의 이유, 열린 질문, 그다음 킬테스트. 깊이가 필요할 때만 챕터를 펼치세요.",
        },
        {
          type: "ol",
          items: [
            "스탬프와 점수: 목표 적합도와 이 점수의 이유(끌어내리는 요인과 레버).",
            "브리프: 진통제 vs 비타민, 강점, 열린 질문.",
            "시장: 규모, 경쟁사, 채널, 방어 가능성.",
            "수익: 단위 경제와 전망(추정이며 약속이 아님).",
            "리스크: 빨간 칸을 무시하기 전에 매트릭스와 프리모템.",
            "플랜: GO이거나 킬테스트 통과로 빌드 경로가 정당화될 때까지 잠김.",
            "근거: 수요 판독 뒤의 코퍼스(장식이 아닌 영수증).",
          ],
        },
        {
          type: "callout",
          text: "스튜디오에서는 결정이 앞에 오도록 챕터가 접혀 있습니다. 필요한 것만 펼치세요.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "채점이 작동하는 방식",
      summary:
        "기준, 가중치, 게이트. 배지·조정이 헷갈릴 때만 읽으면 됩니다.",
      eyebrow: "내부 동작",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "기준",
        "가중치",
        "게이트",
        "밴드",
        "조정",
        "신뢰",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian을 쓰는 데 이 페이지가 필수는 아닙니다. 채점 메모, 경계 배지, 클램프가 이상해 보일 때 여세요.",
        },
        {
          type: "p",
          text: "쉽게 말하면: 모델이 요인마다 짧은 근거와 문자 등급을 씁니다. 소프트웨어가 그 등급을 숫자로 바꾸고, 목표에 맞게 가중치를 주고, 한 가지 치명적 결함이 다른 강점으로 평균 나 사라지지 않도록 하드 규칙을 적용합니다.",
        },
        { type: "h2", text: "열 가지 기준" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "믿을 것" },
        {
          type: "ul",
          items: [
            "실제 링크와 투표 수가 있는 가져온 근거(게시물, 리뷰)",
            "발동했을 때 채점 메모에 나열된 게이트와 클램프",
            "점수가 GO 또는 MAYBE 선 근처에 있을 때 경계 배지(재실행 시 뒤집힐 수 있음)",
          ],
        },
        {
          type: "p",
          text: "시장 규모 수치와 일부 경쟁사 노트는 검색 기반 모델 추정입니다. 회사를 걸기 전에 출처를 확인하세요.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "점수가 왜 바뀌었나요?",
      summary: "재실행, 목표 변경, 새 프레이밍, 그리고 정상적인 채점 노이즈.",
      eyebrow: "문제 해결",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "변동",
        "다름",
        "뒤집힘",
        "경계",
        "노이즈",
        "재실행",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "아이디어 서술, 목표, 또는 창업자 맥락을 바꿨다면: 점수는 바뀌어야 합니다.",
            "경계 점수: 제품이 임계값의 런 간 노이즈 범위 안에 있을 때 표시합니다. 재실행이 반대편에 착지해도 시스템이 고장 난 것은 아닙니다.",
            "새 근거 또는 킬테스트 결과: 현장 데이터가 수요와 판정을 정직하게 움직일 수 있습니다.",
            "딥 검증: 더 무거운 패스가 신뢰도와 메모를 조정할 수 있습니다. 다른 제품이 아니라 두 번째 시선으로 보세요.",
          ],
        },
        {
          type: "callout",
          text: "프레이밍이 그대로인데 점프가 이상하면, 아이디어 제목과 버전을 포함해 help@validorian.com으로 메일 주세요.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "런을 낭비하지 않고 반복하기",
      summary: "Ask, 새 버전, 앵글, 그리고 언제 재채점할지.",
      eyebrow: "스튜디오 루프",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "질문",
        "채팅",
        "버전",
        "앵글",
        "웨지",
        "재채점",
        "런",
      ],
      blocks: [
        {
          type: "p",
          text: "런(또는 전체 채점 리포트)은 캠페인 할당량을 소모하는 깊은 분석입니다. 현재 리뷰만 이해하려면 Ask를 쓰세요.",
        },
        { type: "h2", text: "무엇이 리포트를 소모하나요?" },
        {
          type: "table",
          headers: ["작업", "전체 채점 리포트를 사용하나요?"],
          rows: [
            ["Ask (이 분석에 대해 채팅)", "아니요"],
            ["새 버전 + 재채점", "예"],
            ["앵글 비교 / 웨지 토너먼트", "예, 채점된 앵글마다"],
            ["딥 검증", "예"],
            ["킬테스트 키트, 인텔, 리포트 읽기", "아니요"],
          ],
        },
        { type: "h2", text: "Ask (재채점 없음)" },
        {
          type: "p",
          text: "현재 리포트에 대해 이야기합니다: 점수, 경쟁사, 리스크. 버전을 만들지 않으며 전체 분석을 사용하지 않습니다.",
        },
        { type: "h2", text: "새 버전" },
        {
          type: "p",
          text: "서술, 목표, 또는 맥락을 바꾼 뒤 재채점합니다. 호기심마다 하지 말고, 프레이밍이나 근거에 실질 변경이 있을 때 쓰세요.",
        },
        { type: "h2", text: "앵글 비교" },
        {
          type: "p",
          text: "앵글(알파 또는 웨지라고도 함)은 같은 핵심 아이디어의 다른 엣지 또는 포지셔닝입니다. 토너먼트는 동일 근거 위에서 그런 엣지 몇 개를 맞대어 채점합니다. 채점된 후보마다 리포트 슬롯을 쓰므로 신중히 고르세요.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "킬테스트와 인터뷰",
      summary: "만들기 전 가장 저렴한 실세계 검증.",
      eyebrow: "현장 작업",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "인터뷰",
        "맘테스트",
        "구매자",
        "합격",
        "실패",
        "현장",
        "킬테스트",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE나 NO-GO는 종종 "덱에서 더 열심히"가 아닙니다. "사전 등록한 합격/실패 기준으로 구매자와 대화하라"입니다.',
        },
        {
          type: "ul",
          items: [
            "가장 위험한 가정: 코퍼스가 정리하지 못한 것",
            "채널이 있는 가장 저렴한 테스트(대략 일주일 이하)",
            "결과를 보기 전에 적어 둔 합격·킬 임계값",
            "인터뷰 키트: 누구와 이야기할지, Mom-Test 스타일 질문(아이디어에 대한 칭찬이 아니라 과거 행동과 사실)",
          ],
        },
        {
          type: "p",
          text: "결과를 기록하고 재채점해 판정이 희망이 아니라 현장 데이터로 갱신되게 하세요.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "딥 검증",
      summary: "더 무거운 패스가 리포트 슬롯을 쓸 가치가 있을 때.",
      eyebrow: "고급",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "딥",
        "심층",
        "불",
        "베어",
        "비용",
      ],
      blocks: [
        {
          type: "p",
          text: "딥 검증은 선택적인 더 무거운 분석(독립 케이스, 추가 점검)입니다. 전체 채점 리포트를 사용하며 표준 패스보다 더 많은 연산을 씁니다.",
        },
        {
          type: "ul",
          items: [
            "아이디어가 진지하고 두 번째, 더 까다로운 시선이 필요할 때 쓰세요",
            "초기 초안과 저렴한 실험에는 건너뛰세요",
            "실제 구매자와의 킬테스트를 대체하지 않습니다",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "언어와 AI 출력",
      summary: "UI 언어 vs 리포트 본문 언어.",
      eyebrow: "로케일",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "언어",
        "한국어",
        "번역",
        "글로브",
        "로케일",
      ],
      blocks: [
        {
          type: "p",
          text: "글로브 전환기는 UI 크롬을 설정합니다: 내비, 버튼, 섹션 제목, 판정 스탬프, 라벨. 이름이나 코드로 언어를 검색할 수 있습니다(예: Korean, 한국어, 또는 ko).",
        },
        {
          type: "p",
          text: "AI가 쓴 본문(요약, 경쟁사 노트, 열린 질문)은 생성 또는 재채점 시 활성 언어를 따릅니다. 예전 영어 리포트는 새 로케일에서 다시 실행하기 전까지 영어로 남습니다.",
        },
        {
          type: "ul",
          items: [
            "헤더에서 언제든지 언어를 바꿀 수 있습니다",
            "저장된 데이터의 기계 코드(판정, 기준 이름)는 채점 일관성을 위해 영어로 유지됩니다",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "개인정보와 아이디어",
      summary: "스튜디오에 넣은 내용을 누가 보는지.",
      eyebrow: "신뢰",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "비공개",
        "데이터",
        "보안",
        "공유",
        "비밀",
        "개인정보",
      ],
      blocks: [
        {
          type: "p",
          text: "계정의 아이디어와 리포트는 기본 비공개입니다. 공개 피드에 게시되지 않습니다.",
        },
        {
          type: "ul",
          items: [
            "각 아이디어를 소유한 계정을 본인이 통제합니다",
            "API 키를 만들면 해당 키 또는 계정 모델의 아이디어에만 접근합니다",
            "채점과 리포트 작성에 모델 제공자를 사용합니다: 처리 시스템에 보내도 괜찮은 비밀만 붙여넣으세요",
            "계정 삭제 도구는 제품의 계정 흐름에 따라 데이터를 제거합니다",
          ],
        },
        {
          type: "callout",
          text: "데이터 처리 관련 문의: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "팀에 도움 요청하기",
      summary: "연락 방법과 포함할 내용.",
      eyebrow: "사람",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "이메일",
        "지원",
        "문의",
        "버그",
        "연락",
      ],
      blocks: [
        {
          type: "p",
          text: "제품 문제, 결제, 막힌 캠페인은 help@validorian.com으로 메일 주세요. Support와 Contact는 당분간 같은 수신함입니다.",
        },
        {
          type: "ul",
          items: [
            "관련되면 계정 이메일과 아이디어 제목을 포함하세요",
            "UI 버그는 스크린샷이 도움이 됩니다",
            "비밀번호는 절대 보내지 마세요",
          ],
        },
      ],
    },
  ],
};
