import type { HelpCatalog } from "../types";

export const helpNl: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Aan de slag",
      blurb: "Van eerste idee tot een volledige validatiepass.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Facturatie & campagnes",
      blurb: "Waarvoor je betaalt, wat een rapport verbruikt, en wat te doen als je op bent.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Scores & oordelen",
      blurb: "Wat de stempel betekent en hoe je het rapport leest.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Werken in de studio",
      blurb: "Vragen, re-scoren, hoeken en kill-tests zonder runs te verspillen.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Account & taal",
      blurb: "Locale, privacy en het team bereiken.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Verbruikt chat een volledig rapport?", slug: "iterate" },
    { q: "Wat ontgrendelde mijn campagne?", slug: "campaigns-and-pricing" },
    { q: "Wat betekent GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Ik kan geen nieuwe analyse draaien", slug: "cant-run-analysis" },
    { q: "Waarom veranderde mijn score na een re-run?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Valideer je eerste idee",
      summary:
        "Maak een account, beschrijf het idee, ontgrendel een campagne en krijg een onderbouwde score.",
      eyebrow: "Begin hier",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "eerste",
        "registreren",
        "beginnen",
        "ontgrendelen",
        "starten",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian is een studio voor businessvalidatie. Je beschrijft een idee tegen jouw doel en krijgt een evidence-based GO / MAYBE / NO-GO met markt, geld, risico's en een volgende test. Geen pep talk.",
        },
        { type: "h2", text: "Het pad" },
        {
          type: "ol",
          items: [
            "Maak een gratis account en open de studio.",
            "Beschrijf wat je aanbiedt, voor wie, en waarom nu. Stel je doel in (side hustle, lifestyle, venture of nog niet zeker) zodat de lat voor GO bij jou past.",
            "Wanneer je klaar bent om te scoren, ontgrendel een volledige campagne op dat idee (één prijs per idee; zie Prijzen voor het actuele bedrag).",
            "Lees eerst de stempel en het beslissingsoppervlak, graaf daarna in markt, geld en bewijs waar nodig.",
            "Itereer: herschrijf de pitch, probeer een andere hoek, stel vragen over de review, of draai een real-world kill-test.",
          ],
        },
        {
          type: "callout",
          text: "Chatten met de review verbrandt nooit een gescoord rapport. Volledige re-scores en diepe analyses gebruiken de campagne-allotment.",
        },
        { type: "h2", text: "Wat je krijgt in een volledige pass" },
        {
          type: "ul",
          items: [
            "Oordeel en score (GO / MAYBE / NO-GO) met vertrouwen en doel-relatieve banden",
            "Vraag, betaalbereidheid, concurrentie en haalbare omzet",
            "Risicokaart en pre-mortem",
            "Kopersprofiel en kanalen",
            "Real-world testplan (kill-test) met pass/fail-drempels",
            "Bewijs uit publieke bronnen (posts, reviews, issues) met links",
            "Ruimte om te itereren: nieuwe versies, hoeken en onbeperkte vragen over de review van dat idee",
          ],
        },
        {
          type: "p",
          text: "Een volledige pass kan een paar minuten duren — echte websearch en scoring, geen instant gok.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campagnes en prijzen",
      summary: "Eén prijs per idee; wat ontgrendelt en wat telt als volledig rapport.",
      eyebrow: "Facturatie",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "betalen",
        "prijs",
        "ontgrendelen",
        "abonnement",
        "kosten",
        "geld",
      ],
      blocks: [
        {
          type: "p",
          text: "Account is gratis. Een campagnepass ontgrendelt een volledig validatiepad op één idee: gescoorde rapporten (tot het inbegrepen maximum, standaard 10 volledige analyses), wedges, kill-testkit, concurrentie-intel en onbeperkte chat op dat idee. Geen abonnement.",
        },
        { type: "h2", text: "Wat verbruikt een rapportslot" },
        {
          type: "table",
          headers: ["Actie", "Gebruikt een volledig gescoord rapport?"],
          rows: [
            ["Ask / chat over de review", "Nee"],
            ["Rapport lezen of uitklappen", "Nee"],
            ["Nieuwe versie + re-score", "Ja"],
            ["Diepe validatie", "Ja (zwaardere run)"],
            ["Hoek- / wedge-tournament (elke gescoorde deelnemer)", "Ja, per analyse"],
            ["Interviewkit of intel pack", "Nee (ontgrendeling nodig, geen rapportslot)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Alleen volledig gescoorde analyses verbruiken een rapportslot",
            "Als de inbegrepen rapporten op zijn, blijven chat en bestaande rapporten open",
            "Een ander idee heeft een eigen campagnepass nodig",
          ],
        },
        {
          type: "callout",
          text: "Zie Prijzen voor de actuele prijs en FAQ. Facturatieproblemen: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Ik kan geen nieuwe analyse draaien",
      summary:
        "Campagne vergrendeld, rapporten op, of de knop is om een andere reden uitgeschakeld.",
      eyebrow: "Probleemoplossing",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "op",
        "vergrendeld",
        "geblokkeerd",
        "kan niet scoren",
        "uitgeschakeld",
        "limiet",
      ],
      blocks: [
        {
          type: "p",
          text: "Als Valideren, re-scoren of diepe validatie geblokkeerd is, check dit in volgorde.",
        },
        {
          type: "ol",
          items: [
            "Campagne vergrendeld: dit idee is nooit ontgrendeld. Open ontgrendelen / Prijzen voor dat idee.",
            "Rapporten voltooid: je hebt de volledig gescoorde analyses in de pass opgebruikt. Chat en lezen blijven open. Start een nieuw idee om iets anders te valideren.",
            "Werk nog bezig: wacht tot de huidige analyse klaar is.",
            "Geen materiële wijziging: wil je alleen het huidige rapport begrijpen, gebruik dan Ask (geen rescore) in plaats van nog een run te verbranden.",
          ],
        },
        {
          type: "callout",
          text: "Nog vast? Mail help@validorian.com met je account-e-mail en de titel van het idee.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE en NO-GO",
      summary: "Wat elke stempel betekent en wat je daarna doet.",
      eyebrow: "Oordelen",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "stempel",
        "oordeel",
        "slagen",
        "falen",
      ],
      blocks: [
        {
          type: "p",
          text: "De stempel is de call. Het getal ondersteunt hem, maar de stempel beantwoordt of je moet doorgaan onder het doel dat je stelde.",
        },
        {
          type: "ul",
          items: [
            "GO: bewijs ondersteunt dit framing voor jouw doel. Bouw en test met intentie. Open het plan wanneer je er klaar voor bent.",
            "MAYBE: gemengd of grensgeval. Verbeter het idee, bewijs een kill-test, of verander de hoek voordat je all-in gaat.",
            "NO-GO: zoals geschreven, zwak voor jouw doel. Pivot hard of stop. Polijst geen fatale mismatch.",
            "INSUFFICIENT: te weinig vertrouwen om eerlijk te graderen. Verhelder de statement, voeg context toe, of draai opnieuw na beter bewijs.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle en venture raise worden niet hetzelfde beoordeeld. Een score die GO haalt voor het ene doel kan in MAYBE zitten voor een ander.",
        },
        {
          type: "p",
          text: "UI-labels kunnen in jouw taal verschijnen (bijvoorbeeld Koreaanse stempels). Scoring gebruikt eronder nog steeds dezelfde GO / MAYBE / NO-GO-regels.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Je rapport lezen",
      summary:
        "Hoe je het beslissingsoppervlak, brief, markt, geld, risico's, plan en bewijs scant.",
      eyebrow: "Het rapport",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "secties",
        "markt",
        "geld",
        "risico's",
        "bewijs",
        "rapport",
      ],
      blocks: [
        {
          type: "p",
          text: "Als je maar één keer scant: stempel, waarom deze score, open vragen, dan de kill-test. Klap hoofdstukken alleen open als je diepte nodig hebt.",
        },
        {
          type: "ol",
          items: [
            "Stempel en score: doel-fit en waarom deze score (sleepankers en hendels).",
            "Brief: pijnstiller vs vitamine, sterktes, open vragen.",
            "Markt: omvang, concurrenten, kanalen, verdedigbaarheid.",
            "Geld: unit economics en projecties (schattingen, geen beloftes).",
            "Risico's: matrix en pre-mortem voordat je de rode cellen negeert.",
            "Plan: geblokkeerd tot GO of een geslaagde kill-test een buildpad rechtvaardigt.",
            "Bewijs: het corpus achter de vraaglezing (bewijsstukken, geen decoratie).",
          ],
        },
        {
          type: "callout",
          text: "In de studio blijven hoofdstukken ingeklapt zodat de beslissing voorop staat. Klap alleen open wat je nodig hebt.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Hoe scoring werkt",
      summary:
        "Criteria, gewichten en gates. Optioneel lezen als een badge of aanpassing je in de war brengt.",
      eyebrow: "Onder de motorkap",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "gewichten",
        "banden",
        "systeemanpassingen",
        "vertrouwen",
      ],
      blocks: [
        {
          type: "p",
          text: "Je hebt deze pagina niet nodig om Validorian te gebruiken. Open hem wanneer een scoringnote, grensbadge of clamp mysterieus lijkt.",
        },
        {
          type: "p",
          text: "In gewone taal: het model schrijft een korte rationale en een lettergrade per factor. Software zet die grades om in cijfers, weegt ze voor jouw doel, en past harde regels toe zodat één fatale zwakte niet kan worden weggemiddeld door sterktes elders.",
        },
        { type: "h2", text: "De tien criteria" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Wat je moet vertrouwen" },
        {
          type: "ul",
          items: [
            "Opgehaald bewijs (posts, reviews) met echte links en votecounts",
            "Gates en clamps onder scoringnotes wanneer ze afgaan",
            "Grensbadges wanneer de score bij een GO- of MAYBE-lijn zit (re-runs kunnen kantelen)",
          ],
        },
        {
          type: "p",
          text: "Marktomvangcijfers en sommige concurrentienotes zijn modelschattingen uit search. Check bronnen voordat je het bedrijf inzet.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Waarom veranderde mijn score?",
      summary: "Re-runs, doelwijzigingen, nieuwe framing en normale scoringruis.",
      eyebrow: "Probleemoplossing",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "variantie",
        "anders",
        "kantelen",
        "grens",
        "ruis",
        "opnieuw",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Je wijzigde de ideestatement, het doel of de foundercontext: de score hoort te veranderen.",
            "Grensscores: het product markeert wanneer je binnen run-tot-run-ruis van een drempel zit. Een re-run kan aan de andere kant landen zonder dat het systeem kapot is.",
            "Nieuw bewijs of een kill-testresultaat: velddata kan vraag en oordeel eerlijk bewegen.",
            "Diepe validatie: een zwaardere pass kan vertrouwen en notes bijstellen; behandel het als een tweede blik, niet als een ander product.",
          ],
        },
        {
          type: "callout",
          text: "Als de framing ongewijzigd is en de sprong wild lijkt, mail help@validorian.com met de ideetitel en versies.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Itereren zonder runs te verspillen",
      summary: "Ask, nieuwe versies, hoeken en wanneer te re-scoren.",
      eyebrow: "Studioloop",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "vragen",
        "versie",
        "hoek",
        "run",
      ],
      blocks: [
        {
          type: "p",
          text: "Een run (of volledig gescoord rapport) is een diepe analyse die campagne-allotment verbruikt. Gebruik Ask wanneer je alleen de huidige review wilt begrijpen.",
        },
        { type: "h2", text: "Wat verbruikt een rapport?" },
        {
          type: "table",
          headers: ["Actie", "Gebruikt een volledig gescoord rapport?"],
          rows: [
            ["Ask (chatten over deze analyse)", "Nee"],
            ["Nieuwe versie + re-score", "Ja"],
            ["Hoeken vergelijken / wedge-tournament", "Ja, per gescoorde hoek"],
            ["Diepe validatie", "Ja"],
            ["Kill-testkit, intel, rapport lezen", "Nee"],
          ],
        },
        { type: "h2", text: "Ask (geen rescore)" },
        {
          type: "p",
          text: "Praat door het huidige rapport: scores, concurrenten, risico's. Maakt geen versie en gebruikt geen volledige analyse.",
        },
        { type: "h2", text: "Nieuwe versie" },
        {
          type: "p",
          text: "Wijzig de statement, het doel of de context, en score opnieuw. Gebruik na een echte wijziging in framing of bewijs, niet na elke nieuwsgierigheid.",
        },
        { type: "h2", text: "Hoeken vergelijken" },
        {
          type: "p",
          text: "Een hoek (soms alpha of wedge genoemd) is een andere edge of positionering van hetzelfde kernidee. Tournaments scoren een paar van die edges head-to-head op hetzelfde bewijs. Elke gescoorde deelnemer gebruikt een rapportslot, dus kies bewust.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-tests en interviews",
      summary: "Het goedkoopste real-world bewijs voordat je bouwt.",
      eyebrow: "Veldwerk",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "interview",
        "koper",
        "slagen",
        "falen",
        "veld",
        "kill-test",
      ],
      blocks: [
        {
          type: "p",
          text: 'Een MAYBE of NO-GO is vaak niet "harder proberen in de deck." Het is "praat met kopers met een vooraf vastgelegde pass/fail-drempel."',
        },
        {
          type: "ul",
          items: [
            "Riskantste aanname: wat het corpus niet heeft afgedicht",
            "Goedkoopste test (ongeveer een week of minder) met een kanaal",
            "Pass- en kill-drempels geschreven voordat je resultaten ziet",
            "Interviewkit: met wie praten en Mom-Test-stijlvragen (verleden gedrag en feiten, geen complimenten over je idee)",
          ],
        },
        {
          type: "p",
          text: "Leg het resultaat vast en score opnieuw zodat het oordeel bijwerkt vanuit velddata, niet hoop.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Diepe validatie",
      summary: "Wanneer de zwaardere pass een rapportslot waard is.",
      eyebrow: "Geavanceerd",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "diep",
        "duur",
        "validatie",
      ],
      blocks: [
        {
          type: "p",
          text: "Diepe validatie is een optionele zwaardere analyse (onafhankelijke cases, extra checks). Het gebruikt een volledig gescoord rapport en kost meer compute dan een standaard pass.",
        },
        {
          type: "ul",
          items: [
            "Gebruik het wanneer het idee serieus is en je een tweede, hardere blik wilt",
            "Sla het over bij vroege drafts en goedkope experimenten",
            "Het vervangt geen kill-test met echte kopers",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Taal en AI-output",
      summary: "UI-taal vs rapportproza-taal.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "taal",
        "vertalen",
        "koreaans",
        "nederlands",
      ],
      blocks: [
        {
          type: "p",
          text: "De globe-switcher zet UI-chrome: nav, knoppen, sectietitels, oordeelstempels en labels. Je kunt talen zoeken op naam of code (bijvoorbeeld Korean, 한국어, of ko).",
        },
        {
          type: "p",
          text: "Door AI geschreven bodytekst (samenvattingen, concurrentienotes, open vragen) volgt de taal die actief was toen je genereerde of re-scorede. Oude Engelse rapporten blijven Engels tot je opnieuw draait onder de nieuwe locale.",
        },
        {
          type: "ul",
          items: [
            "Wissel taal op elk moment via de header",
            "Machinecodes in opgeslagen data (oordelen, criteriumnamen) blijven Engels voor scoringconsistentie",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privacy en jouw ideeën",
      summary: "Wie ziet wat je in de studio zet.",
      eyebrow: "Vertrouwen",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privé",
        "gegevens",
        "beveiliging",
        "delen",
        "geheim",
      ],
      blocks: [
        {
          type: "p",
          text: "Ideeën en rapporten in je account zijn standaard privé. Ze worden niet gepubliceerd op een publieke feed.",
        },
        {
          type: "ul",
          items: [
            "Jij beheert het account dat elk idee bezit",
            "API-keys, als je ze aanmaakt, geven alleen toegang tot ideeën voor dat key- of accountmodel",
            "We gebruiken modelproviders om te scoren en rapporten te schrijven: plak geen secrets die je niet naar verwerkingssystemen mag sturen",
            "Accountverwijderingstools verwijderen je data volgens de accountflow van het product",
          ],
        },
        {
          type: "callout",
          text: "Vragen over dataverwerking: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Hulp van het team",
      summary: "Hoe je ons bereikt en wat je moet meenemen.",
      eyebrow: "Mensen",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "e-mail",
        "ondersteuning",
        "fout",
        "mens",
      ],
      blocks: [
        {
          type: "p",
          text: "Voor productproblemen, facturatie of een vastgelopen campagne, mail help@validorian.com. Support en Contact gaan voorlopig naar dezelfde inbox.",
        },
        {
          type: "ul",
          items: [
            "Vermeld je account-e-mail en de ideetitel indien relevant",
            "Screenshots helpen bij UI-bugs",
            "Stuur nooit wachtwoorden",
          ],
        },
      ],
    },
  ],
};
