import type { HelpCatalog } from "../types";

export const helpPl: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Pierwsze kroki",
      blurb: "Od pierwszego pomysłu do pełnego przebiegu walidacji.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Rozliczenia i kampanie",
      blurb: "Za co płacisz, co spala raport i co robić, gdy skończą się sloty.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Wyniki i werdykty",
      blurb: "Co oznacza pieczątka i jak czytać raport.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Praca w studio",
      blurb: "Pytaj, oceniaj ponownie, kąty i kill-testy bez marnowania przebiegów.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Konto i język",
      blurb: "Locale, prywatność i kontakt z zespołem.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Czy czat zużywa pełny raport?", slug: "iterate" },
    { q: "Co odblokowała moja kampania?", slug: "campaigns-and-pricing" },
    { q: "Co oznacza GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Nie mogę uruchomić kolejnej analizy", slug: "cant-run-analysis" },
    { q: "Dlaczego wynik zmienił się po re-run?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Zweryfikuj pierwszy pomysł",
      summary:
        "Załóż konto, opisz pomysł, odblokuj kampanię i dostań ugruntowany wynik.",
      eyebrow: "Zacznij tutaj",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "pierwszy",
        "rejestracja",
        "zacząć",
        "odblokować",
        "start",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian to studio walidacji biznesu. Opisujesz pomysł względem swojego celu i dostajesz GO / MAYBE / NO-GO oparte na dowodach — z rynkiem, pieniędzmi, ryzykami i kolejnym testem. Nie pep talk.",
        },
        { type: "h2", text: "Ścieżka" },
        {
          type: "ol",
          items: [
            "Załóż darmowe konto i otwórz studio.",
            "Opisz, co oferujesz, dla kogo i dlaczego teraz. Ustaw cel (side hustle, lifestyle, venture lub nie wiem), żeby próg GO pasował do ciebie.",
            "Gdy chcesz ocenić, odblokuj pełną kampanię na tym pomyśle (jedna cena za pomysł; aktualną kwotę zobaczysz w Cenniku).",
            "Najpierw przeczytaj pieczątkę i powierzchnię decyzji, potem wchodź w rynek, pieniądze i dowody w razie potrzeby.",
            "Iteruj: przepisz pitch, spróbuj innego kąta, zadawaj pytania o raport albo zrób kill-test w realu.",
          ],
        },
        {
          type: "callout",
          text: "Czat z raportem nigdy nie spala ocenionego raportu. Pełne re-score i głębokie analizy zużywają przydział kampanii.",
        },
        { type: "h2", text: "Co dostajesz w pełnym przebiegu" },
        {
          type: "ul",
          items: [
            "Werdykt i wynik (GO / MAYBE / NO-GO) z pewnością i pasami względnymi do celu",
            "Popyt, skłonność do zapłaty, konkurencja i osiągalne przychody",
            "Mapa ryzyka i pre-mortem",
            "Profil kupującego i kanały",
            "Plan testu w realu (kill-test) z progami pass/fail",
            "Dowody ze źródeł publicznych (posty, recenzje, issues) z linkami",
            "Miejsce na iterację: nowe wersje, kąty i nielimitowane pytania o raport tego pomysłu",
          ],
        },
        {
          type: "p",
          text: "Pełny przebieg może zająć kilka minut — realne wyszukiwanie w sieci i scoring, nie natychmiastowy strzał w ciemno.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Kampanie i cennik",
      summary:
        "Jedna cena za pomysł; co się odblokowuje i co liczy się jako pełny raport.",
      eyebrow: "Rozliczenia",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "płacić",
        "cena",
        "odblokować",
        "subskrypcja",
        "koszt",
        "pieniądze",
        "kampania",
      ],
      blocks: [
        {
          type: "p",
          text: "Konto jest darmowe. Przebieg kampanii odblokowuje pełną ścieżkę walidacji jednego pomysłu: ocenione raporty (do limitu w pakiecie, domyślnie 10 pełnych analiz), wedge'e, kit kill-testu, intel o konkurencji i nielimitowany czat na tym pomyśle. Bez subskrypcji.",
        },
        { type: "h2", text: "Co spala slot raportu" },
        {
          type: "table",
          headers: ["Akcja", "Czy zużywa pełny oceniony raport?"],
          rows: [
            ["Pytaj / czat o raporcie", "Nie"],
            ["Czytaj lub rozwijaj raport", "Nie"],
            ["Nowa wersja + re-score", "Tak"],
            ["Głęboka walidacja", "Tak (cięższy przebieg)"],
            ["Turniej kątów / wedge (każdy oceniony uczestnik)", "Tak, na analizę"],
            ["Kit wywiadów lub pakiet intel", "Nie (wymaga odblokowania, nie slotu raportu)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Tylko pełne ocenione analizy spalają slot raportu",
            "Gdy raporty z pakietu się skończą, czat i istniejące raporty zostają otwarte",
            "Inny pomysł wymaga własnego przebiegu kampanii",
          ],
        },
        {
          type: "callout",
          text: "Aktualną cenę i FAQ znajdziesz w Cenniku. Problemy z rozliczeniami: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Nie mogę uruchomić kolejnej analizy",
      summary:
        "Kampania zablokowana, raporty wyczerpane albo przycisk wyłączony z innego powodu.",
      eyebrow: "Rozwiązywanie problemów",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "wyczerpane",
        "zablokowane",
        "nie mogę ocenić",
        "wyłączone",
        "limit",
      ],
      blocks: [
        {
          type: "p",
          text: "Jeśli Waliduj, re-score lub głęboka walidacja jest zablokowana, sprawdź po kolei.",
        },
        {
          type: "ol",
          items: [
            "Kampania zablokowana: ten pomysł nigdy nie został odblokowany. Otwórz odblokowanie / Cennik dla tego pomysłu.",
            "Raporty wyczerpane: zużyłeś pełne ocenione analizy z przebiegu. Czat i czytanie zostają otwarte. Zacznij nowy pomysł, by walidować coś innego.",
            "Praca w toku: poczekaj, aż skończy się bieżąca analiza.",
            "Brak istotnej zmiany: jeśli chcesz tylko zrozumieć bieżący raport, użyj Pytaj (bez re-score) zamiast spalać kolejny przebieg.",
          ],
        },
        {
          type: "callout",
          text: "Nadal utknąłeś? Napisz na help@validorian.com z e-mailem konta i tytułem pomysłu.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE i NO-GO",
      summary: "Co oznacza każda pieczątka i co robić dalej.",
      eyebrow: "Werdykty",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "pieczątka",
        "werdykt",
        "zaliczenie",
        "porażka",
        "niewystarczające",
      ],
      blocks: [
        {
          type: "p",
          text: "Pieczątka to decyzja. Liczba ją wspiera, ale pieczątka odpowiada, czy iść dalej przy celu, który ustawiłeś.",
        },
        {
          type: "ul",
          items: [
            "GO: dowody wspierają pogoń za tym framingiem pod twój cel. Buduj i testuj z intencją. Otwórz plan, gdy będziesz gotów.",
            "MAYBE: mieszane lub na granicy. Popraw pomysł, udowodnij kill-test albo zmień kąt, zanim pójdziesz all-in.",
            "NO-GO: w tej formie słabe względem twojego celu. Twardy pivot albo stop. Nie poleruj fatalnego niedopasowania.",
            "INSUFFICIENT: pewność jest za niska, by ocenić uczciwie. Doprecyzuj opis, dodaj kontekst albo uruchom ponownie po lepszych dowodach.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle i runda venture nie są oceniane tak samo. Wynik, który jest GO dla jednego celu, może siedzieć w MAYBE dla innego.",
        },
        {
          type: "p",
          text: "Etykiety UI mogą być w twoim języku (np. pieczątki po koreańsku). Scoring nadal używa tych samych reguł GO / MAYBE / NO-GO pod spodem.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Jak czytać raport",
      summary:
        "Jak skanować powierzchnię decyzji, brief, rynek, pieniądze, ryzyka, plan i dowody.",
      eyebrow: "Raport",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "sekcje",
        "rynek",
        "pieniądze",
        "ryzyka",
        "dowody",
        "raport",
      ],
      blocks: [
        {
          type: "p",
          text: "Jeśli skanujesz tylko raz: pieczątka, dlaczego ten wynik, otwarte pytania, potem kill-test. Rozwijaj rozdziały tylko, gdy potrzebujesz głębi.",
        },
        {
          type: "ol",
          items: [
            "Pieczątka i wynik: dopasowanie do celu i dlaczego ten wynik (hamulce i dźwignie).",
            "Brief: painkiller vs witamina, mocne strony, otwarte pytania.",
            "Rynek: wymiarowanie, konkurenci, kanały, obrona.",
            "Pieniądze: unit economics i projekcje (szacunki, nie obietnice).",
            "Ryzyka: macierz i pre-mortem, zanim zignorujesz czerwone komórki.",
            "Plan: zablokowany, dopóki GO lub zaliczony kill-test nie uzasadni ścieżki budowy.",
            "Dowody: korpus za odczytem popytu (rachunki, nie dekoracja).",
          ],
        },
        {
          type: "callout",
          text: "W studio rozdziały zostają zwinięte, żeby wiodła decyzja. Rozwijaj tylko to, czego potrzebujesz.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Jak działa scoring",
      summary:
        "Kryteria, wagi i bramki. Opcjonalna lektura, gdy badge lub korekta cię myli.",
      eyebrow: "Pod maską",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "kryteria",
        "wagi",
        "pasy",
        "korekty systemowe",
        "zaufanie",
      ],
      blocks: [
        {
          type: "p",
          text: "Nie potrzebujesz tej strony, by używać Validorian. Otwórz ją, gdy notatka o ocenie, badge na granicy albo clamp wygląda tajemniczo.",
        },
        {
          type: "p",
          text: "Prosto: model pisze krótkie rationale i literową ocenę na czynnik. Software zamienia te oceny w liczby, waży je pod twój cel i stosuje twarde reguły, żeby jedna fatalna wada nie zniknęła w średniej z mocnych stron gdzie indziej.",
        },
        { type: "h2", text: "Dziesięć kryteriów" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Czemu ufać" },
        {
          type: "ul",
          items: [
            "Pobrane dowody (posty, recenzje) z realnymi linkami i licznikami głosów",
            "Bramki i clampy wymienione w notatkach o ocenie, gdy się odpalą",
            "Badge na granicy, gdy wynik siedzi blisko linii GO lub MAYBE (re-run może odwrócić)",
          ],
        },
        {
          type: "p",
          text: "Liczby wymiarowania rynku i część notatek o konkurencji to szacunki modelu z wyszukiwania. Sprawdź źródła, zanim postawisz firmę.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Dlaczego wynik się zmienił?",
      summary:
        "Re-runy, zmiana celu, nowy framing i normalny szum scoringu.",
      eyebrow: "Rozwiązywanie problemów",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "wariancja",
        "inny",
        "odwrócenie",
        "szum",
        "ponownie",
        "zmienił",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Zmieniłeś opis pomysłu, cel lub kontekst foundera: wynik powinien się zmienić.",
            "Wyniki na granicy: produkt oznacza, gdy siedzisz w szumie run-to-run wokół progu. Re-run może wylądować po drugiej stronie — to nie znaczy, że system jest zepsuty.",
            "Nowe dowody lub wynik kill-testu: dane z pola mogą uczciwie przesunąć popyt i werdykt.",
            "Głęboka walidacja: cięższy przebieg może skorygować pewność i notatki; traktuj to jako drugie spojrzenie, nie inny produkt.",
          ],
        },
        {
          type: "callout",
          text: "Jeśli framing się nie zmienił, a skok wygląda dziko, napisz na help@validorian.com z tytułem pomysłu i wersjami.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Iteruj bez marnowania przebiegów",
      summary: "Pytaj, nowe wersje, kąty i kiedy robić re-score.",
      eyebrow: "Pętla studia",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "pytaj",
        "wersja",
        "kąt",
        "re-score",
        "przebieg",
        "iteracja",
      ],
      blocks: [
        {
          type: "p",
          text: "Przebieg (lub pełny oceniony raport) to głęboka analiza, która spala przydział kampanii. Użyj Pytaj, gdy chcesz tylko zrozumieć bieżący raport.",
        },
        { type: "h2", text: "Co spala raport?" },
        {
          type: "table",
          headers: ["Akcja", "Czy zużywa pełny oceniony raport?"],
          rows: [
            ["Pytaj (czat o tej analizie)", "Nie"],
            ["Nowa wersja + re-score", "Tak"],
            ["Porównaj kąty / turniej wedge", "Tak, na oceniony kąt"],
            ["Głęboka walidacja", "Tak"],
            ["Kit kill-testu, intel, czytanie raportu", "Nie"],
          ],
        },
        { type: "h2", text: "Pytaj (bez re-score)" },
        {
          type: "p",
          text: "Przegadaj bieżący raport: wyniki, konkurenci, ryzyka. Nie tworzy wersji i nie zużywa pełnej analizy.",
        },
        { type: "h2", text: "Nowa wersja" },
        {
          type: "p",
          text: "Zmień opis, cel lub kontekst, potem oceń ponownie. Używaj po realnej zmianie framingu lub dowodów, nie po każdej ciekawostce.",
        },
        { type: "h2", text: "Porównaj kąty" },
        {
          type: "p",
          text: "Kąt (czasem alpha lub wedge) to inna krawędź albo pozycjonowanie tego samego rdzenia pomysłu. Turnieje oceniają kilka takich krawędzi head-to-head na tych samych dowodach. Każdy oceniony uczestnik zużywa slot raportu — wybieraj świadomie.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-testy i wywiady",
      summary: "Najtańszy realny dowód, zanim zbudujesz.",
      eyebrow: "Praca w terenie",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "wywiad",
        "kupujący",
        "zaliczenie",
        "porażka",
        "teren",
        "kill-test",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE lub NO-GO często nie znaczy „próbuj mocniej w decku". Znaczy „rozmawiaj z kupującymi przy wcześniej zarejestrowanym progu pass/fail."',
        },
        {
          type: "ul",
          items: [
            "Najryzykowniejsze założenie: to, czego korpus nie rozstrzygnął",
            "Najtańszy test (ok. tydzień lub mniej) z kanałem",
            "Progi pass i kill zapisane, zanim zobaczysz wyniki",
            "Kit wywiadów: z kim rozmawiać i pytania w stylu Mom-Test (przeszłe zachowania i fakty, nie komplementy o twoim pomyśle)",
          ],
        },
        {
          type: "p",
          text: "Zapisz wynik i oceń ponownie, żeby werdykt zaktualizował się z danych z pola, nie z nadziei.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Głęboka walidacja",
      summary: "Kiedy cięższy przebieg jest wart slotu raportu.",
      eyebrow: "Zaawansowane",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "głęboka",
        "kosztowne",
        "walidacja",
      ],
      blocks: [
        {
          type: "p",
          text: "Głęboka walidacja to opcjonalna cięższa analiza (niezależne case'y, dodatkowe checki). Zużywa pełny oceniony raport i kosztuje więcej compute niż standardowy przebieg.",
        },
        {
          type: "ul",
          items: [
            "Użyj, gdy pomysł jest poważny i chcesz drugiego, twardszego spojrzenia",
            "Pomiń na wczesnych draftach i tanich eksperymentach",
            "Nie zastępuje kill-testu z realnymi kupującymi",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Język i output AI",
      summary: "Język UI vs język prozy raportu.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "język",
        "koreański",
        "tłumaczyć",
        "globus",
        "lokalizacja",
      ],
      blocks: [
        {
          type: "p",
          text: "Przełącznik z globusem ustawia chrome UI: nawigację, przyciski, tytuły sekcji, pieczątki werdyktów i etykiety. Możesz szukać języków po nazwie lub kodzie (np. Polish, polski lub pl).",
        },
        {
          type: "p",
          text: "Tekst pisany przez AI (podsumowania, notatki o konkurencji, otwarte pytania) podąża za językiem aktywnym w momencie generowania lub re-score. Stare angielskie raporty zostają po angielsku, dopóki nie uruchomisz ponownie pod nowym locale.",
        },
        {
          type: "ul",
          items: [
            "Zmieniaj język w dowolnym momencie z nagłówka",
            "Kody maszynowe w zapisanych danych (werdykty, nazwy kryteriów) zostają po angielsku dla spójności scoringu",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Prywatność i twoje pomysły",
      summary: "Kto widzi to, co wkładasz do studia.",
      eyebrow: "Zaufanie",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "prywatne",
        "dane",
        "bezpieczeństwo",
        "udostępniać",
        "sekret",
        "prywatność",
      ],
      blocks: [
        {
          type: "p",
          text: "Pomysły i raporty na twoim koncie są domyślnie prywatne. Nie publikujemy ich w publicznym feedzie.",
        },
        {
          type: "ul",
          items: [
            "Kontrolujesz konto, które jest właścicielem każdego pomysłu",
            "Klucze API, jeśli je utworzysz, mają dostęp tylko do pomysłów w modelu tego klucza lub konta",
            "Używamy dostawców modeli do scoringu i pisania raportów: nie wklejaj sekretów, których nie możesz pozwolić sobie wysłać do systemów przetwarzania",
            "Narzędzia usuwania konta usuwają twoje dane zgodnie z flow konta w produkcie",
          ],
        },
        {
          type: "callout",
          text: "Pytania o obsługę danych: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Pomoc od zespołu",
      summary: "Jak do nas dotrzeć i co dołączyć.",
      eyebrow: "Ludzie",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "wsparcie",
        "kontakt",
        "błąd",
        "człowiek",
      ],
      blocks: [
        {
          type: "p",
          text: "W sprawach produktu, rozliczeń lub zablokowanej kampanii napisz na help@validorian.com. Wsparcie i Kontakt idą na razie do tej samej skrzynki.",
        },
        {
          type: "ul",
          items: [
            "Podaj e-mail konta i tytuł pomysłu, jeśli to istotne",
            "Zrzuty ekranu pomagają przy bugach UI",
            "Nigdy nie wysyłaj haseł",
          ],
        },
      ],
    },
  ],
};
