import type { HelpCatalog } from "../types";

export const helpPt: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Primeiros passos",
      blurb: "Da primeira ideia a um ciclo completo de validação.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Cobrança e campanhas",
      blurb: "O que você paga, o que consome um relatório e o que fazer quando acaba.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Notas e vereditos",
      blurb: "O que o carimbo significa e como ler o relatório.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Trabalhando no studio",
      blurb: "Pergunte, reavalie, ângulos e kill-tests sem desperdiçar rodadas.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Conta e idioma",
      blurb: "Localidade, privacidade e como falar com o time.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "O chat usa um relatório completo?", slug: "iterate" },
    { q: "O que minha campanha desbloqueou?", slug: "campaigns-and-pricing" },
    { q: "O que significa GO / MAYBE / NO-GO?", slug: "verdicts" },
    { q: "Não consigo rodar outra análise", slug: "cant-run-analysis" },
    { q: "Por que minha nota mudou depois de uma nova rodada?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Valide sua primeira ideia",
      summary:
        "Crie uma conta, descreva a ideia, desbloqueie uma campanha e receba uma nota fundamentada.",
      eyebrow: "Comece aqui",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "primeiro",
        "cadastro",
        "começar",
        "desbloquear",
        "onboarding",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian é um studio de validação de negócios. Você descreve uma ideia em relação ao seu objetivo e recebe um GO / MAYBE / NO-GO com base em evidências — mercado, dinheiro, riscos e o próximo teste. Não é pep talk.",
        },
        { type: "h2", text: "O caminho" },
        {
          type: "ol",
          items: [
            "Crie uma conta gratuita e abra o studio.",
            "Descreva o que você oferece, para quem e por que agora. Defina seu objetivo (side hustle, lifestyle, venture ou incerto) para que a barra de GO combine com você.",
            "Quando estiver pronto para pontuar, desbloqueie uma campanha completa nessa ideia (um preço por ideia; veja Preços para o valor atual).",
            "Leia o carimbo e a superfície de decisão primeiro; depois aprofunde em mercado, dinheiro e evidências conforme precisar.",
            "Itere: reescreva o pitch, teste outro ângulo, faça perguntas na revisão ou rode um kill-test no mundo real.",
          ],
        },
        {
          type: "callout",
          text: "Conversar com a revisão nunca consome um relatório pontuado. Reavaliações completas e análises profundas usam a cota da campanha.",
        },
        { type: "h2", text: "O que você ganha em um passe completo" },
        {
          type: "ul",
          items: [
            "Veredito e nota (GO / MAYBE / NO-GO) com confiança e faixas relativas ao objetivo",
            "Demanda, disposição a pagar, concorrência e receita obtível",
            "Mapa de riscos e pré-mortem",
            "Perfil do comprador e canais",
            "Plano de teste no mundo real (kill-test) com barras de pass/fail",
            "Evidências de fontes públicas (posts, reviews, issues) com links",
            "Espaço para iterar: novas versões, ângulos e perguntas ilimitadas na revisão daquela ideia",
          ],
        },
        {
          type: "p",
          text: "Um passe completo pode levar alguns minutos — busca real na web e pontuação, não um chute instantâneo.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Campanhas e preços",
      summary: "Um preço por ideia; o que desbloqueia e o que conta como relatório completo.",
      eyebrow: "Cobrança",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "pagar",
        "preço",
        "desbloquear",
        "assinatura",
        "custo",
        "dinheiro",
      ],
      blocks: [
        {
          type: "p",
          text: "A conta é gratuita. Um passe de campanha desbloqueia um caminho completo de validação em uma ideia: relatórios pontuados (até o teto incluído, padrão 10 análises completas), wedges, kit de kill-test, inteligência de concorrentes e chat ilimitado nessa ideia. Sem assinatura.",
        },
        { type: "h2", text: "O que consome um slot de relatório" },
        {
          type: "table",
          headers: ["Ação", "Usa um relatório pontuado completo?"],
          rows: [
            ["Perguntar / chat sobre a revisão", "Não"],
            ["Ler ou expandir o relatório", "Não"],
            ["Nova versão + reavaliar", "Sim"],
            ["Validação profunda", "Sim (rodada mais pesada)"],
            ["Torneio de ângulos / wedge (cada entrante pontuado)", "Sim, por análise"],
            ["Kit de entrevista ou pacote de intel", "Não (precisa de desbloqueio, não de slot de relatório)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Só análises pontuadas completas consomem um slot de relatório",
            "Quando os relatórios incluídos acabam, chat e relatórios existentes continuam abertos",
            "Uma ideia diferente precisa do seu próprio passe de campanha",
          ],
        },
        {
          type: "callout",
          text: "Veja Preços para o valor ao vivo e o FAQ. Problemas de cobrança: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Não consigo rodar outra análise",
      summary:
        "Campanha bloqueada, relatórios esgotados ou o botão desabilitado por outro motivo.",
      eyebrow: "Solução de problemas",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "esgotado",
        "bloqueado",
        "travado",
        "não pontua",
        "desabilitado",
        "teto",
      ],
      blocks: [
        {
          type: "p",
          text: "Se Validar, reavaliar ou validação profunda estiver bloqueado, confira nesta ordem.",
        },
        {
          type: "ol",
          items: [
            "Campanha bloqueada: esta ideia nunca foi desbloqueada. Abra desbloqueio / Preços para essa ideia.",
            "Relatórios concluídos: você usou as análises pontuadas completas incluídas no passe. Chat e leitura continuam abertos. Comece uma nova ideia para validar algo diferente.",
            "Trabalho ainda rodando: espere a análise atual terminar.",
            "Sem mudança material: se você só quer entender o relatório atual, use Perguntar (sem reavaliar) em vez de gastar outra rodada.",
          ],
        },
        {
          type: "callout",
          text: "Ainda travado? Escreva para help@validorian.com com o e-mail da conta e o título da ideia.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE e NO-GO",
      summary: "O que cada carimbo significa e o que fazer em seguida.",
      eyebrow: "Vereditos",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "carimbo",
        "veredito",
        "aprovado",
        "reprovado",
      ],
      blocks: [
        {
          type: "p",
          text: "O carimbo é a decisão. O número sustenta, mas o carimbo responde se seguir adiante sob o objetivo que você definiu.",
        },
        {
          type: "ul",
          items: [
            "GO: as evidências apoiam perseguir esse enquadramento para o seu objetivo. Construa e teste com intenção. Abra o plano quando estiver pronto.",
            "MAYBE: misto ou no limite. Melhore a ideia, prove um kill-test ou mude o ângulo antes de ir all-in.",
            "NO-GO: como está escrito, fraco para o seu objetivo. Pivotar com força ou parar. Não polir um desalinhamento fatal.",
            "INSUFFICIENT: a confiança é baixa demais para notar com honestidade. Esclareça o enunciado, acrescente contexto ou rode de novo com evidências melhores.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle e rodada de venture não são avaliados da mesma forma. Uma nota que passa em GO para um objetivo pode ficar em MAYBE para outro.",
        },
        {
          type: "p",
          text: "Rótulos da interface podem aparecer no seu idioma (por exemplo carimbos em coreano). A pontuação por baixo ainda usa as mesmas regras GO / MAYBE / NO-GO.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Lendo seu relatório",
      summary:
        "Como varrer a superfície de decisão, brief, mercado, dinheiro, riscos, plano e evidências.",
      eyebrow: "O relatório",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "seções",
        "mercado",
        "dinheiro",
        "riscos",
        "plano",
        "evidências",
      ],
      blocks: [
        {
          type: "p",
          text: "Se for só uma olhada: carimbo, por que essa nota, perguntas em aberto e o kill-test. Expanda capítulos só quando precisar de profundidade.",
        },
        {
          type: "ol",
          items: [
            "Carimbo e nota: aderência ao objetivo e por que essa nota (arrastos e alavancas).",
            "Brief: remédio vs vitamina, forças, perguntas em aberto.",
            "Mercado: dimensionamento, concorrentes, canais, defensabilidade.",
            "Dinheiro: unit economics e projeções (estimativas, não promessas).",
            "Riscos: matriz e pré-mortem antes de ignorar as células vermelhas.",
            "Plano: liberado quando GO ou um kill-test aprovado justifica um caminho de build.",
            "Evidências: o corpus por trás da leitura de demanda (comprovantes, não enfeite).",
          ],
        },
        {
          type: "callout",
          text: "No studio, os capítulos ficam recolhidos para a decisão liderar. Expanda só o que precisar.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Como a pontuação funciona",
      summary:
        "Critérios, pesos e gates. Leitura opcional se um badge ou ajuste te confundir.",
      eyebrow: "Por baixo do capô",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "critérios",
        "pesos",
        "faixas",
        "ajustes",
        "confiança",
      ],
      blocks: [
        {
          type: "p",
          text: "Você não precisa desta página para usar o Validorian. Abra quando uma nota de pontuação, badge de limite ou clamp parecer misterioso.",
        },
        {
          type: "p",
          text: "Em termos simples: o modelo escreve uma breve justificativa e uma nota por letra em cada fator. O software transforma essas notas em números, pondera pelo seu objetivo e aplica regras rígidas para que uma falha fatal não seja diluída por forças em outros pontos.",
        },
        { type: "h2", text: "Os dez critérios" },
        {
          type: "ul",
          items: [
            "Força da Demanda, Disposição a Pagar, Ajuste Problema-Solução",
            "Retenção e Recorrência, Timing de Mercado, Posição Competitiva",
            "Diferenciação / Fossado, Facilidade de Aquisição, Fit do Fundador, Fit com o Objetivo",
          ],
        },
        { type: "h2", text: "No que você deve confiar" },
        {
          type: "ul",
          items: [
            "Evidências buscadas (posts, reviews) com links reais e contagens de votos",
            "Gates e clamps listados nas notas de pontuação quando disparam",
            "Badges de limite quando a nota fica perto da linha de GO ou MAYBE (novas rodadas podem virar)",
          ],
        },
        {
          type: "p",
          text: "Números de dimensionamento de mercado e algumas notas de concorrentes são estimativas do modelo a partir de busca. Cheque as fontes antes de apostar a empresa.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Por que minha nota mudou?",
      summary: "Novas rodadas, mudança de objetivo, novo enquadramento e ruído normal de pontuação.",
      eyebrow: "Solução de problemas",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "variância",
        "diferente",
        "virou",
        "limite",
        "ruído",
        "rodar de novo",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Você mudou o enunciado da ideia, o objetivo ou o contexto do fundador: a nota deve mudar.",
            "Notas no limite: o produto marca quando você está dentro do ruído de rodada a rodada de um limiar. Uma nova rodada pode cair do outro lado sem significar que o sistema quebrou.",
            "Nova evidência ou resultado de kill-test: dados de campo podem mover demanda e veredito com honestidade.",
            "Validação profunda: um passe mais pesado pode ajustar confiança e notas; trate como uma segunda olhada, não como outro produto.",
          ],
        },
        {
          type: "callout",
          text: "Se o enquadramento não mudou e o salto parece absurdo, escreva para help@validorian.com com o título da ideia e as versões.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Itere sem desperdiçar rodadas",
      summary: "Perguntar, novas versões, ângulos e quando reavaliar.",
      eyebrow: "Loop do studio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "perguntar",
        "versão",
        "ângulo",
        "reavaliar",
        "rodada",
      ],
      blocks: [
        {
          type: "p",
          text: "Uma rodada (ou relatório pontuado completo) é uma análise profunda que consome a cota da campanha. Use Perguntar quando só quiser entender a revisão atual.",
        },
        { type: "h2", text: "O que consome um relatório?" },
        {
          type: "table",
          headers: ["Ação", "Usa um relatório pontuado completo?"],
          rows: [
            ["Perguntar (chat sobre esta análise)", "Não"],
            ["Nova versão + reavaliar", "Sim"],
            ["Comparar ângulos / torneio de wedge", "Sim, por ângulo pontuado"],
            ["Validação profunda", "Sim"],
            ["Kit de kill-test, intel, ler o relatório", "Não"],
          ],
        },
        { type: "h2", text: "Perguntar (sem reavaliar)" },
        {
          type: "p",
          text: "Converse sobre o relatório atual: notas, concorrentes, riscos. Não cria versão e não usa uma análise completa.",
        },
        { type: "h2", text: "Nova versão" },
        {
          type: "p",
          text: "Mude o enunciado, o objetivo ou o contexto e reavalie. Use depois de uma mudança real de enquadramento ou evidência, não a cada curiosidade.",
        },
        { type: "h2", text: "Comparar ângulos" },
        {
          type: "p",
          text: "Um ângulo (às vezes chamado de alpha ou wedge) é uma aresta ou posicionamento diferente da mesma ideia central. Torneios pontuam algumas dessas arestas frente a frente na mesma evidência. Cada entrante pontuado usa um slot de relatório — escolha com intenção.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-tests e entrevistas",
      summary: "A prova mais barata no mundo real antes de construir.",
      eyebrow: "Trabalho de campo",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "entrevista",
        "comprador",
        "campo",
        "Mom-Test",
      ],
      blocks: [
        {
          type: "p",
          text: 'Um MAYBE ou NO-GO muitas vezes não é "tente mais no deck." É "fale com compradores com uma barra de pass/fail pré-registrada."',
        },
        {
          type: "ul",
          items: [
            "Premissa mais arriscada: o que o corpus não fechou",
            "Teste mais barato (cerca de uma semana ou menos) com um canal",
            "Limiares de passar e matar escritos antes de ver os resultados",
            "Kit de entrevista: com quem falar e perguntas no estilo Mom-Test (comportamento passado e fatos, não elogios à sua ideia)",
          ],
        },
        {
          type: "p",
          text: "Registre o resultado e reavalie para o veredito atualizar com dados de campo, não com esperança.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Validação profunda",
      summary: "Quando o passe mais pesado vale um slot de relatório.",
      eyebrow: "Avançado",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "profunda",
        "cara",
        "avançado",
      ],
      blocks: [
        {
          type: "p",
          text: "Validação profunda é uma análise opcional mais pesada (casos independentes, checagens extras). Usa um relatório pontuado completo e custa mais computação que um passe padrão.",
        },
        {
          type: "ul",
          items: [
            "Use quando a ideia é séria e você quer uma segunda olhada mais dura",
            "Pule em rascunhos iniciais e experimentos baratos",
            "Não substitui um kill-test com compradores reais",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Idioma e saída da IA",
      summary: "Idioma da UI vs idioma do texto do relatório.",
      eyebrow: "Localidade",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "idioma",
        "traduzir",
        "globo",
        "português",
        "coreano",
      ],
      blocks: [
        {
          type: "p",
          text: "O seletor de globo define o chrome da UI: nav, botões, títulos de seção, carimbos de veredito e rótulos. Você pode buscar idiomas por nome ou código (por exemplo Korean, 한국어 ou ko).",
        },
        {
          type: "p",
          text: "O texto de corpo escrito pela IA (resumos, notas de concorrentes, perguntas em aberto) segue o idioma ativo quando você gera ou reavalia. Relatórios antigos em inglês permanecem em inglês até você rodar de novo na nova localidade.",
        },
        {
          type: "ul",
          items: [
            "Troque o idioma a qualquer momento pelo header",
            "Códigos de máquina nos dados armazenados (vereditos, nomes de critérios) ficam em inglês para consistência da pontuação",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Privacidade e suas ideias",
      summary: "Quem vê o que você coloca no studio.",
      eyebrow: "Confiança",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "privado",
        "dados",
        "segurança",
        "compartilhar",
        "segredo",
      ],
      blocks: [
        {
          type: "p",
          text: "Ideias e relatórios na sua conta são privados por padrão. Não são publicados em um feed público.",
        },
        {
          type: "ul",
          items: [
            "Você controla a conta que é dona de cada ideia",
            "Chaves de API, se você criar, só acessam ideias desse modelo de chave ou conta",
            "Usamos provedores de modelo para pontuar e escrever relatórios: não cole segredos que você não pode mandar para sistemas de processamento",
            "Ferramentas de exclusão de conta removem seus dados conforme o fluxo de conta do produto",
          ],
        },
        {
          type: "callout",
          text: "Dúvidas sobre tratamento de dados: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Peça ajuda ao time",
      summary: "Como nos alcançar e o que incluir.",
      eyebrow: "Humanos",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "e-mail",
        "suporte",
        "contato",
        "humano",
      ],
      blocks: [
        {
          type: "p",
          text: "Para problemas de produto, cobrança ou campanha travada, escreva para help@validorian.com. Suporte e Contato vão para a mesma caixa por enquanto.",
        },
        {
          type: "ul",
          items: [
            "Inclua o e-mail da conta e o título da ideia, se for relevante",
            "Prints ajudam em bugs de UI",
            "Nunca envie senhas",
          ],
        },
      ],
    },
  ],
};
