import type { HelpCatalog } from "../types";

export const helpTr: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Başlarken",
      blurb: "İlk fikirden tam doğrulama geçişine.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Faturalama ve kampanyalar",
      blurb: "Neye ödersiniz, ne bir rapor tüketir ve bittiğinde ne yaparsınız.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Puanlar ve kararlar",
      blurb: "Mühür ne anlama gelir ve raporu nasıl okursunuz.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Stüdyoda çalışmak",
      blurb: "Sor, yeniden puanla, açılar ve kill-testler — çalışmaları boşa harcamadan.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Hesap ve dil",
      blurb: "Dil, gizlilik ve ekibe ulaşmak.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Sohbet tam bir rapor tüketir mi?", slug: "iterate" },
    { q: "Kampanyam neyi açtı?", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO ne demek?", slug: "verdicts" },
    { q: "Başka analiz çalıştıramıyorum", slug: "cant-run-analysis" },
    { q: "Yeniden çalıştırmadan sonra puanım neden değişti?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "İlk fikrinizi doğrulayın",
      summary:
        "Hesap oluşturun, fikri tanımlayın, kampanyayı açın ve kanıta dayalı bir puan alın.",
      eyebrow: "Buradan başlayın",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "ilk",
        "kayıt",
        "başla",
        "aç",
        "başlangıç",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian bir iş fikri doğrulama stüdyosudur. Fikri hedefinize göre tanımlarsınız; kanıta dayalı GO / MAYBE / NO-GO, pazar, para, riskler ve sıradaki testle birlikte alırsınız. Moral konuşması değil.",
        },
        { type: "h2", text: "Yol" },
        {
          type: "ol",
          items: [
            "Ücretsiz hesap oluşturun ve stüdyoyu açın.",
            "Ne sunduğunuzu, kime ve neden şimdi olduğunu tanımlayın. GO eşiği size uysun diye hedefinizi ayarlayın (yan iş, yaşam tarzı, venture veya emin değilim).",
            "Puanlamaya hazır olduğunuzda o fikirde tam bir kampanya açın (fikir başına tek fiyat; güncel tutar için Fiyatlandırma'ya bakın).",
            "Önce mühürü ve karar yüzeyini okuyun; gerekirse pazara, paraya ve delile inin.",
            "Yineleyin: pitch'i yeniden yazın, farklı bir açı deneyin, incelemede soru sorun veya gerçek dünya kill-testi çalıştırın.",
          ],
        },
        {
          type: "callout",
          text: "İncelemeyle sohbet asla puanlı bir rapor tüketmez. Tam yeniden puanlamalar ve derin analizler kampanya kotasını kullanır.",
        },
        { type: "h2", text: "Tam geçişte ne alırsınız" },
        {
          type: "ul",
          items: [
            "Karar ve puan (GO / MAYBE / NO-GO) güven ve hedefe göre bantlarla",
            "Talep, ödeme isteği, rekabet ve ulaşılabilir gelir",
            "Risk haritası ve pre-mortem",
            "Alıcı profili ve kanallar",
            "Geçti/kaldı barajlı gerçek dünya test planı (kill-test)",
            "Herkese açık kaynaklardan delil (gönderiler, incelemeler, issue'lar) bağlantılarla",
            "Yineleme alanı: yeni sürümler, açılar ve o fikrin incelemesinde sınırsız soru",
          ],
        },
        {
          type: "p",
          text: "Tam bir geçiş birkaç dakika sürebilir — gerçek web araması ve puanlama, anlık tahmin değil.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Kampanyalar ve fiyatlandırma",
      summary: "Fikir başına tek fiyat; ne açılır ve tam rapor ne sayılır.",
      eyebrow: "Faturalama",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "ödeme",
        "fiyat",
        "aç",
        "abonelik",
        "maliyet",
        "para",
      ],
      blocks: [
        {
          type: "p",
          text: "Hesap ücretsiz. Bir kampanya geçişi tek fikirde tam doğrulama yolunu açar: puanlı raporlar (dahil tavan kadar, varsayılan 10 tam analiz), wedge'ler, kill-test kiti, rakip istihbaratı ve o fikirde sınırsız sohbet. Abonelik yok.",
        },
        { type: "h2", text: "Rapor yuvasını ne tüketir" },
        {
          type: "table",
          headers: ["Eylem", "Tam puanlı rapor kullanır mı?"],
          rows: [
            ["İnceleme hakkında sor / sohbet", "Hayır"],
            ["Raporu oku veya genişlet", "Hayır"],
            ["Yeni sürüm + yeniden puanla", "Evet"],
            ["Derin doğrulama", "Evet (daha ağır çalıştırma)"],
            ["Açı / wedge turnuvası (puanlanan her giriş)", "Evet, analiz başına"],
            ["Görüşme kiti veya istihbarat paketi", "Hayır (açma gerekir, rapor yuvası değil)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Yalnızca tam puanlı analizler bir rapor yuvası tüketir",
            "Dahil raporlar bitince sohbet ve mevcut raporlar açık kalır",
            "Farklı bir fikir kendi kampanya geçişini gerektirir",
          ],
        },
        {
          type: "callout",
          text: "Güncel fiyat ve SSS için Fiyatlandırma'ya bakın. Faturalama sorunları: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Başka analiz çalıştıramıyorum",
      summary:
        "Kampanya kilitli, raporlar bitti veya düğme başka bir nedenle devre dışı.",
      eyebrow: "Sorun giderme",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "bitti",
        "kilitli",
        "engelli",
        "puanlanamıyor",
        "devre dışı",
        "tavan",
      ],
      blocks: [
        {
          type: "p",
          text: "Doğrula, yeniden puanla veya derin doğrulama engelliyse sırayla bunları kontrol edin.",
        },
        {
          type: "ol",
          items: [
            "Kampanya kilitli: bu fikir hiç açılmadı. O fikir için açma / Fiyatlandırma'yı açın.",
            "Raporlar tamam: geçişe dahil tam puanlı analizleri kullandınız. Sohbet ve okuma açık kalır. Farklı bir şeyi doğrulamak için yeni bir fikir başlatın.",
            "İş hâlâ çalışıyor: mevcut analizin bitmesini bekleyin.",
            "Maddi değişiklik yok: yalnızca mevcut raporu anlamak istiyorsanız başka bir çalıştırmayı yakmak yerine Sor (yeniden puanlama yok) kullanın.",
          ],
        },
        {
          type: "callout",
          text: "Hâlâ takıldınız mı? help@validorian.com adresine hesap e-postanız ve fikir başlığıyla yazın.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE ve NO-GO",
      summary: "Her mühür ne demek ve sırada ne yapılmalı.",
      eyebrow: "Kararlar",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "mühür",
        "yetersiz",
        "geçti",
        "kaldı",
        "karar",
      ],
      blocks: [
        {
          type: "p",
          text: "Mühür karardır. Sayı onu destekler ama mühür, belirlediğiniz hedef altında ilerleyip ilerlemeyeceğinizi yanıtlar.",
        },
        {
          type: "ul",
          items: [
            "GO: delil bu çerçeveyi hedefinize göre izlemeyi destekler. Niyetle inşa edin ve test edin. Hazır olduğunuzda planı açın.",
            "MAYBE: karışık veya sınırda. Her şeyi riske atmadan önce fikri iyileştirin, bir kill-testi kanıtlayın veya açıyı değiştirin.",
            "NO-GO: yazıldığı gibi hedefinize zayıf. Sert pivot veya durun. Ölümcül bir uyumsuzluğu cilalamayın.",
            "INSUFFICIENT: dürüst notlandırmak için güven çok düşük. İfadeyi netleştirin, bağlam ekleyin veya daha iyi delilden sonra yeniden çalıştırın.",
          ],
        },
        {
          type: "callout",
          text: "Yan iş ile venture fonu aynı şekilde notlanmaz. Bir hedefte GO eşiğini geçen bir puan başka bir hedefte MAYBE'de kalabilir.",
        },
        {
          type: "p",
          text: "Arayüz etiketleri dilinizde görünebilir (örneğin Türkçe mühürler). Puanlama altında aynı GO / MAYBE / NO-GO kurallarını kullanır.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Raporunuzu okumak",
      summary:
        "Karar yüzeyi, özet, pazar, para, riskler, plan ve delili nasıl tararsınız.",
      eyebrow: "Rapor",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "bölümler",
        "özet",
        "pazar",
        "para",
        "riskler",
        "delil",
      ],
      blocks: [
        {
          type: "p",
          text: "Yalnızca bir kez göz atacaksanız: mühür, bu puan neden, açık sorular, sonra kill-test. Bölümleri yalnızca derinlik gerektiğinde genişletin.",
        },
        {
          type: "ol",
          items: [
            "Mühür ve puan: hedef uyumu ve bu puan neden (sürükleyiciler ve kaldıraçlar).",
            "Özet: ağrı kesiciye karşı vitamin, güçlü yanlar, açık sorular.",
            "Pazar: boyutlandırma, rakipler, kanallar, savunulabilirlik.",
            "Para: birim ekonomisi ve projeksiyonlar (tahmin, vaat değil).",
            "Riskler: kırmızı hücreleri yok saymadan önce matris ve pre-mortem.",
            "Plan: GO veya bir kill-test geçişi inşa yolunu haklı çıkarana kadar kapalı.",
            "Delil: talep okumasının arkasındaki külliyat (makbuz, süs değil).",
          ],
        },
        {
          type: "callout",
          text: "Stüdyoda bölümler daraltılmış kalır ki karar önde gelsin. Yalnızca ihtiyacınız olanı genişletin.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Puanlama nasıl çalışır",
      summary:
        "Kriterler, ağırlıklar ve kapılar. Bir rozet veya ayarlama kafa karıştırırsa isteğe bağlı okuma.",
      eyebrow: "Perdenin arkası",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "kriterler",
        "ağırlıklar",
        "kapılar",
        "bantlar",
        "sistem ayarlamaları",
        "güven",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian'ı kullanmak için bu sayfaya ihtiyacınız yok. Bir puanlama notu, sınır rozeti veya sıkıştırma gizemli göründüğünde açın.",
        },
        {
          type: "p",
          text: "Sade dille: model her faktör için kısa bir gerekçe ve harf notu yazar. Yazılım bu notları sayıya çevirir, hedefinize göre ağırlıklandırır ve tek ölümcül bir zayıflığın başka yerdeki güçlerle ortalanarak silinmemesi için sert kurallar uygular.",
        },
        { type: "h2", text: "On kriter" },
        {
          type: "ul",
          items: [
            "Talep Gücü, Ödeme İsteği, Problem-Çözüm Uyumu",
            "Elde Tutma ve Tekrar, Pazar Zamanlaması, Rekabet Konumu",
            "Farklılaşma / Hendek, Kazanım Kolaylığı, Kurucu Uyumu, Hedef Uyumu",
          ],
        },
        { type: "h2", text: "Nelere güvenmelisiniz" },
        {
          type: "ul",
          items: [
            "Gerçek bağlantı ve oy sayılarıyla toplanmış delil (gönderiler, incelemeler)",
            "Tetiklendiklerinde puanlama notları altında listelenen kapılar ve sıkıştırmalar",
            "Puan GO veya MAYBE çizgisine yakın oturduğunda sınır rozetleri (yeniden çalıştırmalar tersine çevirebilir)",
          ],
        },
        {
          type: "p",
          text: "Pazar boyutlandırma rakamları ve bazı rakip notları aramadan gelen model tahminleridir. Şirketi riske atmadan önce kaynakları kontrol edin.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Puanım neden değişti?",
      summary: "Yeniden çalıştırmalar, hedef değişiklikleri, yeni çerçeve ve normal puanlama gürültüsü.",
      eyebrow: "Sorun giderme",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "varyans",
        "farklı",
        "tersine",
        "sınır",
        "gürültü",
        "yeniden",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Fikir ifadesini, hedefi veya kurucu bağlamını değiştirdiniz: puan değişmeli.",
            "Sınır puanlar: ürün, bir eşiğin çalıştırmadan çalıştırmaya gürültüsü içinde oturduğunuzu işaretler. Bir yeniden çalıştırma, sistemin bozulduğu anlamına gelmeden diğer tarafa düşebilir.",
            "Yeni delil veya kill-test sonucu: saha verisi talep ve kararı dürüstçe hareket ettirebilir.",
            "Derin doğrulama: daha ağır bir geçiş güveni ve notları ayarlayabilir; farklı bir ürün değil, ikinci bir bakış olarak değerlendirin.",
          ],
        },
        {
          type: "callout",
          text: "Çerçeve değişmediyse ve sıçrama vahşi görünüyorsa, fikir başlığı ve sürümlerle help@validorian.com adresine yazın.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Çalışmaları boşa harcamadan yineleyin",
      summary: "Sor, yeni sürümler, açılar ve ne zaman yeniden puanlamalı.",
      eyebrow: "Stüdyo döngüsü",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "sor",
        "sohbet",
        "sürüm",
        "açı",
        "yeniden puanla",
        "çalıştırma",
      ],
      blocks: [
        {
          type: "p",
          text: "Bir çalıştırma (veya tam puanlı rapor) kampanya kotasını yakan derin bir analizdir. Yalnızca mevcut incelemeyi anlamak istediğinizde Sor kullanın.",
        },
        { type: "h2", text: "Ne bir rapor tüketir?" },
        {
          type: "table",
          headers: ["Eylem", "Tam puanlı rapor kullanır mı?"],
          rows: [
            ["Sor (bu analiz hakkında sohbet)", "Hayır"],
            ["Yeni sürüm + yeniden puanla", "Evet"],
            ["Açıları karşılaştır / wedge turnuvası", "Evet, puanlanan açı başına"],
            ["Derin doğrulama", "Evet"],
            ["Kill-test kiti, istihbarat, raporu okuma", "Hayır"],
          ],
        },
        { type: "h2", text: "Sor (yeniden puanlama yok)" },
        {
          type: "p",
          text: "Mevcut rapor üzerinden konuşun: puanlar, rakipler, riskler. Sürüm oluşturmaz ve tam analiz kullanmaz.",
        },
        { type: "h2", text: "Yeni sürüm" },
        {
          type: "p",
          text: "İfadeyi, hedefi veya bağlamı değiştirin, sonra yeniden puanlayın. Her meraktan sonra değil, çerçeve veya delilde gerçek bir değişiklikten sonra kullanın.",
        },
        { type: "h2", text: "Açıları karşılaştır" },
        {
          type: "p",
          text: "Bir açı (bazen alpha veya wedge denir) aynı çekirdek fikrin farklı bir kenarı veya konumlandırmasıdır. Turnuvalar bu kenarlardan birkaçını aynı delil üzerinde bire bir puanlar. Puanlanan her giriş bir rapor yuvası kullanır; bilerek seçin.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-testler ve görüşmeler",
      summary: "İnşa etmeden önce en ucuz gerçek dünya kanıtı.",
      eyebrow: "Saha çalışması",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "görüşme",
        "alıcı",
        "geçti",
        "kaldı",
        "saha",
        "mom-test",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE veya NO-GO çoğu zaman "sunumda daha çok uğraş" demek değildir. "Önceden kayıtlı geçti/kaldı barajıyla alıcılarla konuş" demektir.',
        },
        {
          type: "ul",
          items: [
            "En riskli varsayım: külliyatın çözmediği şey",
            "Kanalıyla birlikte en ucuz test (yaklaşık bir hafta veya daha az)",
            "Sonuçları görmeden önce yazılmış geçti ve öldür eşikleri",
            "Görüşme kiti: kiminle konuşulacağı ve Mom-Test tarzı sorular (geçmiş davranış ve gerçekler, fikriniz hakkında iltifatlar değil)",
          ],
        },
        {
          type: "p",
          text: "Sonucu kaydedin ve yeniden puanlayın ki karar umuttan değil saha verisinden güncellensin.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Derin doğrulama",
      summary: "Daha ağır geçişin bir rapor yuvasına değdiği zaman.",
      eyebrow: "Gelişmiş",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "derin",
        "pahalı",
        "ağır",
      ],
      blocks: [
        {
          type: "p",
          text: "Derin doğrulama isteğe bağlı daha ağır bir analizdir (bağımsız vakalar, ek kontroller). Tam puanlı bir rapor kullanır ve standart bir geçişten daha fazla hesaplama maliyetine sahiptir.",
        },
        {
          type: "ul",
          items: [
            "Fikir ciddiyse ve ikinci, daha sert bir bakış istediğinizde kullanın",
            "Erken taslaklar ve ucuz deneyler için atlayın",
            "Gerçek alıcılarla kill-testin yerini tutmaz",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Dil ve yapay zekâ çıktısı",
      summary: "Arayüz dili ile rapor metni dili.",
      eyebrow: "Yerel ayar",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "türkçe",
        "çeviri",
        "küre",
        "dil",
      ],
      blocks: [
        {
          type: "p",
          text: "Küre seçici arayüz kromunu ayarlar: navigasyon, düğmeler, bölüm başlıkları, karar mühürleri ve etiketler. Dilleri ad veya kodla arayabilirsiniz (örneğin Turkish, Türkçe veya tr).",
        },
        {
          type: "p",
          text: "Yapay zekânın yazdığı gövde metni (özetler, rakip notları, açık sorular) ürettiğiniz veya yeniden puanladığınız anda aktif olan dili izler. Eski İngilizce raporlar yeni dilde yeniden çalıştırana kadar İngilizce kalır.",
        },
        {
          type: "ul",
          items: [
            "Dili istediğiniz zaman üst bardan değiştirin",
            "Saklanan verideki makine kodları (kararlar, kriter adları) puanlama tutarlılığı için İngilizce kalır",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Gizlilik ve fikirleriniz",
      summary: "Stüdyoya koyduklarınızı kim görür.",
      eyebrow: "Güven",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "gizli",
        "veri",
        "güvenlik",
        "paylaş",
        "sır",
      ],
      blocks: [
        {
          type: "p",
          text: "Hesabınızdaki fikirler ve raporlar varsayılan olarak gizlidir. Herkese açık bir akışta yayınlanmazlar.",
        },
        {
          type: "ul",
          items: [
            "Her fikri sahiplenen hesabı siz kontrol edersiniz",
            "Oluşturursanız API anahtarları yalnızca o anahtar veya hesap modeline ait fikirlere erişir",
            "Puanlama ve rapor yazımı için model sağlayıcıları kullanırız: işleme sistemlerine gönderemeyeceğiniz sırları yapıştırmayın",
            "Hesap silme araçları verinizi ürünün hesap akışına göre kaldırır",
          ],
        },
        {
          type: "callout",
          text: "Veri işleme soruları: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Ekipten yardım alın",
      summary: "Bize nasıl ulaşırsınız ve ne eklemelisiniz.",
      eyebrow: "İnsanlar",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "e-posta",
        "destek",
        "iletişim",
        "hata",
        "insan",
      ],
      blocks: [
        {
          type: "p",
          text: "Ürün sorunları, faturalama veya takılan bir kampanya için help@validorian.com adresine yazın. Destek ve İletişim şimdilik aynı gelen kutusuna gider.",
        },
        {
          type: "ul",
          items: [
            "İlgiliyse hesap e-postanızı ve fikir başlığını ekleyin",
            "Arayüz hatalarında ekran görüntüleri yardımcı olur",
            "Asla şifre göndermeyin",
          ],
        },
      ],
    },
  ],
};
