import type { HelpCatalog } from "../types";

export const helpVi: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "Bắt đầu",
      blurb: "Từ ý tưởng đầu tiên đến một lượt xác thực đầy đủ.",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "Thanh toán & chiến dịch",
      blurb: "Bạn trả cho gì, cái gì tốn một báo cáo, và làm gì khi hết lượt.",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "Điểm & verdict",
      blurb: "Con dấu nghĩa là gì và cách đọc báo cáo.",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "Làm việc trong studio",
      blurb: "Hỏi, chấm lại, góc, và kill-test mà không lãng phí lượt.",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "Tài khoản & ngôn ngữ",
      blurb: "Locale, quyền riêng tư, và liên hệ đội ngũ.",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "Chat có tốn một báo cáo đầy đủ không?", slug: "iterate" },
    { q: "Chiến dịch của tôi mở khóa những gì?", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO nghĩa là gì?", slug: "verdicts" },
    { q: "Tôi không chạy thêm phân tích được", slug: "cant-run-analysis" },
    { q: "Vì sao điểm đổi sau khi chạy lại?", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "Xác thực ý tưởng đầu tiên",
      summary:
        "Tạo tài khoản, mô tả ý tưởng, mở khóa chiến dịch, và nhận điểm có căn cứ.",
      eyebrow: "Bắt đầu tại đây",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "đầu tiên",
        "đăng ký",
        "bắt đầu",
        "mở khóa",
        "hướng dẫn",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian là studio xác thực ý tưởng kinh doanh. Bạn mô tả ý tưởng so với mục tiêu của mình, rồi nhận GO / MAYBE / NO-GO có bằng chứng kèm thị trường, tiền, rủi ro, và bước test tiếp theo. Không phải bài động viên.",
        },
        { type: "h2", text: "Lộ trình" },
        {
          type: "ol",
          items: [
            "Tạo tài khoản miễn phí và mở studio.",
            "Mô tả bạn bán gì, cho ai, vì sao bây giờ. Đặt mục tiêu (side hustle, lifestyle, venture, hoặc chưa chắc) để thanh GO khớp với bạn.",
            "Khi sẵn sàng chấm điểm, mở khóa chiến dịch đầy đủ cho ý tưởng đó (một giá mỗi ý tưởng; xem Pricing cho mức hiện tại).",
            "Đọc con dấu và bề mặt quyết định trước, rồi đào sâu thị trường, tiền, và bằng chứng khi cần.",
            "Lặp lại: viết lại pitch, thử góc khác, hỏi về báo cáo, hoặc chạy kill-test ngoài đời.",
          ],
        },
        {
          type: "callout",
          text: "Chat với báo cáo không bao giờ tốn một báo cáo đã chấm. Chấm lại đầy đủ và phân tích sâu dùng hạn mức chiến dịch.",
        },
        { type: "h2", text: "Bạn nhận gì trong một lượt đầy đủ" },
        {
          type: "ul",
          items: [
            "Verdict và điểm (GO / MAYBE / NO-GO) kèm độ tin cậy và dải tương đối theo mục tiêu",
            "Nhu cầu, sẵn sàng trả tiền, cạnh tranh, và doanh thu có thể đạt",
            "Bản đồ rủi ro và pre-mortem",
            "Hồ sơ người mua và kênh",
            "Kế hoạch kiểm chứng thực tế (kill-test) với ngưỡng đạt/trượt",
            "Bằng chứng từ nguồn công khai (post, review, issue) kèm link",
            "Chỗ để lặp: phiên bản mới, góc, và câu hỏi không giới hạn trên báo cáo của ý tưởng đó",
          ],
        },
        {
          type: "p",
          text: "Một lượt đầy đủ có thể mất vài phút — tìm web thật và chấm điểm, không phải đoán tức thì.",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "Chiến dịch và bảng giá",
      summary:
        "Một giá mỗi ý tưởng; mở khóa gì và cái gì tính là báo cáo đầy đủ.",
      eyebrow: "Thanh toán",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "trả",
        "giá",
        "mở khóa",
        "gói đăng ký",
        "chi phí",
        "tiền",
        "chiến dịch",
      ],
      blocks: [
        {
          type: "p",
          text: "Tài khoản miễn phí. Một lượt chiến dịch mở khóa đường xác thực đầy đủ trên một ý tưởng: báo cáo đã chấm (tới hạn mức kèm theo, mặc định 10 phân tích đầy đủ), wedge, bộ kill-test, intel đối thủ, và chat không giới hạn trên ý tưởng đó. Không subscription.",
        },
        { type: "h2", text: "Cái gì tốn một slot báo cáo" },
        {
          type: "table",
          headers: ["Hành động", "Có dùng báo cáo chấm điểm đầy đủ?"],
          rows: [
            ["Hỏi / chat về báo cáo", "Không"],
            ["Đọc hoặc mở rộng báo cáo", "Không"],
            ["Phiên bản mới + chấm lại", "Có"],
            ["Xác thực sâu", "Có (chạy nặng hơn)"],
            ["Tournament góc / wedge (mỗi entrant được chấm)", "Có, mỗi phân tích"],
            ["Bộ phỏng vấn hoặc gói intel", "Không (cần mở khóa, không tốn slot báo cáo)"],
          ],
        },
        {
          type: "ul",
          items: [
            "Chỉ phân tích chấm điểm đầy đủ mới tốn slot báo cáo",
            "Khi hết báo cáo kèm theo, chat và báo cáo hiện có vẫn mở",
            "Ý tưởng khác cần lượt chiến dịch riêng",
          ],
        },
        {
          type: "callout",
          text: "Xem Pricing cho giá live và FAQ. Vấn đề thanh toán: help@validorian.com.",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "Tôi không chạy thêm phân tích được",
      summary:
        "Chiến dịch bị khóa, hết báo cáo, hoặc nút bị tắt vì lý do khác.",
      eyebrow: "Xử lý sự cố",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "hết",
        "khóa",
        "chặn",
        "không chấm được",
        "tắt",
        "giới hạn",
      ],
      blocks: [
        {
          type: "p",
          text: "Nếu Validate, chấm lại, hoặc xác thực sâu bị chặn, kiểm tra theo thứ tự này.",
        },
        {
          type: "ol",
          items: [
            "Chiến dịch bị khóa: ý tưởng này chưa bao giờ được mở khóa. Mở unlock / Pricing cho ý tưởng đó.",
            "Báo cáo đã hết: bạn đã dùng hết phân tích chấm điểm đầy đủ trong lượt. Chat và đọc vẫn mở. Bắt đầu ý tưởng mới để xác thực thứ khác.",
            "Vẫn đang chạy: đợi phân tích hiện tại xong.",
            "Không có thay đổi vật chất: nếu chỉ muốn hiểu báo cáo hiện tại, dùng Hỏi (không chấm lại) thay vì tốn thêm một lượt.",
          ],
        },
        {
          type: "callout",
          text: "Vẫn kẹt? Gửi email help@validorian.com kèm email tài khoản và tiêu đề ý tưởng.",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO, MAYBE, và NO-GO",
      summary: "Mỗi con dấu nghĩa là gì và làm gì tiếp theo.",
      eyebrow: "Verdict",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "con dấu",
        "verdict",
        "đạt",
        "trượt",
        "không đủ",
      ],
      blocks: [
        {
          type: "p",
          text: "Con dấu là lời gọi. Con số hỗ trợ nó, nhưng con dấu trả lời có nên tiến theo mục tiêu bạn đặt không.",
        },
        {
          type: "ul",
          items: [
            "GO: bằng chứng ủng hộ theo đuổi framing này cho mục tiêu của bạn. Build và test có chủ đích. Mở plan khi sẵn sàng.",
            "MAYBE: hỗn hợp hoặc biên. Cải thiện ý tưởng, chứng minh kill-test, hoặc đổi góc trước khi all-in.",
            "NO-GO: như đang viết, yếu so với mục tiêu. Pivot mạnh hoặc dừng. Đừng đánh bóng sự lệch fatal.",
            "INSUFFICIENT: độ tin cậy quá thấp để chấm trung thực. Làm rõ statement, thêm bối cảnh, hoặc chạy lại sau khi có bằng chứng tốt hơn.",
          ],
        },
        {
          type: "callout",
          text: "Side hustle và vòng gọi vốn venture không được chấm giống nhau. Điểm đủ GO cho một mục tiêu có thể nằm ở MAYBE cho mục tiêu khác.",
        },
        {
          type: "p",
          text: "Nhãn UI có thể hiện bằng ngôn ngữ của bạn (ví dụ con dấu tiếng Hàn). Phía dưới, chấm điểm vẫn dùng cùng quy tắc GO / MAYBE / NO-GO.",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "Cách đọc báo cáo",
      summary:
        "Cách quét bề mặt quyết định, brief, thị trường, tiền, rủi ro, plan, và bằng chứng.",
      eyebrow: "Báo cáo",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "giao diện",
        "mục",
        "thị trường",
        "tiền",
        "rủi ro",
        "bằng chứng",
        "báo cáo",
      ],
      blocks: [
        {
          type: "p",
          text: "Nếu chỉ lướt một lần: con dấu, vì sao điểm này, câu hỏi mở, rồi kill-test. Mở chương chỉ khi cần độ sâu.",
        },
        {
          type: "ol",
          items: [
            "Con dấu và điểm: khớp mục tiêu và vì sao điểm này (kéo và đòn bẩy).",
            "Brief: painkiller vs vitamin, điểm mạnh, câu hỏi mở.",
            "Thị trường: định cỡ, đối thủ, kênh, khả năng phòng thủ.",
            "Tiền: unit economics và dự phóng (ước lượng, không phải cam kết).",
            "Rủi ro: ma trận và pre-mortem trước khi bỏ qua ô đỏ.",
            "Plan: khóa đến khi GO hoặc kill-test đạt biện minh đường build.",
            "Bằng chứng: corpus đứng sau đọc nhu cầu (biên lai, không trang trí).",
          ],
        },
        {
          type: "callout",
          text: "Trong studio, các chương thu gọn để quyết định dẫn dắt. Chỉ mở những gì bạn cần.",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "Cách chấm điểm hoạt động",
      summary:
        "Tiêu chí, trọng số, và gate. Đọc tùy chọn nếu badge hoặc điều chỉnh gây bối rối.",
      eyebrow: "Bên dưới nắp máy",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "tiêu chí",
        "trọng số",
        "dải",
        "điều chỉnh hệ thống",
        "tin cậy",
      ],
      blocks: [
        {
          type: "p",
          text: "Bạn không cần trang này để dùng Validorian. Mở khi ghi chú chấm điểm, badge biên, hoặc clamp trông khó hiểu.",
        },
        {
          type: "p",
          text: "Nói đơn giản: model viết lý do ngắn và điểm chữ cho từng yếu tố. Phần mềm đổi các điểm chữ thành số, trọng số theo mục tiêu của bạn, và áp quy tắc cứng để một lỗ fatal không bị trung bình hóa bởi điểm mạnh chỗ khác.",
        },
        { type: "h2", text: "Mười tiêu chí" },
        {
          type: "ul",
          items: [
            "Demand Strength, Willingness to Pay, Problem-Solution Fit",
            "Retention & Recurrence, Market Timing, Competitive Position",
            "Differentiation / Moat, Acquisition Ease, Founder Fit, Goal Fit",
          ],
        },
        { type: "h2", text: "Bạn nên tin gì" },
        {
          type: "ul",
          items: [
            "Bằng chứng lấy về (post, review) với link thật và số vote",
            "Gate và clamp liệt kê trong ghi chú chấm điểm khi chúng kích hoạt",
            "Badge biên khi điểm nằm gần đường GO hoặc MAYBE (chạy lại có thể lật)",
          ],
        },
        {
          type: "p",
          text: "Số định cỡ thị trường và một số ghi chú đối thủ là ước lượng model từ tìm kiếm. Kiểm tra nguồn trước khi đặt cược công ty.",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "Vì sao điểm của tôi đổi?",
      summary: "Chạy lại, đổi mục tiêu, framing mới, và nhiễu chấm điểm bình thường.",
      eyebrow: "Xử lý sự cố",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "biến thiên",
        "khác",
        "lật",
        "nhiễu",
        "chạy lại",
        "đổi điểm",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "Bạn đổi statement ý tưởng, mục tiêu, hoặc bối cảnh founder: điểm nên đổi.",
            "Điểm biên: sản phẩm đánh dấu khi bạn nằm trong nhiễu run-to-run của một ngưỡng. Chạy lại có thể rơi sang phía kia mà không có nghĩa hệ thống hỏng.",
            "Bằng chứng mới hoặc kết quả kill-test: dữ liệu thực địa có thể dịch nhu cầu và verdict một cách trung thực.",
            "Xác thực sâu: lượt nặng hơn có thể điều chỉnh độ tin cậy và ghi chú; coi như cái nhìn thứ hai, không phải sản phẩm khác.",
          ],
        },
        {
          type: "callout",
          text: "Nếu framing không đổi mà nhảy có vẻ hoang, gửi email help@validorian.com kèm tiêu đề ý tưởng và các phiên bản.",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "Lặp lại mà không lãng phí lượt",
      summary: "Hỏi, phiên bản mới, góc, và khi nào chấm lại.",
      eyebrow: "Vòng studio",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "hỏi",
        "phiên bản",
        "góc",
        "chấm lại",
        "lượt",
        "lặp",
      ],
      blocks: [
        {
          type: "p",
          text: "Một lượt (hoặc báo cáo chấm điểm đầy đủ) là phân tích sâu tốn hạn mức chiến dịch. Dùng Hỏi khi bạn chỉ muốn hiểu báo cáo hiện tại.",
        },
        { type: "h2", text: "Cái gì tốn một báo cáo?" },
        {
          type: "table",
          headers: ["Hành động", "Có dùng báo cáo chấm điểm đầy đủ?"],
          rows: [
            ["Hỏi (chat về phân tích này)", "Không"],
            ["Phiên bản mới + chấm lại", "Có"],
            ["So góc / tournament wedge", "Có, mỗi góc được chấm"],
            ["Xác thực sâu", "Có"],
            ["Bộ kill-test, intel, đọc báo cáo", "Không"],
          ],
        },
        { type: "h2", text: "Hỏi (không chấm lại)" },
        {
          type: "p",
          text: "Bàn về báo cáo hiện tại: điểm, đối thủ, rủi ro. Không tạo phiên bản và không dùng một phân tích đầy đủ.",
        },
        { type: "h2", text: "Phiên bản mới" },
        {
          type: "p",
          text: "Đổi statement, mục tiêu, hoặc bối cảnh, rồi chấm lại. Dùng sau thay đổi thật về framing hoặc bằng chứng, không phải sau mỗi tò mò.",
        },
        { type: "h2", text: "So góc" },
        {
          type: "p",
          text: "Một góc (đôi khi gọi alpha hoặc wedge) là edge hoặc định vị khác của cùng ý tưởng lõi. Tournament chấm vài edge đó đối đầu trên cùng bằng chứng. Mỗi entrant được chấm tốn một slot báo cáo, nên chọn có chủ đích.",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "Kill-test và phỏng vấn",
      summary: "Bằng chứng thực tế rẻ nhất trước khi build.",
      eyebrow: "Việc thực địa",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "phỏng vấn",
        "người mua",
        "đạt",
        "trượt",
        "thực địa",
        "Mom-Test",
      ],
      blocks: [
        {
          type: "p",
          text: 'MAYBE hoặc NO-GO thường không phải "cố hơn trong deck." Mà là "nói với người mua với ngưỡng đạt/trượt đã đăng ký trước."',
        },
        {
          type: "ul",
          items: [
            "Giả định rủi ro nhất: điều corpus chưa giải quyết",
            "Test rẻ nhất (khoảng một tuần hoặc ít hơn) kèm kênh",
            "Ngưỡng đạt và kill viết trước khi bạn thấy kết quả",
            "Bộ phỏng vấn: nói với ai và câu hỏi kiểu Mom-Test (hành vi quá khứ và sự kiện, không phải lời khen về ý tưởng của bạn)",
          ],
        },
        {
          type: "p",
          text: "Ghi kết quả và chấm lại để verdict cập nhật từ dữ liệu thực địa, không phải hy vọng.",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "Xác thực sâu",
      summary: "Khi lượt nặng hơn đáng một slot báo cáo.",
      eyebrow: "Nâng cao",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "sâu",
        "nặng",
        "tốn",
        "xác thực sâu",
      ],
      blocks: [
        {
          type: "p",
          text: "Xác thực sâu là phân tích nặng tùy chọn (case độc lập, kiểm tra thêm). Nó dùng một báo cáo chấm điểm đầy đủ và tốn compute nhiều hơn lượt chuẩn.",
        },
        {
          type: "ul",
          items: [
            "Dùng khi ý tưởng nghiêm túc và bạn muốn cái nhìn thứ hai, cứng hơn",
            "Bỏ qua với draft sớm và thử nghiệm rẻ",
            "Nó không thay thế kill-test với người mua thật",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "Ngôn ngữ và output AI",
      summary: "Ngôn ngữ UI so với ngôn ngữ văn xuôi báo cáo.",
      eyebrow: "Locale",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "ngôn ngữ",
        "tiếng việt",
        "dịch",
        "địa phương",
      ],
      blocks: [
        {
          type: "p",
          text: "Bộ chuyển quả địa cầu đặt chrome UI: nav, nút, tiêu đề mục, con dấu verdict, và nhãn. Bạn có thể tìm ngôn ngữ theo tên hoặc mã (ví dụ Vietnamese, Tiếng Việt, hoặc vi).",
        },
        {
          type: "p",
          text: "Văn bản body do AI viết (tóm tắt, ghi chú đối thủ, câu hỏi mở) theo ngôn ngữ đang active khi bạn generate hoặc chấm lại. Báo cáo tiếng Anh cũ vẫn tiếng Anh cho đến khi bạn chạy lại dưới locale mới.",
        },
        {
          type: "ul",
          items: [
            "Đổi ngôn ngữ bất cứ lúc nào từ header",
            "Mã máy trong dữ liệu lưu (verdict, tên tiêu chí) giữ tiếng Anh để chấm điểm nhất quán",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "Quyền riêng tư và ý tưởng của bạn",
      summary: "Ai thấy những gì bạn đưa vào studio.",
      eyebrow: "Tin cậy",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "riêng tư",
        "dữ liệu",
        "bảo mật",
        "chia sẻ",
        "bí mật",
      ],
      blocks: [
        {
          type: "p",
          text: "Ý tưởng và báo cáo trong tài khoản của bạn riêng tư theo mặc định. Chúng không được đăng trên feed công khai.",
        },
        {
          type: "ul",
          items: [
            "Bạn kiểm soát tài khoản sở hữu mỗi ý tưởng",
            "API key, nếu bạn tạo, chỉ truy cập ý tưởng theo model key hoặc tài khoản đó",
            "Chúng tôi dùng nhà cung cấp model để chấm và viết báo cáo: đừng dán bí mật bạn không thể gửi tới hệ thống xử lý",
            "Công cụ xóa tài khoản gỡ dữ liệu của bạn theo luồng tài khoản của sản phẩm",
          ],
        },
        {
          type: "callout",
          text: "Câu hỏi về xử lý dữ liệu: help@validorian.com.",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "Nhận trợ giúp từ đội ngũ",
      summary: "Cách liên hệ chúng tôi và nên kèm gì.",
      eyebrow: "Con người",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "hỗ trợ",
        "liên hệ",
        "lỗi",
        "người thật",
      ],
      blocks: [
        {
          type: "p",
          text: "Với vấn đề sản phẩm, thanh toán, hoặc chiến dịch kẹt, gửi email help@validorian.com. Support và Contact hiện cùng một hộp thư.",
        },
        {
          type: "ul",
          items: [
            "Kèm email tài khoản và tiêu đề ý tưởng nếu liên quan",
            "Screenshot giúp với bug UI",
            "Không bao giờ gửi mật khẩu",
          ],
        },
      ],
    },
  ],
};
