import type { HelpCatalog } from "../types";

export const helpZh: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "快速上手",
      blurb: "从第一个想法到完整验证流程。",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "计费与活动",
      blurb: "你为哪些内容付费、什么会消耗报告额度，以及额度用尽时怎么办。",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "评分与判定",
      blurb: "印章含义是什么，以及如何阅读报告。",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "在工作室中操作",
      blurb: "提问、重新评分、角度对比与淘汰测试，不浪费运行次数。",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "账户与语言",
      blurb: "语言环境、隐私，以及如何联系团队。",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "对话会消耗完整报告吗？", slug: "iterate" },
    { q: "我的活动解锁了什么？", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO 分别是什么意思？", slug: "verdicts" },
    { q: "我无法再运行分析", slug: "cant-run-analysis" },
    { q: "为什么重新运行后分数变了？", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "验证你的第一个想法",
      summary: "创建账户、描述想法、解锁活动，并获得有依据的评分。",
      eyebrow: "从这里开始",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "上手",
        "注册",
        "解锁",
        "入门",
        "验证",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian 是商业验证工作室。你对照自己的目标描述一个想法，然后得到有证据支撑的 GO / MAYBE / NO-GO，涵盖市场、商业、风险与下一步测试。不是打气话术。",
        },
        { type: "h2", text: "路径" },
        {
          type: "ol",
          items: [
            "创建免费账户并打开工作室。",
            "说明你提供什么、面向谁、以及为什么是现在。设定你的目标（副业、生活方式、创业融资，或尚未确定），这样 GO 的门槛会与你匹配。",
            "准备好评分时，为该想法解锁完整活动（每个想法一次价格；当前金额见定价页）。",
            "先看印章与决策摘要，再按需深入市场、商业与证据。",
            "迭代：改写表述、尝试不同角度、就评审内容提问，或运行真实世界的淘汰测试。",
          ],
        },
        {
          type: "callout",
          text: "与评审对话永远不会消耗已评分报告。完整重新评分与深度分析会使用活动额度。",
        },
        { type: "h2", text: "完整流程你会得到什么" },
        {
          type: "ul",
          items: [
            "判定与分数（GO / MAYBE / NO-GO），含置信度及相对目标的分数区间",
            "需求、付费意愿、竞争与可获得收入",
            "风险地图与事前验尸（pre-mortem）",
            "买家画像与渠道",
            "真实世界测试计划（淘汰测试），含通过/失败门槛",
            "来自公开来源的证据（帖子、评价、问题），附链接",
            "迭代空间：新版本、角度，以及对该想法评审的无限提问",
          ],
        },
        {
          type: "p",
          text: "完整流程可能需要几分钟——真实的网页检索与评分，不是瞬间猜测。",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "活动与定价",
      summary: "每个想法一次价格；解锁内容以及什么算作完整报告。",
      eyebrow: "计费",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "付费",
        "价格",
        "解锁",
        "订阅",
        "费用",
        "活动",
      ],
      blocks: [
        {
          type: "p",
          text: "账户免费。活动通行证为一个想法解锁完整验证路径：已评分报告（最多包含额度，默认 10 次完整分析）、切入点、淘汰测试工具包、竞品情报，以及对该想法的无限对话。无订阅。",
        },
        { type: "h2", text: "什么会消耗报告名额" },
        {
          type: "table",
          headers: ["操作", "是否使用完整已评分报告？"],
          rows: [
            ["就评审提问 / 对话", "否"],
            ["阅读或展开报告", "否"],
            ["新版本 + 重新评分", "是"],
            ["深度验证", "是（更重的运行）"],
            ["角度 / 切入点锦标赛（每个已评分参赛项）", "是，按每次分析计"],
            ["访谈工具包或情报包", "否（需解锁，不占报告名额）"],
          ],
        },
        {
          type: "ul",
          items: [
            "只有完整已评分分析会消耗报告名额",
            "包含报告用尽后，对话与既有报告仍可使用",
            "不同想法需要各自的活动通行证",
          ],
        },
        {
          type: "callout",
          text: "实时价格与常见问题见定价页。计费问题：help@validorian.com。",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "我无法再运行分析",
      summary: "活动未解锁、报告已用尽，或按钮因其他原因被禁用。",
      eyebrow: "故障排查",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "用尽",
        "锁定",
        "无法评分",
        "禁用",
        "额度",
      ],
      blocks: [
        {
          type: "p",
          text: "若「验证」「重新评分」或「深度验证」被阻止，请按以下顺序检查。",
        },
        {
          type: "ol",
          items: [
            "活动已锁定：该想法从未解锁。打开该想法的解锁 / 定价。",
            "报告已用完：你已用尽通行证包含的全部已评分分析。对话与阅读仍可用。要验证其他内容，请新建想法。",
            "任务仍在运行：等待当前分析完成。",
            "没有实质变更：若你只想理解当前报告，请使用「提问」（不重新评分），而不是再消耗一次运行。",
          ],
        },
        {
          type: "callout",
          text: "仍无法解决？请发邮件至 help@validorian.com，并附上账户邮箱与想法标题。",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO、MAYBE 与 NO-GO",
      summary: "每个印章的含义以及下一步该做什么。",
      eyebrow: "判定",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "印章",
        "判定",
        "通过",
        "失败",
        "不足",
      ],
      blocks: [
        {
          type: "p",
          text: "印章是最终结论。数字是支撑，但印章回答的是：在你设定的目标下，是否应继续推进。",
        },
        {
          type: "ul",
          items: [
            "GO：证据支持在你的目标下按此表述推进。带着意图去构建与测试。准备好时打开计划。",
            "MAYBE：信号混杂或处于边缘。先改进想法、用淘汰测试证明，或换角度，再全力投入。",
            "NO-GO：按当前写法，相对你的目标偏弱。大幅转向或停手。不要打磨致命错配。",
            "INSUFFICIENT：置信度过低，无法诚实打分。澄清表述、补充背景，或在证据更充分后再运行。",
          ],
        },
        {
          type: "callout",
          text: "副业与创业融资的评分标准不同。对某一目标达到 GO 的分数，对另一目标可能落在 MAYBE。",
        },
        {
          type: "p",
          text: "界面标签可用你的语言显示（例如中文印章）。底层评分仍遵循相同的 GO / MAYBE / NO-GO 规则。",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "阅读你的报告",
      summary: "如何浏览决策摘要、简报、市场、商业、风险、计划与证据。",
      eyebrow: "报告",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "界面",
        "章节",
        "市场",
        "商业",
        "风险",
        "计划",
        "证据",
      ],
      blocks: [
        {
          type: "p",
          text: "如果只快速浏览一次：印章、为何是这个分数、未决问题，然后是淘汰测试。只有需要深度时再展开各章节。",
        },
        {
          type: "ol",
          items: [
            "印章与分数：目标契合度及为何是此分数（拖累与杠杆）。",
            "简报：止痛药 vs 维生素、优势、未决问题。",
            "市场：规模、竞品、渠道、可防御性。",
            "商业：单位经济与预测（估计，不是承诺）。",
            "风险：矩阵与事前验尸——在忽略红色格子之前先看清楚。",
            "计划：在 GO 或淘汰测试通过证明值得构建路径之前保持锁定。",
            "证据：支撑需求判断的语料（收据，不是装饰）。",
          ],
        },
        {
          type: "callout",
          text: "在工作室中，章节默认折叠，让决策先行。只展开你需要的部分。",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "评分如何运作",
      summary: "标准、权重与闸门。若某个徽章或调整让你困惑，可选择性阅读。",
      eyebrow: "底层原理",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "标准",
        "权重",
        "闸门",
        "区间",
        "系统调整",
        "可信",
      ],
      blocks: [
        {
          type: "p",
          text: "使用 Validorian 不必读本页。当评分说明、边缘徽章或钳制看起来莫名其妙时再打开。",
        },
        {
          type: "p",
          text: "通俗地说：模型为每个因子写简短理由与字母等级；软件把等级转成数字，按你的目标加权，并应用硬规则，使一处致命缺陷无法被其他优势平均掉。",
        },
        { type: "h2", text: "十项标准" },
        {
          type: "ul",
          items: [
            "需求强度、付费意愿、问题—方案契合度",
            "留存与复购、市场时机、竞争地位",
            "差异化 / 护城河、获客难度、创始人契合度、目标契合度",
          ],
        },
        { type: "h2", text: "你应信任什么" },
        {
          type: "ul",
          items: [
            "抓取的证据（帖子、评价），带真实链接与投票数",
            "触发时在评分说明中列出的闸门与钳制",
            "分数贴近 GO 或 MAYBE 线时的边缘徽章（重新运行可能翻转）",
          ],
        },
        {
          type: "p",
          text: "市场规模数字与部分竞品备注是基于搜索的模型估计。在押上公司之前请核对来源。",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "为什么我的分数变了？",
      summary: "重新运行、目标变更、新表述，以及正常的评分波动。",
      eyebrow: "故障排查",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "波动",
        "变化",
        "翻转",
        "边缘",
        "噪声",
        "重新运行",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "你改了想法表述、目标或创始人背景：分数理应变化。",
            "边缘分数：产品会标记你处于阈值附近、存在运行间噪声的区间。重新运行落到另一侧，并不等于系统坏了。",
            "新证据或淘汰测试结果：实地数据可以诚实地推动需求判断与判定。",
            "深度验证：更重的流程可能调整置信度与说明；把它当作第二遍审视，而不是另一个产品。",
          ],
        },
        {
          type: "callout",
          text: "若表述未变但跳变异常，请发邮件至 help@validorian.com，并附上想法标题与版本。",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "迭代而不浪费运行次数",
      summary: "提问、新版本、角度，以及何时重新评分。",
      eyebrow: "工作室循环",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "提问",
        "对话",
        "版本",
        "角度",
        "切入点",
        "重新评分",
        "运行",
      ],
      blocks: [
        {
          type: "p",
          text: "一次运行（或完整已评分报告）是会消耗活动额度的深度分析。若只想理解当前评审，请使用「提问」。",
        },
        { type: "h2", text: "什么会消耗报告？" },
        {
          type: "table",
          headers: ["操作", "是否使用完整已评分报告？"],
          rows: [
            ["提问（就本次分析对话）", "否"],
            ["新版本 + 重新评分", "是"],
            ["比较角度 / 切入点锦标赛", "是，按每个已评分角度计"],
            ["深度验证", "是"],
            ["淘汰测试工具包、情报、阅读报告", "否"],
          ],
        },
        { type: "h2", text: "提问（不重新评分）" },
        {
          type: "p",
          text: "围绕当前报告讨论：分数、竞品、风险。不创建版本，也不使用完整分析。",
        },
        { type: "h2", text: "新版本" },
        {
          type: "p",
          text: "更改表述、目标或背景后重新评分。在框架或证据有真实变化后再用，而不是每次好奇都跑一次。",
        },
        { type: "h2", text: "比较角度" },
        {
          type: "p",
          text: "角度（有时也称 alpha 或 wedge / 切入点）是同一核心想法的不同切面或定位。锦标赛在同一证据上对若干切面进行正面对比评分。每个已评分参赛项占用一个报告名额，请有意识地选择。",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "淘汰测试与访谈",
      summary: "在动手构建之前，成本最低的真实世界证明。",
      eyebrow: "实地工作",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "访谈",
        "买家",
        "通过",
        "失败",
        "实地",
        "淘汰测试",
      ],
      blocks: [
        {
          type: "p",
          text: "MAYBE 或 NO-GO 往往不是「在 pitch 里再努力一点」，而是「带着事先登记的通过/失败门槛去和买家谈」。",
        },
        {
          type: "ul",
          items: [
            "风险最大的假设：语料未能结算的部分",
            "最便宜的测试（大约一周或更短）及渠道",
            "在看到结果之前写好的通过与淘汰门槛",
            "访谈工具包：该找谁谈，以及 Mom-Test 风格问题（关注过去行为与事实，而非对你想法的恭维）",
          ],
        },
        {
          type: "p",
          text: "记录结果并重新评分，让判定来自实地数据，而不是希望。",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "深度验证",
      summary: "何时值得用一次报告名额做更重的流程。",
      eyebrow: "进阶",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "深度",
        "多空",
        "昂贵",
        "进阶",
      ],
      blocks: [
        {
          type: "p",
          text: "深度验证是可选的更重分析（独立论证、额外检查）。它使用一次完整已评分报告，计算成本高于标准流程。",
        },
        {
          type: "ul",
          items: [
            "在想法认真、且你想要第二遍更严苛审视时使用",
            "早期草稿与廉价实验可跳过",
            "它不能替代与真实买家进行的淘汰测试",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "语言与 AI 输出",
      summary: "界面语言 vs 报告正文语言。",
      eyebrow: "语言环境",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "语言",
        "翻译",
        "中文",
        "界面",
        "本地化",
      ],
      blocks: [
        {
          type: "p",
          text: "地球仪切换器设置界面外壳：导航、按钮、章节标题、判定印章与标签。你可按名称或代码搜索语言（例如 Chinese、中文，或 zh）。",
        },
        {
          type: "p",
          text: "AI 撰写的正文（摘要、竞品备注、未决问题）跟随你生成或重新评分时的活跃语言。旧的英文报告在你以新语言环境重新运行之前会保持英文。",
        },
        {
          type: "ul",
          items: [
            "随时可从页眉切换语言",
            "存储数据中的机器码（判定、标准名称）保持英文，以确保评分一致性",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "隐私与你的想法",
      summary: "谁能看到你在工作室中输入的内容。",
      eyebrow: "信任",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "隐私",
        "数据",
        "安全",
        "分享",
        "机密",
      ],
      blocks: [
        {
          type: "p",
          text: "账户中的想法与报告默认私密。它们不会发布在公开信息流上。",
        },
        {
          type: "ul",
          items: [
            "你控制拥有每个想法的账户",
            "若你创建 API 密钥，它们仅按该密钥或账户模型访问想法",
            "我们使用模型提供方进行评分与撰写报告：请勿粘贴你不能承担发送到处理系统的机密",
            "删除账户工具会按产品的账户流程移除你的数据",
          ],
        },
        {
          type: "callout",
          text: "关于数据处理的问题：help@validorian.com。",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "向团队寻求帮助",
      summary: "如何联系我们，以及应附上哪些信息。",
      eyebrow: "人工支持",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "邮件",
        "支持",
        "联系",
        "缺陷",
        "人工",
      ],
      blocks: [
        {
          type: "p",
          text: "产品问题、计费或卡住的活动，请发邮件至 help@validorian.com。目前支持与联系入口均指向同一收件箱。",
        },
        {
          type: "ul",
          items: [
            "请附上账户邮箱，以及相关时的想法标题",
            "界面缺陷附截图会有帮助",
            "切勿发送密码",
          ],
        },
      ],
    },
  ],
};
