import type { HelpCatalog } from "../types";

export const helpZht: HelpCatalog = {
  sections: [
    {
      id: "start",
      title: "快速上手",
      blurb: "從第一個想法到完整驗證流程。",
      entrySlug: "getting-started",
    },
    {
      id: "billing",
      title: "計費與活動",
      blurb: "你為哪些內容付費、什麼會消耗報告額度，以及額度用盡時怎麼辦。",
      entrySlug: "campaigns-and-pricing",
    },
    {
      id: "scoring",
      title: "評分與判定",
      blurb: "印章含義是什麼，以及如何閱讀報告。",
      entrySlug: "verdicts",
    },
    {
      id: "studio",
      title: "在工作室中操作",
      blurb: "提問、重新評分、角度對比與淘汰測試，不浪費執行次數。",
      entrySlug: "iterate",
    },
    {
      id: "account",
      title: "帳戶與語言",
      blurb: "語言環境、隱私，以及如何聯絡團隊。",
      entrySlug: "language",
    },
  ],
  faq: [
    { q: "對話會消耗完整報告嗎？", slug: "iterate" },
    { q: "我的活動解鎖了什麼？", slug: "campaigns-and-pricing" },
    { q: "GO / MAYBE / NO-GO 分別是什麼意思？", slug: "verdicts" },
    { q: "我無法再執行分析", slug: "cant-run-analysis" },
    { q: "為什麼重新執行後分數變了？", slug: "why-score-changed" },
  ],
  articles: [
    {
      slug: "getting-started",
      section: "start",
      title: "驗證你的第一個想法",
      summary: "建立帳戶、描述想法、解鎖活動，並獲得有依據的評分。",
      eyebrow: "從這裡開始",
      tags: [
        "first",
        "signup",
        "begin",
        "unlock",
        "onboarding",
        "上手",
        "註冊",
        "解鎖",
        "入門",
        "驗證",
      ],
      blocks: [
        {
          type: "p",
          text: "Validorian 是商業驗證工作室。你對照自己的目標描述一個想法，然後得到有證據支撐的 GO / MAYBE / NO-GO，涵蓋市場、商業、風險與下一步測試。不是打氣話術。",
        },
        { type: "h2", text: "路徑" },
        {
          type: "ol",
          items: [
            "建立免費帳戶並開啟工作室。",
            "說明你提供什麼、面向誰、以及為什麼是現在。設定你的目標（副業、生活方式、創業融資，或尚未確定），這樣 GO 的門檻會與你匹配。",
            "準備好評分時，為該想法解鎖完整活動（每個想法一次價格；目前金額見定價頁）。",
            "先看印章與決策摘要，再按需深入市場、商業與證據。",
            "迭代：改寫表述、嘗試不同角度、就評審內容提問，或執行真實世界的淘汰測試。",
          ],
        },
        {
          type: "callout",
          text: "與評審對話永遠不會消耗已評分報告。完整重新評分與深度分析會使用活動額度。",
        },
        { type: "h2", text: "完整流程你會得到什麼" },
        {
          type: "ul",
          items: [
            "判定與分數（GO / MAYBE / NO-GO），含信心度及相對目標的分數區間",
            "需求、付費意願、競爭與可獲得收入",
            "風險地圖與事前驗屍（pre-mortem）",
            "買家畫像與通路",
            "真實世界測試計畫（淘汰測試），含通過/失敗門檻",
            "來自公開來源的證據（貼文、評價、問題），附連結",
            "迭代空間：新版本、角度，以及對該想法評審的無限提問",
          ],
        },
        {
          type: "p",
          text: "完整流程可能需要幾分鐘——真實的網頁檢索與評分，不是瞬間猜測。",
        },
      ],
    },
    {
      slug: "campaigns-and-pricing",
      section: "billing",
      title: "活動與定價",
      summary: "每個想法一次價格；解鎖內容以及什麼算作完整報告。",
      eyebrow: "計費",
      tags: [
        "pay",
        "price",
        "unlock",
        "subscription",
        "cost",
        "money",
        "stripe",
        "29",
        "付費",
        "價格",
        "解鎖",
        "訂閱",
        "費用",
        "活動",
      ],
      blocks: [
        {
          type: "p",
          text: "帳戶免費。活動通行證為一個想法解鎖完整驗證路徑：已評分報告（最多包含額度，預設 10 次完整分析）、切入點、淘汰測試工具包、競品情報，以及對該想法的無限對話。無訂閱。",
        },
        { type: "h2", text: "什麼會消耗報告名額" },
        {
          type: "table",
          headers: ["操作", "是否使用完整已評分報告？"],
          rows: [
            ["就評審提問 / 對話", "否"],
            ["閱讀或展開報告", "否"],
            ["新版本 + 重新評分", "是"],
            ["深度驗證", "是（更重的執行）"],
            ["角度 / 切入點錦標賽（每個已評分參賽項）", "是，按每次分析計"],
            ["訪談工具包或情報包", "否（需解鎖，不占報告名額）"],
          ],
        },
        {
          type: "ul",
          items: [
            "只有完整已評分分析會消耗報告名額",
            "包含報告用盡後，對話與既有報告仍可使用",
            "不同想法需要各自的活動通行證",
          ],
        },
        {
          type: "callout",
          text: "即時價格與常見問題見定價頁。計費問題：help@validorian.com。",
        },
      ],
    },
    {
      slug: "cant-run-analysis",
      section: "billing",
      title: "我無法再執行分析",
      summary: "活動未解鎖、報告已用盡，或按鈕因其他原因被停用。",
      eyebrow: "疑難排解",
      tags: [
        "exhausted",
        "locked",
        "blocked",
        "can't score",
        "disabled",
        "cap",
        "用盡",
        "鎖定",
        "無法評分",
        "停用",
        "額度",
      ],
      blocks: [
        {
          type: "p",
          text: "若「驗證」「重新評分」或「深度驗證」被阻止，請按以下順序檢查。",
        },
        {
          type: "ol",
          items: [
            "活動已鎖定：該想法從未解鎖。開啟該想法的解鎖 / 定價。",
            "報告已用完：你已用盡通行證包含的全部已評分分析。對話與閱讀仍可用。要驗證其他內容，請新建想法。",
            "任務仍在執行：等待目前分析完成。",
            "沒有實質變更：若你只想理解目前報告，請使用「提問」（不重新評分），而不是再消耗一次執行。",
          ],
        },
        {
          type: "callout",
          text: "仍無法解決？請寫信至 help@validorian.com，並附上帳戶信箱與想法標題。",
        },
      ],
    },
    {
      slug: "verdicts",
      section: "scoring",
      title: "GO、MAYBE 與 NO-GO",
      summary: "每個印章的含義以及下一步該做什麼。",
      eyebrow: "判定",
      tags: [
        "stamp",
        "maybe",
        "nogo",
        "no-go",
        "insufficient",
        "pass",
        "fail",
        "印章",
        "判定",
        "通過",
        "失敗",
        "不足",
      ],
      blocks: [
        {
          type: "p",
          text: "印章是最終結論。數字是支撐，但印章回答的是：在你設定的目標下，是否應繼續推進。",
        },
        {
          type: "ul",
          items: [
            "GO：證據支持在你的目標下按此表述推進。帶著意圖去建構與測試。準備好時開啟計畫。",
            "MAYBE：訊號混雜或處於邊緣。先改進想法、用淘汰測試證明，或換角度，再全力投入。",
            "NO-GO：按目前寫法，相對你的目標偏弱。大幅轉向或停手。不要打磨致命錯配。",
            "INSUFFICIENT：信心度過低，無法誠實打分。澄清表述、補充背景，或在證據更充分後再執行。",
          ],
        },
        {
          type: "callout",
          text: "副業與創業融資的評分標準不同。對某一目標達到 GO 的分數，對另一目標可能落在 MAYBE。",
        },
        {
          type: "p",
          text: "介面標籤可用你的語言顯示（例如繁體中文印章）。底層評分仍遵循相同的 GO / MAYBE / NO-GO 規則。",
        },
      ],
    },
    {
      slug: "reading-the-report",
      section: "scoring",
      title: "閱讀你的報告",
      summary: "如何瀏覽決策摘要、簡報、市場、商業、風險、計畫與證據。",
      eyebrow: "報告",
      tags: [
        "ui",
        "sections",
        "brief",
        "market",
        "money",
        "risks",
        "plan",
        "evidence",
        "介面",
        "章節",
        "市場",
        "商業",
        "風險",
        "計畫",
        "證據",
      ],
      blocks: [
        {
          type: "p",
          text: "如果只快速瀏覽一次：印章、為何是這個分數、未決問題，然後是淘汰測試。只有需要深度時再展開各章節。",
        },
        {
          type: "ol",
          items: [
            "印章與分數：目標契合度及為何是此分數（拖累與槓桿）。",
            "簡報：止痛藥 vs 維生素、優勢、未決問題。",
            "市場：規模、競品、通路、可防禦性。",
            "商業：單位經濟與預測（估計，不是承諾）。",
            "風險：矩陣與事前驗屍——在忽略紅色格子之前先看清楚。",
            "計畫：在 GO 或淘汰測試通過證明值得建構路徑之前保持鎖定。",
            "證據：支撐需求判斷的語料（收據，不是裝飾）。",
          ],
        },
        {
          type: "callout",
          text: "在工作室中，章節預設摺疊，讓決策先行。只展開你需要的部分。",
        },
      ],
    },
    {
      slug: "how-scoring-works",
      section: "scoring",
      title: "評分如何運作",
      summary: "標準、權重與閘門。若某個徽章或調整讓你困惑，可選擇性閱讀。",
      eyebrow: "底層原理",
      tags: [
        "criteria",
        "weights",
        "gates",
        "bands",
        "system adjustments",
        "trust",
        "標準",
        "權重",
        "閘門",
        "區間",
        "系統調整",
        "可信",
      ],
      blocks: [
        {
          type: "p",
          text: "使用 Validorian 不必讀本頁。當評分說明、邊緣徽章或鉗制看起來莫名其妙時再開啟。",
        },
        {
          type: "p",
          text: "通俗地說：模型為每個因子寫簡短理由與字母等級；軟體把等級轉成數字，按你的目標加權，並套用硬規則，使一處致命缺陷無法被其他優勢平均掉。",
        },
        { type: "h2", text: "十項標準" },
        {
          type: "ul",
          items: [
            "需求強度、付費意願、問題—方案契合度",
            "留存與復購、市場時機、競爭地位",
            "差異化 / 護城河、獲客難度、創辦人契合度、目標契合度",
          ],
        },
        { type: "h2", text: "你應信任什麼" },
        {
          type: "ul",
          items: [
            "擷取的證據（貼文、評價），帶真實連結與投票數",
            "觸發時在評分說明中列出的閘門與鉗制",
            "分數貼近 GO 或 MAYBE 線時的邊緣徽章（重新執行可能翻轉）",
          ],
        },
        {
          type: "p",
          text: "市場規模數字與部分競品備註是基於搜尋的模型估計。在押上公司之前請核對來源。",
        },
      ],
    },
    {
      slug: "why-score-changed",
      section: "scoring",
      title: "為什麼我的分數變了？",
      summary: "重新執行、目標變更、新表述，以及正常的評分波動。",
      eyebrow: "疑難排解",
      tags: [
        "variance",
        "different",
        "flip",
        "borderline",
        "noise",
        "rerun",
        "波動",
        "變化",
        "翻轉",
        "邊緣",
        "雜訊",
        "重新執行",
      ],
      blocks: [
        {
          type: "ul",
          items: [
            "你改了想法表述、目標或創辦人背景：分數理應變化。",
            "邊緣分數：產品會標記你處於閾值附近、存在執行間雜訊的區間。重新執行落到另一側，並不等於系統壞了。",
            "新證據或淘汰測試結果：實地資料可以誠實地推動需求判斷與判定。",
            "深度驗證：更重的流程可能調整信心度與說明；把它當作第二遍審視，而不是另一個產品。",
          ],
        },
        {
          type: "callout",
          text: "若表述未變但跳變異常，請寫信至 help@validorian.com，並附上想法標題與版本。",
        },
      ],
    },
    {
      slug: "iterate",
      section: "studio",
      title: "迭代而不浪費執行次數",
      summary: "提問、新版本、角度，以及何時重新評分。",
      eyebrow: "工作室循環",
      tags: [
        "ask",
        "chat",
        "version",
        "angle",
        "alpha",
        "wedge",
        "rescore",
        "run",
        "提問",
        "對話",
        "版本",
        "角度",
        "切入點",
        "重新評分",
        "執行",
      ],
      blocks: [
        {
          type: "p",
          text: "一次執行（或完整已評分報告）是會消耗活動額度的深度分析。若只想理解目前評審，請使用「提問」。",
        },
        { type: "h2", text: "什麼會消耗報告？" },
        {
          type: "table",
          headers: ["操作", "是否使用完整已評分報告？"],
          rows: [
            ["提問（就本次分析對話）", "否"],
            ["新版本 + 重新評分", "是"],
            ["比較角度 / 切入點錦標賽", "是，按每個已評分角度計"],
            ["深度驗證", "是"],
            ["淘汰測試工具包、情報、閱讀報告", "否"],
          ],
        },
        { type: "h2", text: "提問（不重新評分）" },
        {
          type: "p",
          text: "圍繞目前報告討論：分數、競品、風險。不建立版本，也不使用完整分析。",
        },
        { type: "h2", text: "新版本" },
        {
          type: "p",
          text: "變更表述、目標或背景後重新評分。在框架或證據有真實變化後再用，而不是每次好奇都跑一次。",
        },
        { type: "h2", text: "比較角度" },
        {
          type: "p",
          text: "角度（有時也稱 alpha 或 wedge / 切入點）是同一核心想法的不同切面或定位。錦標賽在同一證據上對若干切面進行正面對比評分。每個已評分參賽項占用一個報告名額，請有意識地選擇。",
        },
      ],
    },
    {
      slug: "kill-test",
      section: "studio",
      title: "淘汰測試與訪談",
      summary: "在動手建構之前，成本最低的真實世界證明。",
      eyebrow: "實地工作",
      tags: [
        "interview",
        "mom test",
        "buyer",
        "pass",
        "fail",
        "field",
        "訪談",
        "買家",
        "通過",
        "失敗",
        "實地",
        "淘汰測試",
      ],
      blocks: [
        {
          type: "p",
          text: "MAYBE 或 NO-GO 往往不是「在 pitch 裡再努力一點」，而是「帶著事先登記的通過/失敗門檻去和買家談」。",
        },
        {
          type: "ul",
          items: [
            "風險最大的假設：語料未能結算的部分",
            "最便宜的測試（大約一週或更短）及通路",
            "在看到結果之前寫好的通過與淘汰門檻",
            "訪談工具包：該找誰談，以及 Mom-Test 風格問題（關注過去行為與事實，而非對你想法的恭維）",
          ],
        },
        {
          type: "p",
          text: "記錄結果並重新評分，讓判定來自實地資料，而不是希望。",
        },
      ],
    },
    {
      slug: "deep-validation",
      section: "studio",
      title: "深度驗證",
      summary: "何時值得用一次報告名額做更重的流程。",
      eyebrow: "進階",
      tags: [
        "deep",
        "bull",
        "bear",
        "cove",
        "expensive",
        "深度",
        "多空",
        "昂貴",
        "進階",
      ],
      blocks: [
        {
          type: "p",
          text: "深度驗證是可選的更重分析（獨立論證、額外檢查）。它使用一次完整已評分報告，計算成本高於標準流程。",
        },
        {
          type: "ul",
          items: [
            "在想法認真、且你想要第二遍更嚴苛審視時使用",
            "早期草稿與廉價實驗可跳過",
            "它不能替代與真實買家進行的淘汰測試",
          ],
        },
      ],
    },
    {
      slug: "language",
      section: "account",
      title: "語言與 AI 輸出",
      summary: "介面語言 vs 報告正文語言。",
      eyebrow: "語言環境",
      tags: [
        "i18n",
        "korean",
        "translate",
        "globe",
        "locale",
        "語言",
        "翻譯",
        "繁體中文",
        "介面",
        "在地化",
      ],
      blocks: [
        {
          type: "p",
          text: "地球儀切換器設定介面外殼：導覽、按鈕、章節標題、判定印章與標籤。你可按名稱或代碼搜尋語言（例如 Chinese、繁體中文，或 zht）。",
        },
        {
          type: "p",
          text: "AI 撰寫的正文（摘要、競品備註、未決問題）跟隨你產生或重新評分時的活躍語言。舊的英文報告在你以新語言環境重新執行之前會保持英文。",
        },
        {
          type: "ul",
          items: [
            "隨時可從頁首切換語言",
            "儲存資料中的機器碼（判定、標準名稱）保持英文，以確保評分一致性",
          ],
        },
      ],
    },
    {
      slug: "privacy",
      section: "account",
      title: "隱私與你的想法",
      summary: "誰能看到你在工作室中輸入的內容。",
      eyebrow: "信任",
      tags: [
        "private",
        "data",
        "security",
        "share",
        "secret",
        "隱私",
        "資料",
        "安全",
        "分享",
        "機密",
      ],
      blocks: [
        {
          type: "p",
          text: "帳戶中的想法與報告預設私密。它們不會發布在公開動態上。",
        },
        {
          type: "ul",
          items: [
            "你控制擁有每個想法的帳戶",
            "若你建立 API 金鑰，它們僅按該金鑰或帳戶模型存取想法",
            "我們使用模型提供方進行評分與撰寫報告：請勿貼上你不能承擔送出至處理系統的機密",
            "刪除帳戶工具會按產品的帳戶流程移除你的資料",
          ],
        },
        {
          type: "callout",
          text: "關於資料處理的問題：help@validorian.com。",
        },
      ],
    },
    {
      slug: "get-help",
      section: "account",
      title: "向團隊尋求協助",
      summary: "如何聯絡我們，以及應附上哪些資訊。",
      eyebrow: "人工支援",
      tags: [
        "email",
        "support",
        "contact",
        "bug",
        "human",
        "郵件",
        "支援",
        "聯絡",
        "缺陷",
        "人工",
      ],
      blocks: [
        {
          type: "p",
          text: "產品問題、計費或卡住的活動，請寫信至 help@validorian.com。目前支援與聯絡入口均指向同一收件匣。",
        },
        {
          type: "ul",
          items: [
            "請附上帳戶信箱，以及相關時的想法標題",
            "介面缺陷附截圖會有幫助",
            "切勿傳送密碼",
          ],
        },
      ],
    },
  ],
};
